### ISSUE TITLE
How does the Wikidata script select a Facebook icon?

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#10116]
While looking at another issue, I noticed that [McDonalds](https://nsi.guide/index.html?t=brands&k=amenity&v=fast_food&tt=mcd#mcdonalds-d24be7) is using the [South Africa Facebook Logo](https://www.facebook.com/McDonalds.ZA), which currently doesn't show a meaningful McD's logo.

This isn't an issue as such, as [dist_files.js](https://github.com/osmlab/name-suggestion-index/blob/7b58c87d2e48ca2fdcc4c30c2e415a3f438a62da/scripts/dist_files.js#L342) already overrules Facebook to use a Commons Logo, but it did make me wonder why the South African Facebook logo is being chosen by the Wikidata script over the main McDs Facebook, when the main one has a `preferred rank`.

Is it because the South Africa one is the last in the list, does the Wikidata script not factor in `rank`?

**Comment by 1ec5** [comment]
The script does prefer any statement with preferred rank, so I’m unsure why that isn’t working:

https://github.com/osmlab/name-suggestion-index/blob/1a86c90de65e20e13b4402fa7264196b4234d6ac/scripts/build_wikidata.js#L507 https://github.com/osmlab/name-suggestion-index/blob/1a86c90de65e20e13b4402fa7264196b4234d6ac/scripts/build_wikidata.js#L334-L335

It’s only showing up now because someone recently [dumped a ton of regional statements](https://www.wikidata.org/wiki/Special:Diff/2252666134/2257026604) onto the global McDonald’s item, even though each regional subsidiary already has its own item, including [McDonald’s South Africa <small>(Q27923821)</small>](https://www.wikidata.org/wiki/Q27923821). I’m tempted to simply revert the changes, but probably the better option would be to move the statements to the appropriate items.

**Comment by Snowysauce** [comment]
NSi.guide seems to be using the main McDonald's Facebook page and logo as of the latest update/release. After seeing that change, I went back and looked at timestamps, and from what I can tell, the [previous release](https://github.com/osmlab/name-suggestion-index/releases/tag/v6.0.20241014) was published just after midnight US Eastern time on October 14, and the statement for the main McDonald's Facebook page was [changed from normal to preferred rank](https://www.wikidata.org/w/index.php?title=Q38076&diff=prev&oldid=2260578376) about 10 hours later. Thus, all the Facebook statements had equal ranks at the time of the previous write to NSI.guide, and the South African Facebook page was indeed chosen because it was the last listed.

**Comment by UKChris-osm** [comment]
>  and the statement for the main McDonald's Facebook page was [changed from normal to preferred rank](https://www.wikidata.org/w/index.php?title=Q38076&diff=prev&oldid=2260578376) about 10 hours later. Thus, all the Facebook statements had equal ranks at the time of the previous write to NSI.guide, and the South African Facebook page was indeed chosen because it was the last listed.

That makes sense, thanks for looking into that @Snowysauce and thanks @1ec5 for you reply too.
