### ISSUE TITLE
Add opening hours to fitness centres open 24/7

### ISSUE THREAD

**Issue by codeinabox** [osmlab/name-suggestion-index#10170]
Looking at the brands for the tag `fitness_centre` there are some, judging by their name, that are open 24/7 and should have the tag `opening_hours=24/7`. I have already done this for Anytime Fitness #10169 10169

**Comment by Cj-Malone** [comment]
I'm a little nervous about this, just because most of them are, doesn't mean they all are. Eg Waffle House has this, but [this one](https://locations.wafflehouse.com/crawfordville-fl-2468/) should be `opening_hours=Mo-Su 07:00-21:00`. Plus there is the "closed for renovation/maintenance" type things which become really hard to tag/keep in OSM as iD will recommend:
```patch
-opening_hours=off
+opening_hours=24/7
```

**Comment by Cj-Malone** [comment]
There is also the conversation of what does "24/7" mean, which according to OSM old timers it includes public holidays `opening_hours=Mo-Su,PH 00:00-24:00`, however most OSM contributors think it means `opening_hours=Mo-Su 00:00-24:00`. This may be less of an issue for gyms, but I wouldn't expect cafes or restaurants to be open on Christmas day.

**Comment by LaoshuBaby** [comment]
For those kind of large brand, keep 24/7 opening time for every branch store is hard, I think we should must be cautious when make such assume.

**Comment by Snowysauce** [comment]
This reminds me of a couple of entries I found once where `addr:state` somehow made its way into the preset tags. They had correct values for the entries in question, but I removed them because only those two entries had such tags out of the tens of thousands of NSI presets. The NSI technically could deliver this type of content to OSM, but I viewed that kind of thing as being outside of the scope of the NSI - and apparently others do as well, or we'd already have various address tags all over the place.

Tying that anecdote to this issue, if we go ahead with providing this content to OSM via the NSI, I feel like it opens the door to `opening_hours` tag presets for any retail chain that supposedly has identical opening hours for all of their stores, whether those hours are 24/7 or not. I don't know if that's a road we should be going down.

**Comment by bhousel** [comment]
Oh I guess it was me that started adding `opening_hours=24/7`: https://github.com/osmlab/name-suggestion-index/issues/2509

I like the suggestion of using `"preserveTags": ["opening_hours"]` to prevent it from being replaced by `24/7` if the mapper knows better.

**Comment by UKChris-osm** [comment]
> I like the suggestion of using `"preserveTags": ["opening_hours"]` to prevent it from being replaced by `24/7` if the mapper knows better.

Is it possible to apply a blanket setting for `"preserveTags": ["opening_hours"]` across the NSI, rather than needing to apply it to each instance of tagging opening hours? Even for non-24/7 hours, I feel like the NSI trying to apply hours in any scenario could be a problem if it's not able to be overridden locally.

**Comment by bhousel** [comment]
> Is it possible to apply a blanket setting for `"preserveTags": ["opening_hours"]` across the NSI, rather than needing to apply it to each instance of tagging opening hours? Even for non-24/7 hours, I feel like the NSI trying to apply hours in any scenario could be a problem if it's not able to be overridden locally.

iD has a list of additional tags to preserve, so someone could add it to this list here:

https://github.com/openstreetmap/iD/blob/b5d45e3f28ccb9a39d243e7504415152e1ce8ec2/modules/services/nsi.js#L584
