### ISSUE TITLE
Research needed for: shop/beauty|Sally Beauty Supply

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1047]
#### :thinking: We need help deciding what to do with "shop/beauty|Sally Beauty Supply"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/beauty|Sally Beauty Supply` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/beauty|Sally Beauty Supply`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/beauty|Sally Beauty Supply`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by skorasaurus** [comment]
note to self to do this later; I'd suggest instead to use the tag [shop=hairdresser_supply](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dhairdresser_supply) instead of shop=beauty. 
since Sally's don't offer any services (haircuts, manis, pedis etc) but they sell the supplies (colorings, nail polishes, shampoos, conditioners, etc) to do so;

**Comment by bhousel** [comment]
Thanks @skorasaurus  - I will make the change

**Comment by skorasaurus** [comment]
Thanks @bhousel ! Perhaps I misunderstand the structure of canonical.json, but shouldn't shop=hairdresser_supply be used in this [commit ](https://github.com/osmlab/name-suggestion-index/commit/20686057b34d0c4c07f37374027362f991a7f9f4#diff-35fa2c3f816f55751604c86b03c3a475R24664) at line 24644 instead of shop=beauty since that line represents the tag to be used going forward?

**Comment by good-praxis** [comment]
I cautiously pushed the suggested change to master, we can always revert it if it's a bad change. I'll reopen it for now and let @bhousel do QA

**Comment by bhousel** [comment]
good catch @skorasaurus  and thanks @good-praxis for the quick fix 👍
