### ISSUE TITLE
Research needed for: shop/convenience|Food Mart

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1262]
#### :thinking: We need help deciding what to do with "shop/convenience|Food Mart"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/convenience|Food Mart` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/convenience|Food Mart`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/convenience|Food Mart`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by PrimeN** [comment]
Hey There, Can I have this issue assigned to me?

**Comment by Adamant36** [comment]
Hello. You don't need issues assigned to you. You can just create a fork and do a PR for it. It might be worth making sure its not a generic term first though. If it is, it can at least be removed from the index.

**Comment by Adamant36** [comment]
For anyone interested, these are generic convenience stores attached to gas stations in America. Which is where most of them are mapped. 

I'm not sure if they should be added to the warning list or not though. Since most places do have signs outside saying food mart, but it might be adding so that people will tag them more specifically with the gas station name. Like "Shell Food Mart" if its a Shell gas station. Its the call of whoever decides to deal with this I guess.
