### ISSUE TITLE
Research needed for: shop/convenience|Tiger Mart

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1303]
#### :thinking: We need help deciding what to do with "shop/convenience|Tiger Mart"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/convenience|Tiger Mart` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/convenience|Tiger Mart`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/convenience|Tiger Mart`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by matkoniecz** [comment]
https://www.wikidata.org/w/index.php?title=Special:Log&page=Q57643977 was deleted

**Comment by matkoniecz** [comment]
I opened https://www.wikidata.org/wiki/Topic:Ux8dwrn1pixolm7a (please do not jump into discussion and let him/her respond).

**Comment by bhousel** [comment]
> https://www.wikidata.org/w/index.php?title=Special:Log&page=Q57643977 was deleted

yeah I noticed this yesterday too.. 

There are a bunch (well maybe a dozen or so) of our pages that were deleted like this.  I did get the admins to undelete one for me once before, but it might be nice to get someone who is familiar with both projects to help streamline the undeletions.

**Comment by matkoniecz** [comment]
I am not sure how close Wikidata culture is to Wikipedia culture, but I assume that it was a mistake - either on our side and it was created as substub without minimal content or it was deleted by accident.

In both cases asking on discussion ow whoever pressed delete button is the best solution (at least on Wikipedia).

Wikipedia (maybe also Wikidata) has unending flood of spam and vandals (unlike OSM where it is fairly rare), so false positives are not rare especially for borderline cases.

**Comment by matkoniecz** [comment]
In case of long inactivity of Pasleim or lack of reply next step is probably https://www.wikidata.org/wiki/Wikidata:Administrators'_noticeboard (I found no dedicated place for undeletion requests)

**Comment by Adamant36** [comment]
I've noticed from going through a lot of the wikidata entries for companies in the index that a good partition of them don't even have descriptions. Let alone anything else that would qualify them as notable. So, there could be more of a job done on our part to fill in as much extra information for entries as we can, not just ones that we create ourselves. 

Hopefully the admin that deleted this one responds by telling you what would help notability. That's something I'm not clear on myself. Currently a lot of the stuff I add to Wikidata entries seems like throwing paint at the wall to see what sticks. I know adding social media links probably helps a little bit, but anyone can create social accounts for a company. My second thought was making sure there's a reference to the businesses apple id # if there is one. Since you have to be semi-legitimate to run an app on iTunes, but who knows if that actually helps. Listing who owns the brand if anyone does might be good, especially if the owner has a Wikipedia page themselves, but I don't know if that helps much either. 

Anyway, it might be worth mentioning in the admin channel know matter what the person did the current deletion says. The more information we get about nobility the better. Its hard to find "serious and publicly available references" for a lot of the more obscure foreign brands, but I don't think that means they aren't notable or shouldn't have Wikidata entries. So I'm interested to see what is said about it.  In the meantime though, we should still do as much as we can our side to fill out all the information we can on entries. I've been compiling a list of common fields for things, that I plan to put into a how to guide eventually, but I haven't had time to work on it lately unfortunately.

**Comment by matkoniecz** [comment]
I posted in https://www.wikidata.org/wiki/Wikidata:Administrators%27_noticeboard#Explanation_request_for_Q57643977

**Comment by matkoniecz** [comment]
Undeleted after https://www.wikidata.org/w/index.php?title=Wikidata:Administrators%27_noticeboard&diff=929065780&oldid=928932531

Apparently shorter messages with just undeletion request work better

**Comment by Adamant36** [comment]
I think number 3 on the nobility thing confirms my suspicions that it's worth adding operator/owner tags to entries and Wikidata pages where we can (with the company also linked to on it's owners page).

"It fulfills some structural need, for example: it is needed to make statements made in other items more useful." 

If I'm understanding it correctly, it means that unique entries for subsidies would meet notability guidelines because they are structurally useful to statements made on their owner's pages.
