### ISSUE TITLE
Research needed for: shop/hairdresser|Top Hair

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1507]
#### :thinking: We need help deciding what to do with "shop/hairdresser|Top Hair"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/hairdresser|Top Hair` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/hairdresser|Top Hair`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/hairdresser|Top Hair`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by ENT8R** [comment]
@Adamant36 why do you think that this is not a generic hairdresser name?

**Comment by Adamant36** [comment]
@ENT8R, because 99% of them are mapped in Germany, and more specifically the Augsburg area. It would be odd if it was a bunch of random businesses that all happened to open in the same area with the same name. Unless "top hair" is generic for a German hairstyle or something that I'm not privy to. It might be. That being said, I wasn't able to find a specific business chain named Top Hair on the internet either. So it probably needs local conformation. I'll change the tags.

**Comment by ENT8R** [comment]
You are right. I just could not find any website and I really thought that this would be a generic hairdresser name, but then I found https://meinfriseur.tophair.com which says that they own about 150 shops throughout Germany. I will add an entry for this now.

**Comment by Adamant36** [comment]
Awesome. I thought so. Good find btw. I researched it a couple of times myself and couldn't find anything.
