### ISSUE TITLE
Query mediawiki API for missing wiki tags

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#151]
My original idea to attack #38 over the next month was to extract all of the "uncomplicated" cases for this index and create GitHub issues for each one so that people can look up the `brand:wikidata` and `brand:wikipedia` tags for us.  

Where "uncomplicated" means - there is no potential duplicate with another entry and there is not already a `brand:wikipedia` and `brand:wikidata` tag.

There are 3029 such "uncomplicated" cases.. which is a lot.  More than the number of Pull Requests I feel like merging.  We can be pretty sure that not all of these are real brands, but a lot are:

<img width="288" alt="screenshot 2018-09-24 13 33 50" src="https://user-images.githubusercontent.com/38784/45968338-ab386b80-bffe-11e8-9589-96aa6b0f3a2a.png">

So I'm now thinking it's probably worth spending a few days to experiment with querying mediawiki API directly.  My thought is to build a quick script that looks up each item, and returns the top wikidata result with a prompt like:
```
Fuddruckers (Q5507056) 
instance_of: ['restaurant_chain']
brand:wikidata=Q5507056
brand:wikipedia=en:Fuddruckers
Accept these tags [y/N]?"  
```
so I can very quickly trim down the list.

**Comment by 1ec5** [comment]
> ```instance_of: ['restaurant_chain']```

This is the hard part. Many restaurant chains have been tagged with more specific statements, like “instance of” [fast food restaurant chain](https://www.wikidata.org/wiki/Q18509232). The [Wikidata Query Service](https://query.wikidata.org/) would be the most obvious tool for finding entities that have matching names and are any kind of chain at all. I’d suggest downloading these SPARQL query results to match against; there’s also an API for doing so automatically:

* [Chain stores](http://tinyurl.com/y9n9jylp)
* [Restaurant chains](http://tinyurl.com/y7u3dfcr)

A lot of the restaurant chains imported into Wikidata from Wikipedia haven’t had any human attention yet, so they haven’t been tagged with “instance of” statements yet, but they have been sorted into the relevant categories on Wikipedia. As with Wikidata, Wikipedia categories form a graph. Use [PetScan](https://petscan.wmflabs.org/) to come up with a list of chains that traverses this graph:

* [Restaurant chains](https://petscan.wmflabs.org/?psid=5910688)

Wikipedia categories are a little messier than Wikidata statements, because you can have things like [Waffle House people](https://en.wikipedia.org/wiki/Category:Waffle_House_people) appearing under Waffle House. So you need to filter out certain category trees:

* [Restaurant chains excluding people](https://petscan.wmflabs.org/?language=en&project=wikipedia&depth=4&categories=Restaurant%20chains&negcats=People&ns%5B0%5D=1&search_max_results=500&interface_language=en&active_tab=)

That’s pretty slow, so intersecting with smaller categories might work better:

* [Restaurant chains excluding restauranteurs](https://petscan.wmflabs.org/?psid=5910831)

It isn’t going to be perfect – _[The Pizza Head Show](https://en.wikipedia.org/wiki/The_Pizza_Head_Show)_ appears if you recurse deeply enough – but hopefully an intersection between this set and the name suggestion index should yield something pretty clean.

**Comment by 1ec5** [comment]
[Reasonator](https://meta.wikimedia.org/wiki/Reasonator) could also be useful here. It’s what many Wikipedia language editions show on the “article not found” page when you look up an article title that doesn’t exist yet in the current language.

**Comment by bhousel** [comment]
hey @1ec5 I realize I probably said the wrong thing in my original message.. 

I'm not planning to put `instance_of: ['restaurant_chain']` in the search.
I'm planning to search only for the name, and display alongside that result whatever `instance_of`(P31) values there are, just to be able to make a quick yes/no decision about whether the search found the right thing.

For example, a `wbsearchentities` query like this:
https://www.wikidata.org/w/api.php?action=wbsearchentities&search=Starbucks&language=en&limit=1&format=json&uselang=en

Returns
```
{"searchinfo":{"search":"Starbucks"},"search":[{"repository":"","id":"Q37158","concepturi":"http://www.wikidata.org/entity/Q37158","title":"Q37158","pageid":39710,"url":"//www.wikidata.org/wiki/Q37158","label":"Starbucks","description":"American multinational coffee company","match":{"type":"label","language":"en","text":"Starbucks"}}],"search-continue":1,"success":1}
```

So we can reasonably assume `brand:wikidata=Q37158` based on `"description":"American multinational coffee company"`, but we know they don't all have good descriptions..

So I'd then fire off a SPARQL like this:
```
SELECT ?isa ?isaLabel WHERE {
   wd:Q37158 wdt:P31 ?isa.
   SERVICE wikibase:label {
     bd:serviceParam wikibase:language "en" .
   }
}
```

Which returns stuff like:

isa|isaLabel
---|---
wd:Q4830453|business
wd:Q507619|chain store
wd:Q6881511|enterprise
wd:Q1252971|food manufacturer

(TODO and also figure out how to get its 'en' brand:wikipedia) page

And display something like:
```
Matched:  Starbucks (Q37158) 
  American multinational coffee company
  instance_of: ['business','chain_store','enterprise','food manufacturer']
brand:wikidata=Q37158
brand:wikipedia=en:Starbucks
Accept these tags [y/N]?"  
```

**Comment by bhousel** [comment]
It kind of works

<img width="527" alt="screenshot 2018-09-25 22 42 11" src="https://user-images.githubusercontent.com/38784/46054198-466f3500-c114-11e8-9682-a756442b89de.png">

**Comment by bhousel** [comment]
Cooking with gas.. 🔥  

<img width="533" alt="screenshot 2018-09-26 01 39 48" src="https://user-images.githubusercontent.com/38784/46059409-1f712d00-c12d-11e8-899a-5af3bd5a5d2c.png">

**Comment by bhousel** [comment]
Latest version 
- each result returns top 3 results
- I can zip through them quickly by pressing number keys


![matching wiki tags](https://user-images.githubusercontent.com/38784/46118124-fefbae00-c1d2-11e8-9e10-f3b5d678192c.gif)

**Comment by bhousel** [comment]
This was done

**Comment by nyurik** [comment]
Just an FYI - you could also use [Sophox Editor](https://wiki.openstreetmap.org/wiki/Sophox_Editor) for something like this -- essentially query OSM data, use a federated query to pull corresponding Wikidata or multiple choice items, and offer the yes/no/pick dialog to the user to actually decide and make an edit.  In this case you would only need to write a SPARQL query, and you can easily share it with others.  I know Sophox wasn't available for the last half a year, but it is back online now :)
