### ISSUE TITLE
Research needed for: shop/mobile_phone|Three

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1553]
#### :thinking: We need help deciding what to do with "shop/mobile_phone|Three"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/mobile_phone|Three` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/mobile_phone|Three`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/mobile_phone|Three`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by lakedistrictOSM** [comment]
Global brand:

- https://en.wikipedia.org/wiki/3_(telecommunications)
- Q407009

UK-specific brand:

- https://en.wikipedia.org/wiki/Three_UK
- Q19840922

If search terms are a thing here, I'd include "3"

**Comment by Adamant36** [comment]
Hi @lakedistrictOSM. I was just thinking about this one while I was cleaning leafs out of my backyard (weird thing to think about, I know). Going by OverPassTurbo it appears there's 54 instances of `name=3 + shop=mobile_phone` versus 2 for name=three so it might be worth having separate entries for them or maybe making the entry for 3 and having three be a match for it. I didn't check the location 3 but if its worldwide it doesn't really matter anyway. 

Here's the if you want to check it yourself  (I'm pretty sure you can copy and paste it).

[out:csv(::count)][timeout:250];

nwr["name"="3"]["shop"="mobile_phone"];
  
out count;

**Comment by ENT8R** [comment]
The situation seems to be the following:
the brand is operating worldwide, but there is no real consensus about how they are naming a store. Judging only from images and the data from Overpass Turbo the most common names are `shop/mobile_phone|3` or `shop/mobile_phone|Three`. Both have nearly the same amount, which is why I would propose to leave it open to the local mapper to choose which one he wants to use. So I added the same information which does already exist for the entry of `shop/mobile_phone|3` to the entry of `shop/mobile_phone|Three` with https://github.com/osmlab/name-suggestion-index/commit/99000e203ac9043afd5049ce62d47fcad6313d4a
If you think that those two entries should be merged, tell me 👍

**Comment by bhousel** [comment]
I'd probably combine them into the single 
"shop/mobile_phone|Three" entry, 
and add a tag `"short_name": "3"`  

It's ok to keep them separate though if that's what people really want to do.
