### ISSUE TITLE
popular restaurant names that are not united in one brand

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#157]
Among restaurant there area names that are popular, but that is not because it is a brand but because it is a good name for restaurant. I would expect that some of names below are (at least in part) not branded.

In that case I would drop brand tag and keep name to help mappers select restaurant correctly

 - [ ] Asia
 - [ ] Athen
 - [ ] Canteen
 - [ ] Cantina
 - [ ] Capri
 - [ ] Carpe Diem
 - [x] Casablanca - removed
 - [ ] China Town
 - [ ] Dolce Vita
 - [ ] Europa
 - [ ] Gusto
 - [ ] Kreta
 - [ ] Mamma Mia
 - [ ] Mensa
 - [ ] Milano
 - [ ] Namaste
 - [ ] Napoli
 - [ ] Oasis
 - [x] <s>Olive Garden</s> US chain, turned out to be OK on checking
 - [ ] Osaka
 - [ ] Poseidon
 - [ ] Rhodos
 - [ ] Rose
 - [ ] Saigon
 - [ ] San Marco
 - [ ] Santorini
 - [ ] Shanghai
 - [ ] many between Shanghai and Venezia
 - [x] Venezia  - removed - turned out that following is incorrect - <s>(note that it seems that Venezia ice cream chain exists in Germany based on overpass turbo results but I found no Wikidata entrey, WIkipedia Page or confirmation that it exists)</s>
 - [ ] many other

**Comment by matthijsmelissen** [comment]
Honest question: does it matter if it is a brand name or not? If I enter a restaurant and want to fill in the name field, wouldn't it be useful anyway if autocomplete proposes 'Napoli' as a name? What do you think @bhousel?

Olive Garden is a mayor US chain by the way, and does not belong in this list.

**Comment by matkoniecz** [comment]
> Honest question: does it matter if it is a brand name or not?

In that case adding brand tag is not really useful (and AFAIK without #158 various independent restaurants operating under name "Panorama" would have common Panorama tag).

**Comment by matthijsmelissen** [comment]
> In that case I would drop brand tag and keep name to help mappers select restaurant correctly

I overread this sentence, I think that makes sense.

In general, I'm not quite sure if it makes sense to automatically add a brand tag if it is equal to the name tag. I see iD also doesn't do this at the moment, but maybe it still uses an old version of name-suggestion-index?

**Comment by matkoniecz** [comment]
> maybe it still uses an old version of name-suggestion-index?

Probably it is using old version, this version of name index was in large part automatically generated and requires review by humans (and someone from China, Japan, Korea and Russia should read through all names in their languages - based on what I noticed in my local names and some in English there are many things that should be fixed)

**Comment by bhousel** [comment]
>Honest question: does it matter if it is a brand name or not? If I enter a restaurant and want to fill in the name field, wouldn't it be useful anyway if autocomplete proposes 'Napoli' as a name? What do you think @bhousel?

My goal for this project is for every entry to be a brand with a `brand:wikidata` tag.

For example, there may be 100s of restaurants called "Golden Dragon", or "Pizza Napoli" but if they are not all operating as brands, I don't want them in the index.  There may be some usefulness in autocompleting common names, but I would rather have the mapper supply the name in that case (what if it's really "Pizzaria Napoli" and they are just picking a wrong thing because it was autosuggested to them by iD). 

Brands are special because they all really should share a common name and tags.  Once they are all associated with a Wikidata id, they also get a lot more useful, and we can do other things like
- handle mergers and [renames](https://news.dunkindonuts.com/news/releases-20180925) (automated edit to rename "Dunkin' Donuts" to "Dunkin'")
- test OSM for completeness (Dunkin' Donuts says there are over 11,300 locations, how many are actually in OSM?)
- search OSM for brands that are mistagged or missing, and task out fixes (Maproulette challenge to fix misspellings like "Dunkin' Donats"?)

**Comment by matthijsmelissen** [comment]
Thanks for the clarification!

**Comment by ENT8R** [comment]
> Venezia (note that it seems that Venezia ice cream chain exists in Germany based on overpass turbo results but I found no Wikidata entrey, WIkipedia Page or confirmation that it exists)

Venezia is no ice cream chain that exists in Germany 😄 It is just a generic name that probably a lot of operators like... This is also covered by #1977

**Comment by matkoniecz** [comment]
Thanks, I updated the first post.

**Comment by bhousel** [comment]
This is old - Our restaurant regexes in `filters.json` are really good now!
