### ISSUE TITLE
Research needed for: shop/second_hand|Value Village

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1601]
#### :thinking: We need help deciding what to do with "shop/second_hand|Value Village"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/second_hand|Value Village` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/second_hand|Value Village`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/second_hand|Value Village`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by ajashton** [comment]
This one may be complicated because the same business operates under 4 different brand names (Savers, Value Village, Village des Valeurs, & Unique).

- https://stores.savers.com/
- https://en.wikipedia.org/wiki/Savers

Wikidata and Wikipedia only have one entry each (for the Savers name). I'm not sure if it would be appropriate to use the same `brand:wikidata` & `brand:wikipedia` values for the other 3 or not?
