### ISSUE TITLE
reconsider separate brands for shop/department_store|Walmart and shop/supermarket|Walmart Supercenter

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#171]
Currently first have `brand=Walmart` and second have `brand=Walmart Supercenter`.

I would expect both to have to have `brand=Walmart` (that is what I planned for Carefour and Carefour Express).

Note that all walmarts share brand:wikidata and brand:wikipedia.

**Comment by bhousel** [comment]
Oh yeah, I set them up that way because they are really two different things, and they are branded differently in real life.  They both have the same `brand:wikidata=Q483551` though, so it kind of would make sense to me if they all had `brand=Walmart`.  

I guess I'm saying, I don't think it really matters much, because `brand:wikidata` is the more important tag and `brand` is just for humans to look at.

On the iD side, it makes sense to see both "Department Store - Walmart" and "Supermarket - Walmart Supercenter" on the list.

**Comment by matkoniecz** [comment]
> On the iD side, it makes sense to see both "Department Store - Walmart" and "Supermarket - Walmart Supercenter" on the list.

I agree, I am not asking to merge them. I just think that brand tag should be the same for both.

**Comment by bhousel** [comment]
Ok, I made the change - All the various Walmart entries just use `"brand": "Walmart"` now.
