### ISSUE TITLE
in contributing add note about `node match_wikiTags`

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#173]
currently it is not mentioned anywhere from what I see

**Comment by bhousel** [comment]
Yeah I wasn't sure whether to mention it or not.  

My thought was that soon everything in the index will either have a `brand:wikidata` or be discarded, and we won't have a need to run the matching script anymore except after loading a new osm planet file.  

Things are a bit hectic right now because we haven't really updated this project much in 5 years.
