### ISSUE TITLE
[limiting local brand] amenity/cafe|Barista

### ISSUE THREAD

**Issue by ImreSamu** [osmlab/name-suggestion-index#2106]
no `countryCodes`  AND   probably a  Local Brand  ( amenity/cafe|Barista )

```json
  "amenity/cafe|Barista": {
    "count": 68,
    "tags": {
      "amenity": "cafe",
      "brand": "Barista",
      "brand:wikidata": "Q644735",
      "brand:wikipedia": "en:Barista (company)",
      "name": "Barista"
    }
  },
```
Same name - different logos - 
https://www.facebook.com/search/str/Barista+cafe/keywords_places/
Examples:
* http://barista.se/
* https://www.facebook.com/Cafe-Barista-114200171994144/

**Comment by ENT8R** [comment]
Looks to me like this would be a generic name because it is split all over the world: https://overpass-turbo.eu/s/D02
But as the item links to a chain existing in South Asia (according to the wikipedia article in India, Maldives, Sri Lanka and Nepal), I think we should maybe add `"countryCodes": ["in","lk","mv","np"]`

**Comment by good-praxis** [comment]
Barista is also kind of generic, so I expect a bunch of one-off Barista shops here and there, too

**Comment by good-praxis** [comment]
I think the majority of listings will be generic, Barista is, after all, just a profession

**Comment by bhousel** [comment]
> But as the item links to a chain existing in South Asia (according to the wikipedia article in India, Maldives, Sri Lanka and Nepal), I think we should maybe add `"countryCodes": ["in","lk","mv","np"]`

☝️  I did this
