### ISSUE TITLE
Add entry for: Sodimac

### ISSUE THREAD

**Issue by sguinetti** [osmlab/name-suggestion-index#2357]
[Sodimac Website](http://www.sodimac.com/)
[Wikipedia](https://es.wikipedia.org/wiki/Sodimac)
`brand=Sodimac`
`shop=doityourself`

**Comment by Adamant36** [comment]
Hi there. I noticed you added a bunch of issues for adding new entries. Do you any experience with coding?   If so, there's a guide for how to contribute in the CONTRIBUTING.md. They will probably get added quicker if you add them yourself and we can always use new contributors.

**Comment by sguinetti** [comment]
Hello.Unfortunately I do not have much experience in npm coding. Thanks for asking. Although I know some franchises of Peru and, out of curiosity, I found this Github repository. So I'm adding what I have in my notes.

**Comment by Adamant36** [comment]
If you have general coding experience its not that difficult. Adding new entries only takes editing one file and its all pretty uniform. If its not something you want to do though, I guess someone else add them at some point. 

Btw, we don't really include websites in the index since they usually be found on the company's Wikidata page. So one thing that might be worth doing on your end if you want is checking that the Wikidata entries have links to the websites and adding them if not. It should be fairly easy if you want to do it.

**Comment by sguinetti** [comment]
Maybe at another time I will make contributions with this mode of code. For the rest, I hope the review goes well.

**Comment by sguinetti** [comment]
@Adamant36 Hello again. Is canonical.json this file for editing? If so, I know something about JSON coding (without npm). As I see it is easy to add information (like #2350 right?). Reviewing Marathon Sports  #2355, I can add without much mess. Thanks for the suggestion.

**Comment by matkoniecz** [comment]
https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md should help

If it is not good enough - open an issue with explanation what is unclear

**Comment by Adamant36** [comment]
@sguinetti yes it is if your just adding new companies. Id follow @matkoniecz's advice anyway though by going through the guide and opening an issue for anything in it that's not clear. Its always better to read instructions if there are any versus not. Plus, guidelines always need improving :)
