### ISSUE TITLE
Licensing of database in this repository

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2437]
There is a BSD 3-Clause applied to this repository https://github.com/osmlab/name-suggestion-index/blob/master/LICENSE.md (result of #37)

But dataset was in large part produced from OSM database (" Regenerate files from current planet " type commites like https://github.com/osmlab/name-suggestion-index/commit/bd13dd87004bdeeb359ccca858ecde89ebc5f6b7 ) - what would make distributed brand database ODBL licensed, right?

**Comment by bhousel** [comment]
Oh! This actually came up a while ago because some folks from Wikidata were asking @1ec5 when he showed off the project at their Wikimania conference last year.
  
I actually asked someone from LWG about this a while back, and their take was that it's not a substantial extract of the database, just some analysis/statistics run against it.  We don't even include any location data in the index that we're producing.  So there really isn't anything that would trigger an ODbL concern.

**Comment by matkoniecz** [comment]
> I actually asked someone from LWG about this a while back, and their take was that it's not a substantial extract of the database, just some analysis/statistics run against it.

That is surprising to me. But given that it is about a copyright law the surprise is not surprising.
