### ISSUE TITLE
Update Acme with wikidata

### ISSUE THREAD

**Issue by yoasif** [osmlab/name-suggestion-index#2457]
http://osmlab.github.io/name-suggestion-index/brands/shop/supermarket.html#shopsupermarketacme

https://www.wikidata.org/wiki/Q341975

**Comment by bhousel** [comment]
Thanks for all the issues @yoasif - Are you interested in submitting Pull Requests also?  
If not, that is ok!   But since you are doing all the work of researching these brands, it is just a few quick extra steps to get them added to the index, and I'm happy to walk you through the process if you want.

**Comment by yoasif** [comment]
I can't figure out how to do a pull request from the command line after I have edited the file and run a build. Installed "hub" and I got stuck at trying 

git push origin feature
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

after forking.

**Comment by matkoniecz** [comment]
You are starting with git, right?

I remember using at first https://desktop.github.com/ (though it is redesigned now, so I am not sure is it a still good for a beginner).

----

You may also edit directly in browser - https://github.com/yoasif/name-suggestion-index/blob/master/brands/shop/supermarket.json should have edit link icon leading to in-browser editor.

----

https://guides.github.com/activities/hello-world/ also may be useful

**Comment by yoasif** [comment]
It isn't fun, but I am using the GH website for this for now.
