### ISSUE TITLE
npm run logos should not overwrite all entries or logo cache should not be stored in human editable file

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2472]
Currently logo cache is completely overwritten by running `npm run logos`.

It means that editing `logos` entry by human is futile.

I think that it would be preferable to keep data in `brands` human editable.

Moving logo cache to a separate folder would be one solution, to avoid encouraging tweaking logos by humans - see https://github.com/osmlab/name-suggestion-index/pull/2467/files (PR that edited logos).

Second solution would be to stop `npm run logos` from automatically overwriting data.

**Comment by bhousel** [comment]
I agree, I'll move them to a separate file

**Comment by bhousel** [comment]
I did this, and it's much better now!    Thanks @matkoniecz for the suggestion 👍 

- the logos are not in the brand files anymore
- `npm run logos` is now `npm run wikidata` (old one still works)
- we're saving the fetched Wikidata info to `dist/wikidata.json`.  

This cached data may be useful to downstream projects too.  I also reuse it when generating the `docs/` pages (so `npm run docs` runs a lot faster now, as we don't have to re-fetch the labels, descriptions, etc).

Another minor change - I'm fetching each brand's `official_website` claim now, and I've added these links to the docs pages here:  http://osmlab.github.io/name-suggestion-index/brands/index.html

This is super convenient because the brand's official website is usually the best place to lookup their Facebook/Twitter/Instagram links.
