### ISSUE TITLE
uk:Мережа АЗС Приват (Q12122687) may be fuel station brand

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2484]
It was removed to mitigate #2479 

@tohaklim Is https://uk.wikipedia.org/wiki/%D0%9C%D0%B5%D1%80%D0%B5%D0%B6%D0%B0_%D0%90%D0%97%D0%A1_%D0%9F%D1%80%D0%B8%D0%B2%D0%B0%D1%82 describing generic fuel station or is it an existing brand?

If it is an existing brand - how it is typically tagged in OSM?

**Comment by Adamant36** [comment]
I've researched about 90% of the issues at this point and I'd say most of the Russian ones are junk. At least the ones left are. There seems to be a massive amount of random, nonsensical Russian tagging in the Ukrainian area. The language is Ukrainian. It just means "Private A3C Chain." So my best guess is that it's bunk.

**Comment by tohaklim** [comment]
> It was removed to mitigate #2479
> 
> @tohaklim Is https://uk.wikipedia.org/wiki/%D0%9C%D0%B5%D1%80%D0%B5%D0%B6%D0%B0_%D0%90%D0%97%D0%A1_%D0%9F%D1%80%D0%B8%D0%B2%D0%B0%D1%82 describing generic fuel station or is it an existing brand?
> 
> If it is an existing brand - how it is typically tagged in OSM?
It appears to be an offhand reference for a group of semi-linked/semi-branded owned by some group in the Ukraine. So it is a brand, but the partial match between one of the words in this brand name and the generic Russian word for a fuel station was wrong.

@Adamant36 Yes, Russian tagging is a mess from the name-suggestion point of view, because you get same-name places that are not under the same brand, and, even worse, generic name tagging for shop=yes name=shop

**Comment by Adamant36** [comment]
> @Adamant36 Yes, Russian tagging is a mess from the name-suggestion point of view, because you get same-name places that are not under the same brand, and, even worse, generic name tagging for shop=yes name=shop

Thanks for the info. I was thinking that was the case. Hopefully whatever gets dealt with in the name index will lead to things being mapped better there. The style is stopping rendering of shop=yes also. Which will probably help with better shop type tagging.
