### ISSUE TITLE
Facebook logo: type=large offers higher resolution than type=square

### ISSUE THREAD

**Issue by ENT8R** [osmlab/name-suggestion-index#2491]
https://github.com/osmlab/name-suggestion-index/blob/e4bd2327d95c08d8ed3a94b13707e8b0401487e3/fetch_logos.js#L129

Is there a reason why you are using `type=square` rather than `type=large`?

`type=large` offers a better resolution than `type=square`:

`type=square` | `type=large`
--- | ---
<img src="https://graph.facebook.com/Dominos/picture?type=square" height="100px"> | <img src="https://graph.facebook.com/Dominos/picture?type=large" height="100px">

Though the size of the file of course also increases 😄

**Comment by bhousel** [comment]
Good question - it's to fit inside this 60x60px space in iD's sidebar:

<img width="300" alt="Screenshot 2019-03-18 12 52 27" src="https://user-images.githubusercontent.com/38784/54547750-c1573100-497c-11e9-872a-13c5733e6a42.png">

Or this 40x40 space on iD's new ribbon:

<img width="300" alt="Screenshot 2019-03-18 12 52 07" src="https://user-images.githubusercontent.com/38784/54547771-ca480280-497c-11e9-8c0f-af5fb28ea289.png">

I think the `square` option returns a 100x100 icon.

Some more details about logos:
- Facebook/Instagram profile URLs can be fetched from [Facebook's Graph API](https://developers.facebook.com/docs/graph-api/reference/user/picture/).  It has a GET endpoint that anybody can use without authentication.  This is nice!  iD actually could construct these URLs on the fly if it wanted to.
- Twitter profile URLs can be fetched through the [Twitter API](https://developer.twitter.com/en/docs/accounts-and-users/user-profile-images-and-banners.html) however you need an app key to use their API and there are some strict rate limits, so that is why we need to cache the logo urls.  I'd rather not!
- Wikidata's logo URLs can be anything - it's just whatever URL people attach to property P154.  They are often not at all square, and sometimes just pictures of the front of a building or a plate of food.

So for the purposes of showing a logo in iD, I'll probably do Facebook/Instagram first, Twitter as fallback, and Wikidata as next fallback.  

I know this is heavily biased towards iD.. but if other projects want to use the logos, I'm happy to change what we do in name-suggestion-index to make it more useful for other projects too.  For #2472 I will be moving all of the cached Wikidata properties and logos into a separate file.

👉 __A very useful thing that anybody can do__ is go through the browsable index 
http://osmlab.github.io/name-suggestion-index/brands/index.html
and for each brand missing a logo, look up the brand's Facebook/Instagram/Twitter/etc accounts and add them all to the brand's Wikidata page.  I was doing this last night, and got through a bunch of the cafes.  It's very easy to do!

**Comment by Adamant36** [comment]
Are you going to be adding Instagram to the catched icon tables in the list of what we have or not? It would be nice to know which ones still need them added to their Wikidata articles.

**Comment by bhousel** [comment]
> Are you going to be adding Instagram to the catched icon tables in the list of what we have or not? It would be nice to know which ones still need them added to their Wikidata articles.

The reason I didn't is because Instagram and Facebook are essentially merged now.  But I can see how it would be useful to add it for checking the brand for completeness.

**Comment by ENT8R** [comment]
Thank you for your very detailed response!

> I think the `square` option returns a 100x100 icon.

It seems to be 80x80 but that does fit too 👍 

> So for the purposes of showing a logo in iD, I'll probably do Facebook/Instagram first, Twitter as fallback, and Wikidata as next fallback.

I don't know if this is the best order because sometimes some brands don't have their logo as a profile picture but some kind of advertisement.
Can be seen e.g. at [Burger King](https://osmlab.github.io/name-suggestion-index/brands/amenity/fast_food.html#amenityfast_foodburger-king) at the moment:

Wikidata | Facebook | Twitter
--- | --- | ---
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Burger_King_Logo.svg/100px-Burger_King_Logo.svg.png" height="80px"> | <img src="https://scontent.xx.fbcdn.net/v/t1.0-1/p50x50/53857832_2613005375379449_4599009186230042624_n.jpg?_nc_cat=1&_nc_ht=scontent.xx&oh=df299a6ed64adfc13cdf4bcc247605e2&oe=5D0DFED5" height="80px"> | <img src="https://pbs.twimg.com/profile_images/834508415942680587/ejWq1bq0_bigger.jpg" width="80px">

Otherwise I don't really know how to prevent this...

BTW: the documentation of the endpoint is this one: https://developers.facebook.com/docs/graph-api/reference/app/picture and not https://developers.facebook.com/docs/graph-api/reference/user/picture/

**Comment by matkoniecz** [comment]
> sometimes just pictures of the front of a building or a plate of food

Maybe accept only svg and small png and refuse 3000px x 2000 px jpg files? This should drop some blatantly wrong data.

**Comment by bhousel** [comment]
> > sometimes just pictures of the front of a building or a plate of food
> 
> Maybe accept only svg and small png and refuse 3000px x 2000 px jpg files? This should drop some blatantly wrong data.

The thing I said above is significantly easier than trying to outsmart the users  😆

**Comment by Adamant36** [comment]
Or maybe we could fix the entries on Wikimedia's side that are suppose to be icons but aren't.

**Comment by bhousel** [comment]
> Or maybe we could fix the entries on Wikimedia's side that are suppose to be icons but aren't.

Yes, this 💯!

**Comment by bhousel** [comment]
> Is there a reason why you are using `type=square` rather than `type=large`?
> `type=large` offers a better resolution than `type=square`:

Update on this - @quincylvania [got them working in iD](https://github.com/openstreetmap/iD/issues/5167#issuecomment-477716355) and the `large` size really does look much better than the `square` size - so I'm going to switch the url in `build_wikidata.js` and refetch them..
