### ISSUE TITLE
Shoprite - mismatch between data in name-suggestion-index and data mapped in OSM.

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2517]
Countries declared in countryCodes field and where such objects are mapped in OSM is not matching.
it may be caused by:
* mistake in countryCodes field (fixable by changing it)
* by different brand using the same name, not present in the index (fixable by adding it to the index)
* mistake in OSM (fixable by editing OSM)
* suspicious data in OSM (fixable by opening an OSM note)

entry data:
````
{
  "count": 355,
  "countryCodes": [
    "ao",
    "bw",
    "cd",
    "gh",
    "ls",
    "mg",
    "mu",
    "mw",
    "mz",
    "na",
    "ng",
    "sz",
    "ug",
    "za",
    "zm"
  ],
  "nomatch": [
    "shop/supermarket|ShopRite"
  ],
  "tags": {
    "brand": "Shoprite",
    "brand:wikidata": "Q1857639",
    "brand:wikipedia": "en:ShopRite (South Africa)",
    "name": "Shoprite",
    "shop": "supermarket"
  }
}
````

Country codes declared in name-suggestion-index:
* ao - 46 mapped entries
* bw - 5 mapped entries
* cd - 1 mapped entries
* gh - 4 mapped entries
* ls - 3 mapped entries
* mg - 16 mapped entries
* mu - 1 mapped entries
* mw - 8 mapped entries
* mz - 51 mapped entries
* na - 43 mapped entries
* ng - 8 mapped entries
* sz - 5 mapped entries
* ug - 1 mapped entries
* za - 290 mapped entries
* zm - 40 mapped entries

Additional countries with object of matching name and type mapped in OSM
im - 35 mapped entries
in - 1 mapped entries
qa - 1 mapped entries
id - 8 mapped entries

you can use following query in the Overpas Turbo Wizard to look at this data:
'shop'='supermarket' and name='Shoprite' global

**Comment by Adamant36** [comment]
@matkoniecz, is country code meant for where the business is mapped or is it meant for where it actually has stores opened? Id think it would be where there is stores open. Otherwise, it wouldn't come up in a search when someone wants to add the business in a new area that it hasn't been mapped in yet. 

But then there's always also the risk that they are different brands in cases where the index has less countries then is mapped and your adding country codes based on it. So....

Considering your issue with using Wikidata/Wikipedia as a source of information (for instance with the cuisine thing), I'm not sure how doing it this way is anymore reliable.

**Comment by matkoniecz** [comment]
> where it actually has stores opened?

This one.

> I'm not sure how doing it this way is anymore reliable.

I am catching cases where OSM mapping indicated wider use than expected by data in the index. As mentioned it requires checking what is happening

```
it may be caused by:

    mistake in countryCodes field (fixable by changing it)
    by different brand using the same name, not present in the index (fixable by adding it to the index)
    mistake in OSM (fixable by editing OSM)
    suspicious data in OSM (fixable by opening an OSM note)
```

For example in this case Isle of Man has its own local brand with the same name.
