### ISSUE TITLE
Add entry for Hunt Brothers Pizza

### ISSUE THREAD

**Issue by rivermont** [osmlab/name-suggestion-index#2586]
`name=Hunt Brothers Pizza`
`amenity=fast_food`  
`cuisine=pizza`  
[website](https://www.huntbrotherspizza.com)  
[Wikipedia](https://en.wikipedia.org/wiki/Hunt_Brothers_Pizza)

**Comment by 1ec5** [comment]
Hunt Brothers locations tend to be counters within convenience stores and the like, rather than eateries unto themselves. I wonder if `takeaway=only` would be appropriate for this entry.

**Comment by Adamant36** [comment]
Am I only one that finds it weird that these are even being added? I mean, most convenience stores have a little place in the back for hot food. It's stretching the amenity=fast_food tag a bit to use it in these cases. 

Something like that just looks like a shelf that sells a certain brand of product. 
![images](https://user-images.githubusercontent.com/30259065/56726839-685d8400-6704-11e9-8ad6-d28ef7ec99e3.jpg)

In America we AMPM's with a hot food thing in the back called "Looking Hot." Could those be tagged as amenity=fast_food then? 

I don't think they deserve to be mapped or have their own entry any more then something like a Little Debbie's donuts stand in a convenience store does as a shop=bakery or whatever. It's kind of implied in the shop=convenience tag that these types of things are provided in convenience stores.

![o](https://user-images.githubusercontent.com/30259065/56727390-719b2080-6705-11e9-9963-12368b535255.jpg)

**Comment by matkoniecz** [comment]
Is it a separate shop or just a shelf in a shop? If one wants to map individual shelves - please do not misuse shop tag or `amenity=fast_food`.

**Comment by bhousel** [comment]
Oh yeah , I agree we should not add an entry for a branded shelf within a convenience store.  @rivermont is that what these are?

**Comment by rivermont** [comment]
I have not physically been to one of the locations to check, only seen them advertised everywhere. They're common enough I figured I would start an entry. Wikipedia notes them as a "food service destination within stores." I agree though that it does not sound like a physical store needing a brand tag.

**Comment by 1ec5** [comment]
I’m of two minds about [store-within-a-store](https://en.wikipedia.org/wiki/Store-within-a-store) food-to-go chains like Hunt Brothers, Krispy Kreme, and Chester’s Chicken. Sometimes it’s just a shelf, other times a counter attached to the convenience store’s checkout counter (staffed by the same person). Some stores-within-stores do get mapped as stores in their own right, like pharmacy counters and taquerías inside supermarkets and veterinarians at big-box pet stores. But convenience stores are much smaller, so the stores inside them are smaller still.

On the other hand, if you look at the monument sign for the gas station along the road, there’s usually a panel for the store-in-store, just like there would be if a McDonald’s were colocated with the gas station (as is sometimes the case). The Shell on the left just remodeled; Chester’s has taken over the checkout counter, so you pay for your groceries while surrounded by fried chicken under heat lamps. The Circle K attached to the Marathon at right has a Beer Cave in the back – a branded walk-in freezer full of alcoholic beverages.

[![](https://images.mapillary.com/0Gt1VT56arO8nQVkMN0xFA/thumb-2048.jpg)](https://www.mapillary.com/map/im/0Gt1VT56arO8nQVkMN0xFA)

Should it matter whether the kiosk’s brand is franchised from a separate company? What if a convenience store has its own “store brand” version of a food-to-go that provides the same service under the same corporate umbrella? What if there’s no separate branding at all? At United Dairy Farmers (#2234), you pay for groceries over tubs of temping ice cream. In that case, I argued for mapping the ice cream parlor and convenience store as a single POI, because it isn’t branded or signposted like a business in its own right and the ice cream parlor’s facilities are scattered around the convenience store.

**Comment by 1ec5** [comment]
So if these POIs shouldn’t be tagged as `amenity=fast_food`, what should they be tagged as, in case a mapper does want to take advantage of name-suggestion-index’s brand tags? [`barrier=shelf`](https://wiki.openstreetmap.org/wiki/OpenLevelUp/Use_cases/Shopping_mall) `product=food`? `natural=cave` `cave=beer`? 😄

**Comment by bhousel** [comment]
Yes, I'm definitely ok with adding them to the index if we can pick a good tag - they just aren't a standalone `amenity=fast_food` or `shop=convenience`.  

This index does contain some other branded things that exist at or inside other businesses (like vending machines, electric vehicle charging stations, etc).

**Comment by Adamant36** [comment]
"like pharmacy counters and taquerías inside supermarkets and veterinarians at big-box pet stores" In the case of pharmacies its because they have their own staff, phone number etc. At least that's how I see it. For vending machine I think its ok to map as a stand alone thing because they are essentially self ran and self maintained. You don't pay for what you get at the chrckout counter and you have to call a special number if the things breaks for a refund. So it makes sense to map them as their own POI. 

None of the pictures I've seen of this thing are self staffed. Its not clear if they are independantly managed by their wiki or website either. If they aren't, and its just hot food from a particular brand that pay for at the main counter and that they make, I don't see how its any different then a shelf.

Maybe there should be a special tag for things like this that gets added to the main conveince store tag or something (like atm=yes), but then why not for the donut shelfs, soda machines, or any other similar things also? Seems like a slippery slope that could lead to a lot of pointless over mapping. Especially if they are mapped as individual poi's.

**Comment by rivermont** [comment]
So in this case it sounds more like Hunt Brothers is a brand of _food_, rather than a brand of _store_. Still a brand but not a good thing to physically map. Perhaps something like `cuisine:Hunt Brothers Pizza=yes` on the store would be an option? I'm inventing tags here but it does sound useful to indicate that the convenience store offers this brand, especially since it's heavily advertised. Adding every brand of item sold at a store is impractical and near impossible, but I think it would be acceptable for specific things like this. (This is all just a thought however)

**Comment by Adamant36** [comment]
So looking at Taginfo I guess there are a little more than 17 of them already mapped. From just a quick glance it seems they are mostly tagged as `amenity=fast_food + cuisine=pizza`.  I called one of the convenience stores on the east coast where it looked like it was tagged separately to see what the deal with them is, but apparently the number no longer works. Shrug.

**Comment by bhousel** [comment]
Ok, since it sound like we don't know what the tagging should be, let's close this for now.  We can reopen it later after more consensus has been reached.
