### ISSUE TITLE
What is actually sold in Value Village?

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2587]
`shop=second_hand` is quite poor as it is completely not specifying what is sold there.

In `second_hand.json` file we have currently two entries - first is using a proper shop type and `second_hand=only`. It would be nice to do the same with Value Village.

```
{
  "shop/second_hand|Buffalo Exchange": {
    "countryCodes": ["us"],
    "match": [
      "shop/second_hand|Buffalo Exchange"
    ],
    "nocount": true,
    "tags": {
      "brand": "Buffalo Exchange",
      "brand:wikidata": "Q4985721",
      "brand:wikipedia": "en:Buffalo Exchange",
      "name": "Buffalo Exchange",
      "second_hand": "only",
      "shop": "clothes"
    }
  },
  "shop/second_hand|Value Village": {
    "count": 82,
    "tags": {
      "brand": "Value Village",
      "brand:wikidata": "Q7428188",
      "brand:wikipedia": "en:Savers",
      "name": "Value Village",
      "shop": "second_hand"
    }
  }
}
```

**Comment by Adamant36** [comment]
Looks like 90% clothes from their website and internet search. The rest is house wears and books. Kind of the same as Goodwill. Kind of makes sense to because there's always a huge amount of clothing being constantly donated to these places. Donations of other things are way more rare  and are usually the result of a dead person's family just wanting an easy way to get rid of their stuff. Or if not that, its a bunch of cheap dollar houseware stuff and are bought and gotten rid of by the truck loads. 

Anyway, maybe clothing store would be better. Since it's their bread and butter. Perhaps with added tags for the books and housewares or something.

**Comment by matkoniecz** [comment]
I posted https://lists.openstreetmap.org/pipermail/talk-us/2019-April/019437.html for additional feedback

**Comment by matkoniecz** [comment]
Appears there is no consensus for a change and given that it would be armchair mapping I will keep it unchanged.
