### ISSUE TITLE
Validator - Do not complain about similar names for utterly different entities

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2638]
See https://github.com/osmlab/name-suggestion-index/commit/d49a46e9c8ee8439a1b50fc52d0bddc62ac5956f that should not be needed, as even with similar name `amenity=car_rental` and `amenity=bank` are something different.

**Comment by bhousel** [comment]
I disagree, I think the similar name warning is helpful.   
The warning code removes noisewords like "bank", that's why it flags both" Nationwide Bank" and "Nationwide".  as similar

Scripts have no way of knowing what "utterly different" means.  The tags are all made up.

Also.. Try to be nicer in your changeset comments.

**Comment by matkoniecz** [comment]
> Also.. Try to be nicer in your changeset comments.

OK, I will try to avoid it. Just as an explanation - it was not intended as negative comment toward anyone, just this match was quite weird one.

> Scripts have no way of knowing what "utterly different" means. The tags are all made up.

Well, that is exactly what I proposed to change (to have pairs of tags where similar names will not be reported)
