### ISSUE TITLE
cuisine tag is missing for amenity=restaurant デニーズ(Japan)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2673]
Is there one that apply to every single location for this poi?
What would be appropriate value for it?

This brand may be described at https://ja.wikipedia.org/wiki/デニーズ_(日本)

entry data:
```
{
  "countryCodes": [
    "jp"
  ],
  "tags": {
    "amenity": "restaurant",
    "brand": "デニーズ",
    "brand:en": "Denny's",
    "brand:ja": "デニーズ",
    "brand:wikidata": "Q11320661",
    "brand:wikipedia": "ja:デニーズ (日本)",
    "name": "デニーズ",
    "name:en": "Denny's",
    "name:ja": "デニーズ"
  }
}
```

summoning @johachi to get info a about Japan

**Comment by johachi** [comment]
I been thinking about how to classify these Japanese "Family Restaurants" since I made my first contribution to this repo. Classifying Japanese Family Restaurants is hard.

This particular restaurant chain was originally a Japanese company licensing the American franchise "Dennys", and one would think that the cuisine tag would therefor be "American", but it is not really that easy. 

They serve [Japanese food](https://www.dennys.jp/menu/teisyoku-lunch/), [Japanese & Western styled steak](https://www.dennys.jp/menu/steak/), [Italian and Japanese pasta dishes](https://www.dennys.jp/menu/pasta-rice-lunch/), and all kinds of food.

However, one could argue that most "Western food" in Japan is really Japanese food. Look up the term [yoshoku](https://en.wikipedia.org/wiki/Y%C5%8Dshoku) on wikipedia. Yoshoku is Japanized western food. When I have asked my Japanese friends, they say that yoshoku is not it is not Japanese food. I guess it is the same as when someone in Sweden say that taco is Mexican. I'm not sure that anyone from Mexico would call their taco "Mexican food". More like Mexican inspired Swedish food, or Swedified Mexican food.

The question is, when does something stop being French/Italian/American food and become Japanese food...

If we agree that yoshoku is Japanese food, then I guess we could write just "Japanese" for cuisine, which is (kind of) correct. But at the same time, yoshoku is not really what most Japanese (or non-Japanese) think about when they hear the english term "Japanese cuisine". Because of that, I would have to recommend the "western;japanese" tag, but I would accept only "Japanese" even though it feels a little bit misleading to me.

**Comment by Adamant36** [comment]
> I would have to recommend the "western;japanese" tag, but I would accept only "Japanese" even though it feels a little bit misleading to me.

I don't know about "western." That's a little vague. America doesn't have a monopoly on being the west and there's a lot of variation in cuisine between western places. For instance Canadian cuisine can be vastly different then American, but they are both "western."

**Comment by matkoniecz** [comment]
> For instance Canadian cuisine can be vastly different then American, but they are both "western."

And that is why I would use `western` where it can not be describes more specifically and serving various dishes that can not be described by something more specific (for example restaurant serving pizza, burgers, foie gras etc).

**Comment by Adamant36** [comment]
> And that is why I would use western where it can not be describes more specifically and serving various dishes that can not be described by something more specific

@matkoniecz, sounds to me from what @johachi said, "Japanese & Western styled steak", that the specifically western thing they serve is steak. Which is clearly American. Plus, it's still a Denny's. Which is a quintessentially American restaurant. Just because it's in Japan and might serve some Japanese dishes doesn't change that. Did you look at the menu links @johachi provided? Nothing there looks "western." Everything none Japanese looks American though. Outside of the steak the only other thing is fried chicken and mashed potatoes/fries. Again, American.

**Comment by matkoniecz** [comment]
> that the specifically western thing they serve is steak.

Not only - see "Italian (...) pasta dishes,"

**Comment by Adamant36** [comment]
> Not only - see "Italian (...) pasta dishes,"

The only "pasta" thing on the menu looks like a basic spaghetti and meatballs. I'd hardly call that authentic Italian. It's also served at every other Denny's in the world. So I guess we should either tag all of them as Italian or change the normal Denny's entry to "western" then? 

https://www.dennys.com/food/dinner-classics/brooklyn-spaghetti-meatballs/

**Comment by johachi** [comment]
> The only "pasta" thing on the menu looks like a basic spaghetti and meatballs. I'd hardly call that authentic Italian. It's also served at every other Denny's in the world. So I guess we should either tag all of them as Italian or change the normal Denny's entry to "western" then? (...)

There would be no need to change "every other Denny's in the world" since there is a distinct difference between the Japanese Denny's and the American Denny's menu. It is not like McDonald's in Japan and America, where the menu is almost the same.

When comparing the American Denny's  and the Japanese Denny's menu, they look very different.


> America doesn't have a monopoly on being the west and there's a lot of variation in cuisine between western places.

This is the exact reason that I would prefer to have the tag `western` instead of `American`.

As stated earlier, for me, only having `Japanese` as a tag might be technically correct, but it feels misleading to me personally. `American` do also not fit that good fit. The Japanese Denny's do not serve typical American foods, like you stated yourself.

**Comment by Adamant36** [comment]
Well, I guess if that's how you want it.

**Comment by johachi** [comment]
> [Well, there's nothing on the menu that looks none American or isn't served in American Denny's already (...)
](https://github.com/osmlab/name-suggestion-index/issues/2673#issuecomment-496394999)

> [Did you look at the menu links @johachi provided? Nothing there looks "western."](https://github.com/osmlab/name-suggestion-index/issues/2673#issuecomment-496370262)

I have a really hard time understanding what your point is. In some posts you say that Denny's in Japan serve mostly Japanese food, and in another, you say nothing looks none American.
