### ISSUE TITLE
MOD Pizza is fast food not restaurant

### ISSUE THREAD

**Issue by roadgeek99** [osmlab/name-suggestion-index#2678]
I've noticed MOD Pizza is in the `amenity=restaurant` category. It should be in the `amenity=fast_food` category because it's basically like the Subway (the sandwich shop) for pizzas. Customers build their own pizzas, pay, wait for it to be baked, and get the pizza themselves. It is not a sit-down restaurant at all. Not sure why people think it's `restaurant`, but it really should be `fast_food`.

**Comment by tas50** [comment]
Fixed by fcf9969ea0025eee4286285df2283732e7c8f2f5

**Comment by Adamant36** [comment]
>  It is not a sit-down restaurant at all.

I'm not sure how that relates. What makes something a restaurant is if an employee brings the pizza to your table for you when it's done or not. It seem's like in this case that they do. Just because the pizza is made by pointing at fresh ingredients, like Subway, versus picking them from a menu doesn't really matter. The speed with which the food is made doesn't matter either. Subway is a fast food place only because you take the sandwich at the counter when your done having it made and the employees don't serve you. That's not the case here. In MOD pizza places you order, sit down, and they bring it to you when it's done. Really, it's no different than any other pizza restaurant. It's just made quicker. 

There was a discussion about this a few days ago, but I can't remember where.

**Comment by tas50** [comment]
One of the big measures was where you order. A lot of fast food places bring the food to you, but there’s no full table service. If you wait in a line and order pizza like a burger at McDonalds but they bring it to you that seems pretty fast food to me. Fast casual blurs the line, but we have a lot of restaurants in the index that should be fast food locations.
