### ISSUE TITLE
no data found at all for E-WALD charging_station

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2706]
``'amenity'='charging_station' and 'name'='E-WALD' global` query finds no entries across the world
entry data:
```
{
  "matchNames": [
    "e-wald ladestation"
  ],
  "tags": {
    "amenity": "charging_station",
    "brand": "E-WALD",
    "brand:wikidata": "Q61804335",
    "name": "E-WALD"
  }
}
```

E-Wald seems to appear - see for example https://www.openstreetmap.org/node/4512397438 (13 in total - see http://overpass-turbo.eu/s/Jqo )

It seems to me that there is no good reason to follow logo styling in this case, plenty of logos and promotional material is using capitalized letters.

**Comment by SilentSpike** [comment]
I think it should be capitalised in the index. That's how the company writes it on their own website.

Existing occurrences may not use it, but 13 isn't many and they will be matched by fuzzy matching for suggested tagging in iD.

**Comment by matkoniecz** [comment]
> writes it on their own website

On their website they use full capitalization also for many other things, I am not convinced that name should actually follow this particular stylistic choice

![Selection_004](https://user-images.githubusercontent.com/899988/58506138-ec38df00-818e-11e9-872b-2b635b564811.png)

**Comment by SilentSpike** [comment]
See https://electrific.eu/partners/e-wald-gmbh where throughout the text it is capitalised

**Comment by Adamant36** [comment]
Its in all caps on the actual charging stations.

**Comment by bhousel** [comment]
Because the company calls itself E-WALD and writes it that way on the charging stations, and it wouldn't look too weird on a map, let's just leave it this way in our index.

I did add a `"countryCodes": ["de"]` .. It seems like that's where they all are located.

Aside:  I wonder whether I should switch the Overpass Turbo links over to use case insensitive regex matching for names?  This query finds them all, with or without the "ladestation":

```
[out:json][timeout:60];
(nwr["amenity"="charging_station"]["name"~"E-WALD",i];);
out body;
>;
out skel qt;
```

Regex matching is a little slower, but I like the idea of finding everything.

**Comment by bhousel** [comment]
> Aside: I wonder whether I should switch the Overpass Turbo links over to use case insensitive regex matching for names?

I did this..
