### ISSUE TITLE
Official name tag should automatically become a matchname

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#2732]
There's a lot of brands out there with short names we use in OSM and then very long official_names that are used often. We've added a good number of those official names in the data set, but they should automatically become matchNames for the brands.

Example:

Total Wine: official name of "Total Wine & More" would become the match name of "total wine more"

**Comment by matkoniecz** [comment]
The question is whatever it should appear in https://raw.githubusercontent.com/osmlab/name-suggestion-index/master/dist/name-suggestions.json and other dist files or is it something that `npm run build` would add to human-editable files?

**Comment by Adamant36** [comment]
> We've added a good number of those official names in the data set, but they should automatically **become** matchNames for the brands.

Hopefully they would stay as official_names in the index also. Instead of being removed. As that would prevent people from unnecessary name re-tagging while mapping or opening pointless PR's based on a perception that the name should be different. It's also useful to have the official name on the map if someone is looking for something and doesn't know the shortened name in my Opinion. As sometimes they can be quit different.

**Comment by bhousel** [comment]
I just did this!

Now the matcher will automatically match on these tags too
    - `alt_name`
    - `official_name`
    - `short_name`

So we don't need to add extra `matchNames` for these anymore.  

These all remain on all the entries as tags, wherever people have added them, so that hasn't changed.
