### ISSUE TITLE
Tesco Express - is it shop=supermarket or shop=convenience? (United Kingdom, with some minor usage in Ireland, Czechia, Hungary, Slovakia, Thailand, South Korea, Sri Lanka)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2740]
Is shop=supermarket sometimes preferable tagging for Tesco Express?

entry data:
```
{
  "tags": {
    "brand": "Tesco Express",
    "brand:wikidata": "Q487494",
    "brand:wikipedia": "en:Tesco",
    "name": "Tesco Express",
    "shop": "supermarket"
  }
}
```

entry data:
```
{
  "nomatch": [
    "amenity/fuel|Tesco"
  ],
  "tags": {
    "brand": "Tesco Express",
    "brand:wikidata": "Q487494",
    "brand:wikipedia": "en:Tesco",
    "name": "Tesco Express",
    "shop": "convenience"
  }
}
```

appears in: United Kingdom [gb] 95%, Ireland [ie] 1%, Czechia [cz] 0%, Hungary [hu] 0%, Slovakia [sk] 0%, Thailand [th] 0%, South Korea [kr] 0%, Sri Lanka [lk] 0%

@SilentSpike, @jeisenbe

**Comment by SilentSpike** [comment]
In my experience Tesco Express is always what I would call a convenience store (plus I think that's the whole purpose of differentiating the name).

I think the issue is that they can be quite big, which makes people think of them as a supermarket. However, they don't have everything a Tesco store usually would (clothing section, kitchenware, etc.) which is why I would say they're a convenience store.

**Comment by ImreSamu** [comment]
> appears in:  **Hungary** [hu] 0%,

in Hungary - we have `name="Tesco Expressz"` ---->  https://taginfo.openstreetmap.org/tags/name=Tesco%20Expressz  ( count = 41  )
We have cleaned ( ~ 7 months ago ; discussed in the local mail list!  current example: https://www.openstreetmap.org/way/353281883 )  
and the  tagging now:
```
    "shop": "convenience",            <-----  because mostly small shops.
    "name": "Tesco Expressz",         <-----   en:Express == hu:Expressz  ; just a different writing.
    ...
    "brand": "Tesco",                 <----- we use this - because it is a "Tesco" Brand! 
    "brand:wikidata": "Q487494",     
    "brand:wikipedia": "hu:Tesco",    <-----  hungarian wikipedia page - for local users.
```

in Hungary we have:

- `Tesco Hipermarket` = hypermarket
- `Tesco Szupermarket`  = supermarket
- `Tesco Expressz`  = ~ convenience      

--------------
imho: the brand name - should be only `brand="Tesco"`  - similar than the wikipedia/wikidata page for human inspection!

**Comment by Adamant36** [comment]
> imho: the brand name - should be only brand="Tesco" - similar than the wikipedia/wikidata page for human inspection!

#2530 covers adding Wikidata entries for Tesco brands. I was actually planning on creating them pretty soon here. After that, it shouldn't really matter. For the sake of the index though, brand name has to be the same as the name name. So if it was brand=tesco + name=tesco express, that really wouldn't work and therefore brand=tesco express or whatever is the only way to go about it. Plus, it's what on the signs anyway. Whatever the title of the wikidata/wikipedia articles is doesn't really matter.

**Comment by bhousel** [comment]
> For the sake of the index though, brand name has to be the same as the name name.

No it doesn't... We can have `brand=Tesco` for all the different kinds of Tesco businesses.

**Comment by Adamant36** [comment]
Oh, my bad. I thought you said somewhere else that it did.

**Comment by bhousel** [comment]
also, is this just #2530?

**Comment by SK53** [comment]
Yes it's important to distinguish between the brand "Tesco" and the format "Tesco Express", "Tesco Metro" or "Tesco Extra" (sp?). Tesco Express in the UK should always be convenience, they are not subject to Sunday opening hours restrictions which is determined by maximum floor area. Tesco Metro are often what were mainstream Tesco stores until they started opening hypermarkets and will typically be located on high streets rather than retail parks or out-of-town. Geolytix produce an detailed open dataset of UK retail, and as they are retail specialists, their approach is worth checking out.

**Comment by jnicho02** [comment]
Here are some UK stats (with no comment as to what is right or wrong):
```csv
shop=		name=			total
"convenience"	"Tesco Express"		714
"supermarket"	"Tesco Express"		586
"supermarket"	"Tesco"			563
"supermarket"	"Tesco Extra"		186
"supermarket"	"Tesco Metro"		145
"convenience"	"Tesco"			45
"convenience"	"Tesco Metro"		17
"convenience"	"Tesco Extra"		11
"supermarket"	"Tesco Superstore"	10
"convenience"	"Tesco Petrol Station"	7
```

**Comment by ldw606** [comment]
The Tesco Express in Clane that I used as an example of one that should be considered a supermarket in #2530 has now been turned into a Tesco Metro. There may be others that are large enough to be considered a supermarket but that was the clearest example that I could find.
[Previously an Express supermarket](http://blog.myhome.ie/wp-content/uploads/2012/02/Tesco_Express_Clane.jpg)
[Now a Metro](https://www.openstreetmap.org/way/96767941) (I can't find any pictures of it as a Metro which is why I thought it was still an Express in my original post)
The fact that this store is in Ireland may be relevant as [according to Wikipedia](https://en.wikipedia.org/wiki/Sunday_shopping#Ireland) Sunday trading laws are more relaxed there.

**Comment by doublah** [comment]
I'd argue that Tesco Express is exclusively shop=convenience, and Tesco Metro is always somewhere in size between the big Tesco supermarkets and the smaller Tesco Express shops, so probably shop=supermarket is best. [[1]](https://www.reddit.com/r/unitedkingdom/comments/5ivhbk/whats_the_difference_between_a_tesco_express_and/) [[2]](https://en.wikipedia.org/wiki/Tesco#Tesco_Express)

Also, they have preferred using their Extra/Metro/Express labels compared to just Tesco over the last few years, I wonder how many are really still called just Tesco. (Also, 'Tesco Superstore' isn't actually used on store signage, it's just what the company website calls the stores branded just 'Tesco' AFAICT)

**Comment by bhousel** [comment]
Ok, I've removed the `shop/supermarket|Tesco Express` entry.. Sounds like we can take the position that Tesco Express is always a convenience store.
