### ISSUE TITLE
Research needed for: amenity/bank|Kreissparkasse Köln

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#275]
#### :thinking: We need help deciding what to do with "amenity/bank|Kreissparkasse Köln"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/bank|Kreissparkasse Köln` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/bank|Kreissparkasse Köln`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/bank|Kreissparkasse Köln`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by ENT8R** [comment]
This is only a regional brand (around the German city of Cologne) but it has its own Wikipedia entry: https://de.wikipedia.org/wiki/Kreissparkasse_K%C3%B6ln and then of course also a Wikidata entry: https://www.wikidata.org/wiki/Q1787788. But basically it is the same as https://github.com/osmlab/name-suggestion-index/issues/274... What should be done in this special case?

**Comment by bhousel** [comment]
If they have 2 separate wikidata, we can keep 2 separate entries 👍

**Comment by ENT8R** [comment]
But then, theoretically we also have to add all other "Kreissparkassen" listed in the table of this Wikipedia entry: https://de.wikipedia.org/wiki/Liste_der_Sparkassen_in_Deutschland#Bestehende_Sparkassen which is IMO a bad idea because if somebody wants to add a new "Kreissparkasse" using iD, every single instance is shown to the user... "Kreissparkasse" (without the city name) is sufficient and everybody does understand which bank is meant...

**Comment by bhousel** [comment]
> "Kreissparkasse" (without the city name) is sufficient and everybody does understand which bank is meant...

Ah gotcha - yes reading up on wikipedia now about the German public banking system.  
I agree we should probably just encourage mappers to use the single "amenity/bank|Kreissparkasse" entry (without the city name).

**Comment by bhousel** [comment]
Thanks for your input @ENT8R - it is really important to have someone with local knowledge helping us with this list 🙏 

Here is what I did in 9ee54a0:
I kept "Sparkasse" as the generic public bank, and tagged it to Q2513770 / "de:Verband der Freien Sparkassen" which explains the public banking system and includes the branding.  Since it has a `count: 4568` this is a very strong signal that it's how most Germans are currently mapping these. 

I also kept "Kreissparkasse", since I don't know whether that is really a different kind of a thing from "Sparkasse".  Please let me know if that should also get included in the "Sparkasse" match array...

```
  "amenity/bank|Sparkasse": {
    "count": 4568,
    "match": [
      "amenity/bank|Hamburger Sparkasse",
      "amenity/bank|Mittelbrandenburgische Sparkasse",
      "amenity/bank|Sparkasse Aachen",
      "amenity/bank|Sparkasse KölnBonn",
      "amenity/bank|Stadtsparkasse"
    ],
    "tags": {
      "amenity": "bank",
      "brand": "Sparkasse",
      "brand:wikidata": "Q2513770",
      "brand:wikipedia": "de:Verband der Freien Sparkassen",
      "name": "Sparkasse"
    }
  },

...

  "amenity/bank|Kreissparkasse": {
    "count": 594,
    "match": ["amenity/bank|Kreissparkasse Köln"],
    "tags": {
      "amenity": "bank",
      "brand": "Kreissparkasse",
      "brand:wikidata": "Q2513770",
      "brand:wikipedia": "de:Verband der Freien Sparkassen",
      "name": "Kreissparkasse"
    }
  },
```

**Comment by ENT8R** [comment]
> I kept "Sparkasse" as the generic public bank, and tagged it to Q2513770 / "de:Verband der Freien Sparkassen" which explains the public banking system and includes the branding.

Mmh... I think it is actually a little bit different:
- The current brand (de:Verband der Freien Sparkassen) is not correct. This brand only operates banks at 6 different locations (Bordesholm, Bremen, Lübeck, Hamburg, Mittelholstein, Westholstein) which are listed here: https://de.wikipedia.org/wiki/Verband_der_Freien_Sparkassen#Mitglieder
- The correct brand for `amenity/bank|Sparkasse` should be [`de:Sparkasse`](https://de.wikipedia.org/wiki/Sparkasse)
- The "Kreissparkasse" is only a subcategory of a "Sparkasse" and TBH I don't even know the exact difference. If somebody says that he's working at a "Sparkasse" it can also be a "Kreissparkasse" or even a "Stadtsparkasse" which is another subcategory 😄

I think we could remove the entry for the "Kreissparkasse", add `"match": ["amenity/bank|Kreissparkasse", "amenity/bank|Kreissparkasse Köln"],` to the entry of "Sparkasse" and correct the wikidata and wikipedia tags...

**Comment by Adamant36** [comment]
@ENT8R, hhhmmm, I'm wondering why you did this. Sparkassen isn't even a bank. Its a type of public banks that are independently ran. Whereas, Kreissparkasse Köln is an actual, individual, bank brand even if its a type Sparkassen. So consolidating its entry into Sparkassen is completely wrong. If anything Kreissparkasse Köln should have its own entry, like it already did, and Sparkassen should be added to the generic list. In general there are plenty of Kreissparkasse and Sparkasse banks. They are all different companies, the names Kreissparkasse or Sparkasse in them doesn't mean they should all be under the same listing. 

https://www.ksk-koeln.de/ (founded in 1853)
https://www.kreissparkasse-euskirchen.de (founded in 1855)
https://www.sparkasse-koelnbonn.de/ (founded in 2005)
https://www.ostsaechsische-sparkasse-dresden.de (founded in 1821)
https://www.sparkasse-lev.de (founded in 1844)
https://www.foerde-sparkasse.de (founded in 2007)
https://www.frankfurter-sparkasse.de (founded in 1816)

Etc. Etc. All clearly different companies.

**Comment by ENT8R** [comment]
Mmhh... All the Sparkassen you listed there can be considered as some kind of subcategory of the "Sparkasse". But they are not completely different/independent companies because they all belong to the "Sparkasse". They are just divided into their operating regions (e.g. "Sparkasse Köln" operates only in the region of Cologne) but this is one brand after all IMO.
So if you are e.g. living in the region of Cologne and you say you have to go to the "Sparkasse" everybody understands where you want to go. Saying "Kreissparkasse Köln" is just a little bit more specific but in the end this is all the same...
If you think I'm wrong, I would be happy to hear your opinion on that 👍

**Comment by Adamant36** [comment]
"Kreissparkasse Köln" is just a little bit more specific but in the end this is all the same." 

Its at least a little more specific then saying
 Sparkasse, and its an actual brand. Even if its just regional. So your chosen to go with a more generic none brand name over one that's an actual brand. Sparkasse is a type of bank. Its not a company. Therefore, if you think Kreissparkasse Köln should be axed because its to generic, so should it. There's no reason the regional brands can't have their own entries though. Since they are different brands and Sparkasse could be the operator or something. We do that with hotel chains and some other things already if I remember correctly. Although, it would be miss leading to make Sparkasse the operator. The question is how many banks does each chain/region have? 

Looking at taginfo a lot of them. for example Hamburger␣Sparkasse (155 uses),  Sparkasse␣KölnBonn (90 uses), Mittelbrandenburgische␣Sparkasse (89 uses), Sparkasse␣Ansbach (83 uses), Kreissparkasse␣Köln (79 uses), Kreissparkasse␣Ludwigsburg (40 uses etc. 

Those could all be different entries. My guess is that both the Sparkasse and Kreissparkasse tags usage is miss tagging because there isn't specific tag for those types of banks. I see that kind of miss-tagging all the time. If you consoludate everything under Sparkasse though your going to lose the brand variations and essentially encourage people to tag the banks with a type tag that's masquerading as a name tag.

**Comment by ENT8R** [comment]
Wait, why do you think Sparkasse is not a company? In other countries this might be different, but in Germany this is a company (see also https://de.wikipedia.org/wiki/Sparkassen-Finanzgruppe which is the actual company behind the German "Sparkasse")

> There's no reason the regional brands can't have their own entries though

I think that the amount of local branches is just too much to be added to this index. There are about 400 different branches of the "Sparkasse" throughout Germany (https://de.wikipedia.org/wiki/Liste_der_Sparkassen_in_Deutschland)

> My guess is that both the Sparkasse and Kreissparkasse tags usage is miss tagging because there isn't specific tag for those types of banks

I would not consider it as miss-tagging, it is just not that specific as it could be...

**Comment by Adamant36** [comment]
Sparkassen-Finanzgruppe is A Sparkassen company. Its not THE Sparkassen company though (or its the operator of the other companies). There's also just generic "Sparkassen" to though. See https://en.m.wikipedia.org/wiki/German_public_bank 

Sparkassen is probably miss-tagged in the same way "cooperative bank" or similar things are in South America. Ultimately its a category. Not a brand. 

"I think that the amount of local branches is just too much to be added to this index."

There's only like 10 main ones with any major usage. So that shouldn't be a problem. I'm not saying we should add individual entries for every single one, just ones that are clearly major brands, with their own websites, social media accounts, etc. If its some mom and pop local bank that happens to also be a Sparkassen bank, I don't really care, but if its something like Hamburger Sparkasse that has 155 uses it should 100% be its own entry. 

"I would not consider it as miss-tagging, it is just not that specific as it could be"

Its about not about how specific it is or not. Its the wrong tag. Sparkasse isn't a brand. Its a type of bank. Its like if we consolidated Mcdonald's and Burger King into a brand:fast_food entry or two restaurant brands that have "restaurant" in their name under brand:restaurant. Its both not specific enough and just wrong.

**Comment by ENT8R** [comment]
> There's only like 10 main ones with any major usage.

If we add all "Sparkassen" with a number of branches higher than 50, we would still have to add more than 40 different entries. I mean, this would probably not be the problem, but the problem would be that (in iD) the "Hamburger Sparkasse" is also shown to users who want to add a "Kreissparkasse Köln" if they are just searching for "Sparkasse".

So do you think that it is Okay to add entries for "Sparkassen" with more than 50 branches and the rest is simply tagged as a "Sparkasse" if users are searching for it?

**Comment by Adamant36** [comment]
but the problem would be that (in iD) the "Hamburger Sparkasse" is also shown to users who want to add a "Kreissparkasse Köln" if they are just searching for "Sparkasse".

Not if we add Sparkasse to the generic list. Since that's clearly what it is. Then people would have to use a more specific name. Which would encourage better tagging. Sounds like a win to me. 

 None of the are just called "Sparkasse" right? All of them have an added regional or whatever word in their names right? That's what it seemed like to me. 

"If we add all "Sparkassen" with a number of branches higher than 50, we would still have to add more than 40 different entries." 

I say we start with a higher threshold, but ultimately, there should be as many individual entries as there are unique companies.

**Comment by ENT8R** [comment]
Alright. I thought some more about the whole situation. If we have all different "Sparkassen" as separate entries then we really do not need the generic "Sparkassen" entry anymore because there should always the something which is more specific. With that argument in mind, my previous argumentation is kind of deprecated.
My only argument against this is that users of iD might be overwhelmed with the amount of choices if they only type in "Sparkasse".
But your argument that it improves the tagging situation is actually a very big argument and that's probably what made me think different 😄
In addition to that, if the data coverage is good enough, it allows data consumers to deliver more specific data.
So, sorry for the previous discussion, but you convinced me 😃 👍

> None of the are just called "Sparkasse" right? All of them have an added regional or whatever word in their names right?

Yes, you are right. Often it is just the name of the city the bank is located in.

> I say we start with a higher threshold, but ultimately, there should be as many individual entries as there are unique companies.

If it is okay to @bhousel then we should start to do that 👍

**Comment by ENT8R** [comment]
Wait, I just noticed that all entries at https://de.wikipedia.org/wiki/Liste_der_Sparkassen_in_Deutschland which lists all "Sparkassen" in Germany have their own Wikipedia entry and thus also a Wikidata item.
So we don't need to add every single entry by hand, but I could write a little script which converts the table to our format.
