### ISSUE TITLE
Broken logos from Facebook

### ISSUE THREAD

**Issue by SilentSpike** [osmlab/name-suggestion-index#2750]
It seems that sometimes facebook logos are broken, came across this while editing with iD.

Example:
https://osmlab.github.io/name-suggestion-index/brands/amenity/cafe.html#amenitycafepatisserie-valerie

There are actually two there, I believe the ones with a question mark image correspond to facebook pages where login is required to view. Not sure what the broken one I've linked is caused by.

**Comment by bhousel** [comment]
Yeah the question mark logo happens when there is any kind of restriction on the brand's Facebook page.   Because the endpoint to fetch the logo is open (you don't need to be a member of Facebook or be logged in to see the logo), Facebook doesn't know whether the person viewing the logo meets the restriction, [so they return a question mark icon instead](https://stackoverflow.com/questions/12793622/facebook-profile-picture-doesnt-show-up-it-shows-an-icon-of-a-question-mark).

Normally these are age or country based restrictions.  For example, pretty much all [alcohol shops](http://osmlab.github.io/name-suggestion-index/brands/shop/alcohol.html) have an age restriction, so we get question marks for their profile pictures.

On the iD side, I'm ignoring some kinds of businesses when we build the presets, but this isn't a perfect solution.  We could detect whether the logos return question marks, but it requires fetching each one and I don't want to abuse their api too badly.

https://github.com/openstreetmap/iD/blob/3f798b85cc723a5c5159721289f6fc755bb446d5/build_data.js#L265-L276

**Comment by matkoniecz** [comment]
> it requires fetching each one and I don't want to abuse their api too badly.

So it would be probably best as a separate `npm run facebook`?

>  when there is any kind of restriction on the brand's Facebook page

Is it depending on location of user attempting to fetch it?

**Comment by bhousel** [comment]
> So it would be probably best as a separate `npm run facebook`?

Yes, that's a good idea.. Or I can probably make it another thing that `npm run wikidata` does. 

> Is it depending on location of user attempting to fetch it?

It more depends on how the owner of the page set up their page.  I'm logged into Facebook now and can look at BevMo's page:

<img width="200" alt="Screenshot 2019-06-07 13 10 32" src="https://user-images.githubusercontent.com/38784/59121318-cbf2e800-8925-11e9-9569-99e47e52a73b.png">

But their CDN will still give me a question mark when I request the public profile picture this way:
https://graph.facebook.com/BevMo/picture?type=large

<img width="180" alt="Screenshot 2019-06-07 13 13 59" src="https://user-images.githubusercontent.com/38784/59121467-24c28080-8926-11e9-959c-62527e9007f3.png">

**Comment by SilentSpike** [comment]
I figured out the case I link to as an example with the totally broken logo is what happens when the facebook page no longer exists: https://www.facebook.com/ValerieCafe

**Comment by bhousel** [comment]
I did this today - `npm run wikidata` will check whether the Facebook logos are ok, and skip the ones that are unavailable.  

Also the docs pages now display "Profile restricted" if there is a Facebook account but no logo.

<img width="691" alt="Screenshot 2019-06-12 17 06 59" src="https://user-images.githubusercontent.com/38784/59386380-84f56000-8d34-11e9-8781-47585e2a337c.png">
