### ISSUE TITLE
Wikicheck - list entries that are not matching according to the Wikidata

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2770]
For example formerly linked https://www.wikidata.org/wiki/Q25209674 had

* coordinate location (P625), indicating that it is a single building
* without P31 (instance of) that would be directly or indirectly case of https://www.wikidata.org/wiki/Q507619 (retail chain)

I think that `wikicheck` script would benefit from both checking for blacklisted properties (P625 for start) and checking is what we consider brand is marked as brand on Wikidata (descendant of Q507619 or potentially also being marked as a brand in some other way)

@ENT8R Would you be potentially interested in expanding `wikicheck` again?

**Comment by ENT8R** [comment]
I did another update to the wikicheck script (https://github.com/osmlab/name-suggestion-index/commit/5b59e9ace0753fe64e5270e0baddec81b4da66ea) and now it is possible to
- find deleted Wikipedia articles and redirects
- detect if the Wikipedia article is actually linked to another Wikidata entity than the one which is in the index
- warn if a P625 (coordinate location) claim is present as this might either be a wrong entry or just a wrong claim which actually should be a qualifier for the headquarters office...
---
Regarding your second idea @matkoniecz: I tried to implement something like this (check whether instance claim (P31) has one value of [`Q167270` (trademark)](https://www.wikidata.org/wiki/Q167270), [`Q6881511` (enterprise)](https://www.wikidata.org/wiki/Q6881511), [`Q507619` (retail chain)](https://www.wikidata.org/wiki/Q507619) or [`Q4830453` (business)](https://www.wikidata.org/wiki/Q4830453)) but this turned out to be not so good, as there are hundreds of other values which also describe the item as a brand and I thought it would not be worth it to include them all in a list (i.e. [`Q18534542` (restaurant chain)](https://www.wikidata.org/wiki/Q18534542) or [`Q1631129` (hotel chain)](https://www.wikidata.org/wiki/Q1631129)).

**Comment by bhousel** [comment]
closing as stale, I dont think anyone has run the wiki  check script in a while and not sure whether it still works 🤔
