### ISSUE TITLE
MUFG Union Bank (USA) Name Matching

### ISSUE THREAD

**Issue by mds08011** [osmlab/name-suggestion-index#2781]
I have noticed that the iD validator is not suggesting Wikidata tags for MUFG Union Bank nodes tagged with `name=Union Bank` (Example: https://www.openstreetmap.org/node/5747834819).  I was going to submit a Pull Request adding `matchNames": ["union bank"]` but I am nervous that this will conflict with the many other "X Union Bank" and "Union Bank of X" entries because the name is somewhat generic.  Are there any easy ways to address this?

https://github.com/osmlab/name-suggestion-index/blob/12198fad81f447fba11a683a558fd8a5a2e0d949/brands/amenity/bank.json#L4914-L4930

**Comment by 1ec5** [comment]
iD avoids upgrading any “Union Bank” because there are multiple entries by that name, each with a disambiguating suffix. Ideally, iD would issue a less urgent suggestion to choose from among a palette of Union Bank presets or ignore the warning. In the future, perhaps we can also minimize the need for disambiguation by tracking which states each brand operates in. That would be relevant to banks that operate under state charters.

**Comment by bhousel** [comment]
> iD avoids upgrading any “Union Bank” because there are multiple entries by that name, each with a disambiguating suffix. Ideally, iD would issue a less urgent “Did you mean?”-type suggestion to choose from among a palette of Union Bank presets or ignore the warning.

☝️ Yes, this is why it's not offered for upgrade.  I agree that someday it would be nice to offer iD users a choice of fixes for upgrading ambiguous names.

I'm going to close here as it's really an iD issue, but it's a good idea!  (We only recently added the code to iD to make this even a possibility).

**Comment by mds08011** [comment]
Makes sense.  Thanks!
