### ISSUE TITLE
dev/test UI

### ISSUE THREAD

**Issue by jnicho02** [osmlab/name-suggestion-index#2802]
My first edit feels very much like flying blind. Sure, I can run the build to check for consistency but it doesn't fill me with confidence that the change I just made will result in a sensible result in Vespucci or iD say. 

Is it possible to provide a mini UI where I can set the countrycode, start typing into a box and see what the presets show for me?

....or do I have to check out the whole iD project and integrate it locally?

**Comment by matkoniecz** [comment]
Sounds like #2733

**Comment by Adamant36** [comment]
That would only show that it would work in the docs, after merging it. Which, there's no reason it wouldn't work there or even in iD Editor if the PR is reviewed properly before it's merged. The wait time until it shows up in the next iD Editor release can be a little long though, but I think that just takes a little patient and faith. 

Generally, it's pretty hard to get anything merged that won't work latter. Since we are pretty good about reviewing things. Plus, npm run build has a bunch of error checks built into it also. Although, something can sneak by us sometimes, but it usually gets fixed pretty quickly if it does.

**Comment by SilentSpike** [comment]
Good to keep in mind that this project is separate from those editors too. If the data fits to specification in this project then that's all we're looking for. The closest you'll likely get are the [generated docs](https://osmlab.github.io/name-suggestion-index/brands/).

**Comment by bhousel** [comment]
Yes this is a good idea.. I recently improved the docs app to make it possible to do client side country code filtering.. It will end up here:  https://osmlab.github.io/name-suggestion-index/index.html 

This is #2733 , so I'll close here.
