### ISSUE TITLE
Handling of Combined Brands

### ISSUE THREAD

**Issue by mparrault** [osmlab/name-suggestion-index#2847]
There are a lot of cases where two brands (usually commonly owned) combine in one store.  Examples I am familiar with include KFC/Taco Bell, Wendy's/Tim Hortons, Carter's / OshKosh.  I would estimate there at least 50 of each of these combos.  Sometimes the two brands have separate cash registers, but they often don't.  Should we create new entries for the combined brands?  Should the two brands be separated into two nodes?

I think it should depend on the case, but some combined brands should have entries.  For example, Wendy's/Tim Hortons should be split into separate nodes (since they have separate cashes), and Carter's / OshKosh should have a new entry.  KFC/Taco Bell could have a new entry (because the two brands share a cash), but splitting might make more sense.

**Comment by 1ec5** [comment]
Another reason to combine some locations is that one always comes first and the other second in signage, menu layout, and how the store is referred to. You’d want that order to be preserved even if you rotate the map.

Adding entries for the more common combination seems reasonable. Alternatively, mappers can already add two points in iD and combine them, which turns the name and brand tags into semicolon-delimited lists. Admittedly this workaround isn’t particularly discoverable.

**Comment by 1ec5** [comment]
Car dealerships are often affiliated with multiple brands as well. I don’t think it would be very practical to include all possible combinations of car brands, but we could include some common combinations like Chrysler/Jeep/Dodge, BMW/Mini, Jaguar/Land Rover, etc.

**Comment by bhousel** [comment]
This is a really hard problem...

The index already does [filter out "KFC/Taco Bell"](https://github.com/osmlab/name-suggestion-index/blob/67d845e7ee67731cf8690edf2d350c6edf67a8a8/config/filters.json#L46), which is the most common instance in OSM currently.

I'm a big proponent of doing the simplest thing possible, which in this case is _just map 2 pins_ - one for KFC and one for Taco Bell.  A great thing about OSM is that we can map the world in as much detail as the contributors want to.  However it becomes a real problem for software (like name suggestion index) when people use creative tagging that breaks the one-feature-one-element rule.  I really don't want to maintain an index (or an editor for that matter) that needs to deal with semicolon-delimited names/brands/cuisines/ and everything else.

I took a look at what other maps do <sup>†</sup>, and none of them seem to handle the "combined brand" case at all.

### Google:
<img width="800" alt="Screenshot 2019-07-05 08 43 16" src="https://user-images.githubusercontent.com/38784/60724302-0a1eff80-9f04-11e9-9395-4547618db44f.png">


### Apple:
<img width="487" alt="Screenshot 2019-07-05 08 45 25" src="https://user-images.githubusercontent.com/38784/60724323-15722b00-9f04-11e9-9cf6-b566ffaa9730.png">

### OSM:
<img width="558" alt="Screenshot 2019-07-05 09 03 01" src="https://user-images.githubusercontent.com/38784/60724339-1c993900-9f04-11e9-9dac-e58364c7fe35.png">


<sup>†</sup> We don't really know what the other maps do - it's possible they have multiple points at the same place and because of max zoom and label collision we can only see one of them.

**Comment by 1ec5** [comment]
That KFC/Taco Bell is an example of a newer store where there’s no boundary between the two restaurants inside but there is a distinct boundary outside in terms of the façade. On the other hand, there are plenty of older or smaller locations where there’s no clear distinction and the secondary brand may be just an extra logo on signage.

Apart from Yum Brands, what of multiple car brands at a dealership? This is the more common case of combined brands. Most maps rightly handle them as a single point feature, but it would be nice if mappers could more easily discover that they should combine multiple points instead of starting out with a single point and trying to come up with brand tags themselves.

**Comment by mparrault** [comment]
I personally map KFC/Taco Bell combos as two separate nodes - it makes them easier to find later that way.

For car dealerships, I generally have one node, with the brand data being for the dominant brand.  For instance, I would map a Chevrolet Buick GMC dealership with name="... Chevrolet Buick GMC" and brand=Chevrolet.  I'm not sure how the index could facilitate this.

**Comment by 1ec5** [comment]
> I personally map KFC/Taco Bell combos as two separate nodes - it makes them easier to find later that way.

Regardless of what’s at issue here, I think geocoders should ideally support finding POIs by name in semicolon-delimited list, just as some renderers support choosing POI icons from semicolon-delimited values in `amenity`, `shop`, etc.

> For car dealerships, I generally have one node, with the brand data being for the dominant brand. For instance, I would map a Chevrolet Buick GMC dealership with name="... Chevrolet Buick GMC" and brand=Chevrolet. I'm not sure how the index could facilitate this.

Each colocated Yum Brand restaurant has a dominant brand too – it’s the brand to the left on signage and the first brand in the name of the overall store (even if you rotate the map). If you order a Long John Silver’s meal from a KFC/Long John Silver’s, everything but the main entrée is wrapped in KFC branding. So I guess one could similarly map the location as a standard KFC with “Long John Silver’s” in the name. But that makes it more difficult to search for the Long John Silver’s, just as it’s harder to find Buick dealerships if you only indicate them in the `name` tag.

To better illustrate the point, combination Chevrolet/Jeep/Dodge dealerships are so common – in that order – that many dealership names are suffixed with “[CJD](https://www.championcjdindiana.com/)”. But standalone Jeep dealerships are also common. While one could map each marque as a separate POI, that throws off any analysis that one might do of OSM coverage, because it’s really just one business, even if a given customer might only interact with one of the marques.
