### ISSUE TITLE
Add Blink Fitness

### ISSUE THREAD

**Issue by yoasif** [osmlab/name-suggestion-index#2852]
https://www.blinkfitness.com/

**Comment by yoasif** [comment]
Added wikdata Q65621568

**Comment by Adamant36** [comment]
@yoasif, thank's for creating the Wikidata entry. Just a general comment, but you should really add more information to it like links to social media accounts and add something with a reference. Otherwise, it's not used by iD Editor and the Wikidata admins will probably delete it due to notability issues. There's an example of a usable citation in the contributing file. Although, others will work also.

**Comment by ENT8R** [comment]
I added some more details and references to the [Wikidata entry](https://www.wikidata.org/wiki/Q65621568) and also added it to the index now
