### ISSUE TITLE
New entry for LinkNYC WiFi hot spots

### ISSUE THREAD

**Issue by yoasif** [osmlab/name-suggestion-index#2884]
See https://en.wikipedia.org/wiki/LinkNYC

https://www.link.nyc/

Wifi name "LinkNYC Free Public Wi-Fi"

**Comment by 1ec5** [comment]
These kiosks, which are also present in other cities, cram so many amenities into [a single piece of street furniture](https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element) that some unusual tagging combinations seem to be required: 
`tourism=information` `information=terminal` `internet_access=wlan` `height=9'6"` `amenity=telephone;device_charging_station`.

Also, like ATMs, I wonder if information kiosks should be tagged with `network` as well.

**Comment by bhousel** [comment]
I guess we could support adding these as `internet_access=wlan`, but not all the other toplevel tags.

**Comment by 1ec5** [comment]
I think it should at least have `tourism=information` `information=terminal` so it can have a primary feature tag. These are primarily kiosks with community information, not just wireless routers placed on light poles. But they also secondarily function as telephones, replacing the pay phone system. If I’d omit anything, it’d be `amenity=device_charging_station`, since public telephones are more commonly mapped. On the other hand, phone charging is going to become more useful over time as the calling capabilities become less useful.

**Comment by yoasif** [comment]
I don't see these as information screens -- they show advertisements more than community information: https://en.wikipedia.org/wiki/LinkNYC#Advertising_screens

They are primarily wifi hotspots with the additional benefits of a phone (honestly did not realize this made calls even though I have passed these on the street a number of times) and charging station.

**Comment by 1ec5** [comment]
It figures that it would be more about advertising than helpful information. 😛 I think it still does need something beyond `internet_access`, because regardless of what people use it for, it is a piece of street furniture. After all, if it were a lightpole-mounted router, we’d likely be adding some tags to a lightpole preset.

**Comment by yoasif** [comment]
information=terminal seems to make sense.

**Comment by TheAdventurer64** [comment]
The Wi-Fi Hotspot preset on iD uses `internet_access=wlan` as the base tag.

**Comment by peternewman** [comment]
Do you think these are the same as the BT Street Hubs in the UK (the page lists their capabilities):
https://business.bt.com/public-sector/street-hubs/

I've mapped one as an advertising totem, like @1ec5 said, WiFi doesn't really feel like their primary purpose, I was certainly only torn between telephony and advertising.

**Comment by yoasif** [comment]
@peternewman they seem pretty similar, except with the addition of 4/5G.
