### ISSUE TITLE
Add Spectrum stores

### ISSUE THREAD

**Issue by yoasif** [osmlab/name-suggestion-index#2900]
See https://www.spectrum.com/locations/index.html

**Comment by mds08011** [comment]
@yoasif thank you for adding these!

As you find more brands to include in the index, it is very helpful if you can also include whether or not it has an existing Wikidata ID.  In this case, Spectrum does: [Q7805197](https://www.wikidata.org/wiki/Q7805197).

As a quick check, if the brand has a Wikipedia page the Wikidata ID will often be linked on the left side under “Tools”:

<img src="https://user-images.githubusercontent.com/8010709/61414441-c4b6e680-a8a2-11e9-808e-f8fdc7365aba.png" width="70%">

**Comment by Adamant36** [comment]
I know if adding the existing Wikipedia/wikidata pages would be good in this instance because its less about the stores themselves and more about the services the company provides. We should probably create unique Wikidata entry just for the stores instead. Which would also work better for the stuff on Wikidata's side to like "Instance of." Although, I don't know how it would work with social media accounts or website links. Since they would have to be unique.

**Comment by mds08011** [comment]
You have a good point overall but I don't see what sets Spectrum apart from any other entries.  For the majority of other restaurants and shops in the index, the corporation's Wikidata page is linked rather than one specific to the physical stores.  Ultimately, we are tagging `brand:wikidata=` and the Spectrum wiki pages seem to adequately to convey the brand.

**Comment by mds08011** [comment]
I'm also not sure how to tag these stores.  `shop=electronics` seems to be the most applicable official tag.  Someone on the OSM-US Slack also suggested `shop=internet` which is not official but has [moderate use](https://taginfo.openstreetmap.org/tags/shop=internet)

**Comment by bhousel** [comment]
I'd use either `office=telecommunication` or `shop=mobile_phone` based on similar brands in the index already..

**Comment by mds08011** [comment]
`office=telecommunication` seems more applicable as these locations sell a lot more than just mobile phones.  That does seem consistent with other index brands.

**Comment by tas50** [comment]
I tag these as `shop=telecommunication`. It's clearly not 100% right, but it feels like the least wrong. There really needs to be a `shop=telecommunication` as well to cover the retail comcast, spectrum, centurylink type offices vs. their CO type locations.
