### ISSUE TITLE
amenity/car_sharing should have an operator tag

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#2928]
It was pointed out to me when updating nodes for Zipcar that car_sharing nodes should have an operator tag per the wiki. We should probably add this to all of them matching the brand tag. https://wiki.openstreetmap.org/wiki/Tag:amenity=car%20sharing?uselang=en

**Comment by bhousel** [comment]
Yeah ......
in cf21ce5  I removed all the `operator` tags and I think it was probably a bit too heavy-handed.  There are entries in this index where `operator` tags really are appropriate  (also for post offices and post boxes).

I think I need to relax the schema rule prohibiting the `operator` tags, and maybe we just pay more attention to the index so that they don't sneak in except for certain key/value types.

**Comment by DavidMoraisFerreira** [comment]
+1 for an operator tag in [amenity=charging_stations](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station#Examples) :)

**Comment by bhousel** [comment]
Thanks for your patience everyone - I've moved `amenity/car_sharing` and `amenity/charging_station` to the 'operators' tree.
