### ISSUE TITLE
U-Haul Q7862902 has incorrect amenity. Should be truck_rental instead of car_rental

### ISSUE THREAD

**Issue by spjoruss** [osmlab/name-suggestion-index#2968]
see title

**Comment by bhousel** [comment]
can you please fix up the issue description?

(btw @carstenhag this is why I don't like Issue Templates)

**Comment by carstenhag** [comment]
Well, it helps, but it's not perfect.

**Comment by tas50** [comment]
Is truck_rental a supported amenity. I know this came up previously and we came to the conclusion that car_rental was the closest thing you could use.

**Comment by spjoruss** [comment]
I am new to all of this. I searched all over and could not find how when a brand is created how they connect the amenity to it. car_rental is not a very good amenity for U-Haul. It is only rents trucks and moving equipment.

**Comment by tas50** [comment]
We can only tag things in this repo using the approved tags listed in the wiki. Here's the amenity tag wiki page that links off to all the approved amenity tags:

https://wiki.openstreetmap.org/wiki/Key:amenity

Personally I think more rental tags are necessary because car_rental doesn't cover it all, just like you stated. car_rental should really be vehicle_rental and there probably also needs to be a equipment_rental for things like United Rentals that rent out large construction equipment. The proposal of those new tags happens in the main OSM project though and not in this repo.

**Comment by 1ec5** [comment]
I dug around, and besides the approved `boat_rental` and `bicycle_rental` tags, apparently there’s a documented [`shop=rental`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Drental) tag that isn’t approved but has been in use for a while. I’m not sure how I feel about a tag that’s so broad that it could cover both tennis racquet rentals and houseboat rentals though…

**Comment by spjoruss** [comment]
Okay, thanks for the help. I'll look for the area in OSM project to propose it.

**Comment by Adamant36** [comment]
U-Haul rents stuff besides trucks. They also rent trailers, dollies, furniture pads, and other things related to moving. So I think in this case shop=rental might actually work. Then people could just check Wikipedia for more details if need be. Otherwise, something like shop=rental with a rental=moving_equipment sub-tag or shop=moving_equipment_rental? (probably not). They also sell general items related to moving in their dedicated stores. So maybe a none rental related shop tag would be better?

**Comment by bhousel** [comment]
> apparently there’s a documented [`shop=rental`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Drental) tag

I agree with @1ec5 and @Adamant36.
Lets use that.. It seems fine for a place that doesn't exactly match an established tag.

**Comment by spjoruss** [comment]
The main thing that caused me to notice the car_rental tag was that the icon on the node was an image of a car and a key. I see now that it has an image of what looks like a shopping basket. That seems better than having an image of a  car and key. 

Thanks.
