### ISSUE TITLE
Opap preset

### ISSUE THREAD

**Issue by beatnickgr** [osmlab/name-suggestion-index#2992]
https://github.com/osmlab/name-suggestion-index/blob/master/brands/shop/bookmaker.json
For OPAP, the greek community has decided the following tags:
      "brand:wikidata": "Q2007823",
      "brand:wikipedia": "el:ΟΠΑΠ",
      "name": "ΟΠΑΠ",
      "shop": "bookmaker"
      "website": "https://opap.gr",

**Comment by bhousel** [comment]
Thanks @beatnickgr  - I see that we already have this entry in `bookmaker.json`, but in 133b834 I've updated the `brand:wikipedia` tag to use the Greek page.

**Comment by beatnickgr** [comment]
It's not just the brand.
You can remove the brand:el and name:el which are just duplicates of the brand and name.
EN is not an official language in GR, we use int_name when necessary.
you can also add the website.
It has been consulted with the greek community in our dedicated matrix channel to only keep those 5 tags.

**Comment by bhousel** [comment]
> It's not just the brand.
> You can remove the brand:el and name:el which are just duplicates of the brand and name.

ok.. I'll remove them.

Also, we don't really set the `website` tag for any of the entries in this index because many mappers want that to be the website _for the particular location_ not the website _for the brand_.

**Comment by Adamant36** [comment]
@beatnickgr, it's still helpful to have the English name if official or not. There are places where the company uses English in it's branding though. As seen below. A lot of entries for none English brands have name:en. Even when it's not the official language of where the brand is being mapped. So that shouldn't be the deciding factor in my opinion. It should be if the company uses English in their branding or not. Along with a few other factors. What exactly is the problem with keeping it on there?  Personally, I don't think using int_name for the English name is appropriate because it's not an international language and the Wiki says its better not to use it that way. 

![image_gallery](https://user-images.githubusercontent.com/30259065/64137341-71461c80-cdac-11e9-9639-1ffa8158264b.png)
