### ISSUE TITLE
Supermarkets in Iceland

### ISSUE THREAD

**Issue by Stalfur** [osmlab/name-suggestion-index#3000]
Netto was branded with the foreign chain, www.netto.is for context.

Supermarket Iceland in Iceland (yes they recently opened) is a subsidiary of the British chain but should be its own entity.

**Comment by 1ec5** [comment]
> Netto was branded with the foreign chain, www.netto.is for context.

Fixed in #3001 by adding a Nettó entry and limiting the existing Netto entry to specific countries.

> Supermarket Iceland in Iceland (yes they recently opened) is a subsidiary of the British chain but should be its own entity.

Are you referring to [this Iceland chain](https://en.wikipedia.org/wiki/Iceland_%28supermarket%29) opening locations in Iceland? The index tracks brands, but not all brands are subsidiaries and not all subsidiaries have their own brands. Does Iceland’s Iceland subsidiary use unique branding or anything that would require tags that differ from the existing Iceland entry?

https://github.com/osmlab/name-suggestion-index/blob/8902efdb752d703c70ed8f0b7775be41cd29697f/brands/shop/frozen_food.json#L17-L26

**Comment by mds08011** [comment]
The Iceland chain in Iceland uses a different website from the UK locations and has a different owner but it's not immediately clear whether the branding is unique: https://icelandbudir.is/
