### ISSUE TITLE
Matching with conflicting tags on one object

### ISSUE THREAD

**Issue by tohaklim** [osmlab/name-suggestion-index#3079]
I assume this is only relevant for fuel stations, where one possible tagging variant for a station with a shop on premises is amenity=fuel and shop=* on the same node/area.
NSI rule in iD currently suggests this as non-standard tags (since it only expects amenity=fuel).
Should this case of simplified mapping be supported by NSI, or should I open an iD issue instead to suggest the validation rule wording to prompt for a separate shop node?

**Comment by bhousel** [comment]
> I assume this is only relevant for fuel stations, where one possible tagging variant for a station with a shop on premises is amenity=fuel and shop=* on the same node/area.

Oh yeah there are a few types of POIs now that are being tagged this way.. @1ec5 and I were talking about it in another thread.

> Should this case of simplified mapping be supported by NSI, or should I open an iD issue instead to suggest the validation rule wording to prompt for a separate shop node?

I'm not sure. I'd prefer for people to map the fuel and shop as separate nodes, and I think it's a bit lazy to combine them into a single point, but not necessarily wrong.  I do think that it introduces more work for consumers of OSM data when features have multiple primary tags.  (e.g. how do you even render a map marker for this thing?)

I think iD is a better place to open an issue for discussion, since it's a specific validation warning that might need adjustment.
