### ISSUE TITLE
Frequency of change propagation to iD

### ISSUE THREAD

**Issue by tohaklim** [osmlab/name-suggestion-index#3147]
Having fixed (presumably) newsagent's Белсоюзпечать [NSI entry](https://github.com/osmlab/name-suggestion-index/blob/master/brands/shop/newsagent.json) and wikidata, I am still seeing it being matched to the defunct Soviet and now Russian brand and wikidata entry, despite country codes and the rest of the tags being modified. Am I missing something?

**Comment by Adamant36** [comment]
I think its updated on iD's end about once a month around this time when we release a new version. According to [here](https://github.com/osmlab/name-suggestion-index/releases) its been since Aug 26 since the last update. So we are probably due for one. I don't want to speak for him, but my guess is that @bhousel is waiting until Hacktoberfest is over to do a new release since we are still getting some of contributions from that.

**Comment by bhousel** [comment]
Oh yeah, we don't really have a schedule.  It's updated in iD whenever we release iD, which is roughly once a month. @quincylvania and I have been close to releasing a new version for a few weeks now.  We are definitely due for another one.
