### ISSUE TITLE
Add Greyhound bus stations / stops

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#3164]
Another super common private bus stop / station that should get into the index.

**Comment by 1ec5** [comment]
Part of #2864.

**Comment by tas50** [comment]
@1ec5 I thought a good start would be tackling the commercial transit side of things since those are standard brands. These 2 are easy additions.

**Comment by 1ec5** [comment]
In that case, we could reopen and merge #2863. It’s a fine place to start, though as I expressed in https://github.com/osmlab/name-suggestion-index/pull/2863#discussion_r301672863, I do hope we can find a way to add `network` tags to the picture, given that `network` is more practical and relevant than `brand` for this kind of infrastructure.

**Comment by bhousel** [comment]
Ah yeah, this is a thing I've kind of been putting off, sorry..

My rough thinking on this is... if you go to https://nsi.guide, you see this:

<img width="599" alt="Screenshot 2019-10-28 11 42 07" src="https://user-images.githubusercontent.com/38784/67693401-ff3b1f80-f977-11e9-8a96-9d3e044a5414.png">

That's because we are treating the `brand:wikidata` almost as a "[natural key](https://en.wikipedia.org/wiki/Natural_key)" (sort of, but not really, as they aren't unique). 
 `brand:wikidata` tag is that important link between OSM and wikidata.

For some other types of features that will be `operator:wikidata` or `network:wikidata` or something else maybe.

So we need some way of handling alternate trees for entries to live under.  Right now everything is under `brands/` and we need to grow beyond that.  It changes a lot of stuff about how the project is organized (including code), but will let us do a lot more too.

**Comment by bhousel** [comment]
This was done!  There's a `transit` tree now and Greyhound Lines is in it: 
https://nsi.guide/index.html?t=transit&k=route&v=bus&tt=grey#greyhoundlines-1d67e7
