### ISSUE TITLE
Add multiple Sparkasse Brands

### ISSUE THREAD

**Issue by ferdinand0101** [osmlab/name-suggestion-index#3327]
There are Curremtly two allready in the project. the one being from Hamburg and the other one being from brandenburg
I'd like to add the ~400 other (those with 10 more shops)

my question would be if this is allowed

**Comment by Adamant36** [comment]
This was explored in #2475 and unfortunately got shot down by the German community due to the discussion [here](https://forum.openstreetmap.org/viewtopic.php?id=65695). Personally, I'd like to see them added. As its better to have some kind of unified tagging then not, but as the saying goes "The will of the people something something..Etc etc." So, it's a no go without the German communities buy in at this point 😞
