### ISSUE TITLE
Nextbike: should be replaced by sub-brands

### ISSUE THREAD

**Issue by sb12** [osmlab/name-suggestion-index#3378]
At least for Germany, nextbike has a lot of sub-brands e.g. KVV.nextbike, VRNnextbike, metropolradruhr, I don't know any city in Germany where only `nextbike` is used as the brand. It is very important to differ between this brands as there can be differences in pricing especially regarding annual rates. Because of the increasing power of this index and the iD editor many of these subbrands have disappeared from the database.
`name=nextbike` also does not make any sense as the brand name is used on the rental stations, sometimes combined with the name of the specific location.
Therefore please remove nextbike from this index for Germany and add the subbrands instead if needed.

**Comment by Adamant36** [comment]
" I don't know any city in Germany where only nextbike is used as the brand. Therefore please remove nextbike from this index for Germany and add the subbrands instead if needed."

Doing a basic Google search comes up with a bunch of results. In particular there's [this](https://www.nextbike.de/en/giessen/) interesting one where the company itself seems to use OpenStreetMaps as a way for people to find NextBike locations. There's also images on that page things bikes etc labeled just as "NextBike" and the page is specific to Germany. So, they must use it alone as branding there. 

Anyway, removing NextBike from the database in Germany might impact if they use us a map source or not. Since a lot of those places would be re-tagged and they clearly think the objects currently being tagged that way are correct as is or they wouldn't be showing them as part of just the NextBike brand if their wasn't such a thing. 

Also, there's a bunch of other website sites and images out there  with bikes and stations in Germany just showing NextBike as the branding, including a few buildings. Maybe adding the Sub brands would be OK, but it clearly shouldn't come at the cost of removing the main brand from the index. 

[NextBike sign in Berlin](https://www.gettyimages.com/detail/news-photo/rent-by-app-nextbike-is-written-on-a-street-sign-in-berlin-news-photo/1039485728) (I couldn't just upload it)

NextBike branding from images in random articles about Nextbike in Germany. Including from their own website. 

![NextBike 1](https://user-images.githubusercontent.com/30259065/68902607-a4caee80-06ed-11ea-8a14-f9bd0669a007.jpg)

![Nextbike 2](https://user-images.githubusercontent.com/30259065/68902615-a98fa280-06ed-11ea-93f5-a572a10cf361.jpg)

![nextbike_1](https://user-images.githubusercontent.com/30259065/68902732-f2475b80-06ed-11ea-8afa-015dc2b1b34a.jpg)

**Comment by bhousel** [comment]
> Therefore please remove nextbike from this index for Germany and add the subbrands instead if needed.

Ok, I removed it in 295de1633.. If somebody wants to add the subbrands, I'd be happy to accept a PR for it.

**Comment by hikemaniac** [comment]
@bhousel As @Adamant36 pointed out, Nextbike is still often used as the brand name on bicycle rental stations. I can confirm that many rental stations in Austria bear the logo "nextbike" without any subbrands. It might be useful to add the subbrands, but I think Nextbike should still remain in the index.

**Comment by bhousel** [comment]
@hikemaniac can you and @sb12 talk through it?

When someone asks us to remove something, my instinct is really to just remove it, no questions asked.  I think this index is extremely helpful to encourage good mapping, but people can certainly contribute stuff to OSM without it being in here.

**Comment by sb12** [comment]
Thanks to @Adamant36 for the analysis. I was not aware that there are actually nextbike stations in Germany (and Austria) just branded as "nextbike". Sorry for not looking deeper into it.
I tried to add all the sub-brands in Germany and Austria I found in #3381, so that it should be clearer for mappers when to use the "nextbike" brand and when to use the local brand.

Nextbike has used an OSM map on their locations site for some time, but I don't think they actually store their locations in OSM (some locations are definitely missing in OSM or the location in OSM is better than the position on their map :smile: ). They also show all nextbike stations in the location map of subbrands (e.g. https://www.kvv-nextbike.de/en/locations/). 

As far as I understand all the systems are operated by nextbike, but some of them are subsidised/sponsored by local towns, transportation authorities or companies which want use their own branding and sometimes adjust the pricing.
