### ISSUE TITLE
Tesco Fuel

### ISSUE THREAD

**Issue by maxerickson** [osmlab/name-suggestion-index#3385]
Tesco Fuel, at least in the UK, should point at https://en.wikipedia.org/wiki/Tesco which is the company that operates the retail locations.

**Comment by SK53** [comment]
I'd make this at least Europe wide, Tesco operate in Poland (although I don't know if they have fuel outlets). I presume in Thailand they are named & branded as Tesco Lotus, so this would not need to apply.

I also note that [Wikipedia](https://en.wikipedia.org/wiki/Tesco_Corporation) says that Tesco Corporation are defunct. In addition they were a b2b oil-field service provider. 

Error noted because of edit on this way : https://www.openstreetmap.org/way/305036454

**Comment by maxerickson** [comment]
The current entry isn't country limited. I was remarking about my research not being thorough there.
