### ISSUE TITLE
Midcounties Co-operative (And potentially other co-op brands)

### ISSUE THREAD

**Issue by doublah** [osmlab/name-suggestion-index#3390]
https://en.wikipedia.org/wiki/Midcounties_Co-operative
Associated with co-operative group and uses co-op group branding, we could add presets like so:
```
      "brand": "The Co-operative Food",
      "brand:wikidata": "Q3277439",
      "brand:wikipedia": "en:Co-op Food",
      "name": "The Co-operative Food",
      "operator": "Midcounties Co-operative",
      "operator:type": "cooperative",
      "operator:wikidata": "Q6841138",
      "operator:wikipedia": "en:Midcounties Co-operative",
      "shop": "convenience"
```
Operates it's own Co-operative Food (supermarket and convenience), Co-operative Funeralcare, Co-operative Childcare (not part of co-op group and recently rebranded [Little Pioneers](https://www.littlepioneers.coop/)),  Co-operative Pharmacy (seperate to the now rebranded co-op pharmacy now known as [Well Pharmacy](https://en.wikipedia.org/wiki/Well_Pharmacy)) and Co-operative Travel.

Looking for feedback before any action is taken, as this can be repeated for other similar co-operatives and brands.

**Comment by Adamant36** [comment]
I had screwed around with adding these a while back, but couldn't really decide how they should be added. As far as your attempt, I think the operator tags are incorrect. Like the Wikipedia page says "The "Co-op" brand is used by over 3,500 shops owned by the various societies which make up the co-operative movement, including the Central _England Co-operative_ and the _Midcounties Co-operative_." So there isn't one operator. Whatever that means in this context (because who really knows). My best suggestion would be to leave out the operator, create separate Wikidata entries for all the different "brands" or whatever you call them, and just go with that.

**Comment by doublah** [comment]
The thing is the different co-operatives are just different operators (with usually the same branding and products) running under the same brand, so using the brand and operator tags like this isn't wrong and tagging like this would also fix any wrong operator tags like `operator=co-op` or similar. 
Don't know how we'd distinguish it from the operator-less brand entry though, might have to prioritize the operator: tags over the brand tags.

**Comment by trigpoint** [comment]
The differences between co-ops are import in areas where they overlap.

Different membership schemes meaning different loyalty cards and other benefits. For example Mid-Counties give 10% off to members over 60 on a Tuesday.

**Comment by bhousel** [comment]
done in #5150
