### ISSUE TITLE
Adding mobile_phone shop name

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#34]
To begin with, I'm looking to add another of the most popular mobile phone shops in the UK to the presets. Currently O2, Vodafone and Carphone Warehouse are available in iD - I'd like to add EE to the list. 

Can someone please explain which files to edit to make this happen? Thanks

Eventually I want to "3/3 Store/Three/Three Store" to the list, but need to work out which is the correct name for the shop!

**Comment by math1985** [comment]
Sorry for the late reply.

The list of available presets is semi-automatically generated (with some modifications) based on frequently used shop names. We include shops that occur at least 50 times, which criterion is met by EE, but not by Three (presumably due to the many different spellings).

EE now also shows up in iD.

So the best thing to do for now would be to try to add more Three shops, and/or work on standardising the spelling. Note that the spelling differences exist in real life, some shops have a '3' sign above their window while others have a 'Three' sign.

I'm closing this as nothing remains to be done on our side, but feel free to let us know if yo uhave further questions.

**Comment by boothym** [comment]
Thanks, I figured it was automatically generated once EE appeared in the latest iD release. And yeah I noticed the discrepancy with the 3 Store/Three name, as well as many other inconsistencies with shop names/tags in the UK - really needs a good cleanup at some point.
