### ISSUE TITLE
Use French Wikipedia for French brands

### ISSUE THREAD

**Issue by bikepunk** [osmlab/name-suggestion-index#3409]
The request is to switch brand:wikipedia tag from "en:article" to "fr:article" since these are French companies operating mainly in france

-Leader Price
-Groupe Caisse d'Épargne
-Renault
-Géant Casino
-Brico Dépôt

**Comment by Adamant36** [comment]
Hi there. There isn't really a specific policy or anything that dictates what languages the Wikipedia articles in. Most of them were just picked randomly at the time they were added. At this point it's mostly about having people submit PRs for them to be changed. So, feel free to do a PR for these if you want. If the decision to change them was made by others besides you, maybe you could encourage them to contribute PR's also. It would be really helpful.

**Comment by doktorpixel14** [comment]
I would not change Renault because it operates in serveral countries. 

Otherwise, I don't really get the point of adding 'brand:wikipedia'. Wouldn't it be enough to only add 'brand:wikidata'? The Wikidata object is connected to all Wikipedia languages so isn't 'brand:wikipedia' obsolete?

**Comment by bhousel** [comment]
> Otherwise, I don't really get the point of adding 'brand:wikipedia'. Wouldn't it be enough to only add 'brand:wikidata'?

Yes technically all of the Wikipedia tags are unnecessary in OSM.  Wikidata QIDs offer a more stable link to a concept.  But it really doesn't hurt anything to add the corresponding Wikipedia tags, and I think for now people expect them to be there.

Someone could ask the broader OSM community in other channels whether it might make sense to just remove all the Wikipedia tags from OSM and standardize on Wikidata for everything, but I feel like there would likely be pushback.

**Comment by Adamant36** [comment]
> I would not change Renault because it operates in several countries.

Same goes for Leader Price and Brico Dépôt.

**Comment by camelCaseNick** [comment]
> Yes technically all of the Wikipedia tags are unnecessary in OSM. Wikidata QIDs offer a more stable link to a concept.

In most situations...

Though with de:Aldi or en:Aldi, we have an article for Q41171373 (Aldi Nord) and Q41171672 (Aldi Süd), since the company split into two, while Aldi is the common brand, the Wikidata tags are more precise to which brand and group one store belongs.

Why do I tell? The problem then is, it is not simply a bijection between Wikidata and Wikipedia and it isn't just simply selecting the corresponding Wikipedia article for the Wikidata entry, since Aldi Nord and Süd don't have one.

**Comment by Adamant36** [comment]
> it is not simply a bijection between Wikidata and Wikipedia and it isn't just simply selecting the corresponding Wikipedia article for the Wikidata entry, since Aldi Nord and Süd don't have one.

We aren't as hamstrung on our side as some people make it out though since we can always create Wikipedia articles for them if need be. Even if it doesn't directly impact this project it would still be good give back to Wikidata/Wikipedia by helping them fill in some of their holes when it comes to information and articles about brands. For instance I've spent a lot of time working on expanding coverage of banks in Wikidata. Even in cases where the information I have added doesn't necessarily directly impact OSM or this project. It just seems like the right thing to do. There's much need for more articles about brands and I don't see why we can't contribute them in cases where it helps, or not. It doesn't really matter. I'm not really a big fan of the whole "It has to work in every instance to be beneficial" argument though. Especially considering how flexible this all is and how much we can do to improve things on both ends, but you can't expect someone else to do it for you. If you think it would be better if there where individual Wikipedia pages for Aldi Nord and Süd or whatever then create them and do a PR for us to add them.

**Comment by camelCaseNick** [comment]
> We aren't as hamstrung on our side as some people make it out though since we can always create Wikipedia articles for them if need be.

Of course and I have thought about it, though the relevance criteria for Wikidata differ from Wikipedia, so maybe in this case it might be a solution, in others it might be not the case.

> Even if it doesn't directly impact this project it would still be good give back to Wikidata/Wikipedia by helping them fill in some of their holes when it comes to information and articles about brands. For instance I've spent a lot of time working on expanding coverage of banks in Wikidata.

I know how those projects work, since I started with Wikipedia much earlier than OSM. I always appreciate if someone contributes! Thanks for that! I myself, add Wikidata entries sometimes to help me fill the `name:etymology:wikidata` gaps around me.

> Even in cases where the information I have added doesn't necessarily directly impact OSM or this project. It just seems like the right thing to do. There's much need for more articles about brands and I don't see why we can't contribute them in cases where it helps, or not.

That's how I came that I at least rarely contribute to (if I come across something I miss) Wikipedia, Wikidata, OpenStreetMap, OpenLibrary, Wikimedia Commons, OpenFoodFacts. So I get your mentality and may share it to some extent. But that does not make any point in favor or against my suggestion of omitting Wikipedia if it is the exact article for the most specific Wikidata entry.

> It doesn't really matter. I'm not really a big fan of the whole "It has to work in every instance to be beneficial" argument though.

That wasn't my point. We will never get to 100 %, though I thought at least one could think about those edge-case, especially if I had already a solution to suggest.

> Especially considering how flexible this all is and how much we can do to improve things on both ends, but you can't expect someone else to do it for you. If you think it would be better if there where individual Wikipedia pages for Aldi Nord and Süd or whatever then create them and do a PR for us to add them.

They are flexible indeed. I just suggested to omit Wikipedia if it is the exact article for the most specific Wikidata entry.

**Comment by bhousel** [comment]
ok, I did this!
