### ISSUE TITLE
amenity=post_box with name=*

### ISSUE THREAD

**Issue by Recoil016** [osmlab/name-suggestion-index#3410]
According to the Wiki, amenity=post_box should have the operator tagged in the operator=* tag, not the name=* tag (which makes sense, since postboxes usually do not have a name). This is currently not the case, thereby leading to post boxes tagged with a name when using the NSI and not double-checking the suggested tagging.

**Comment by bhousel** [comment]
Can you link to the wiki page where you found this?   Many times the wiki just reflects one person's opinions about how post boxes should be tagged.  It's really not a "spec".  I personally don't have a problem with postboxes that have UPS, FedEx, USPS, or whatever in the name field, and renderers are free to skip labels for those features.

If the entry made it into this index in the first place, it's because our scripts did find the name used frequently enough in the `name` field for it to get included.  (> 50 times)

Still, if people really are upset about names on post boxes, we can remove them from NSI like we did with the nextbike entries in #3378.   

Let's discuss, but not just assume the wiki is right (it often isn't).

**Comment by Recoil016** [comment]
The wiki page [here](https://wiki.openstreetmap.org/wiki/Tag:amenity=post_box) shows as tagging scheme to use the operator (aka. the mail service responsible) in the operator=* tag, it does not discuss the name=* tag at all.

My argument is more about general mapping practice, really and thought the Wiki was an accepted backup for that.

Since it apparently isn't have some data: [This overpass query](https://overpass-turbo.eu/s/OBf) for the German state of North-Rhine Westphalia (as an example) shows 4400 nodes with operator="Deutsche Post" whereas [this query](https://overpass-turbo.eu/s/OBh) with name="Deutsche Post" only returns 34 nodes. At least for Germany, this is considered mapping practice.

I just think it is factually wrong. At least in Germany, postboxes do not have names, they have a ref=* at most, and well, the operator that runs them.

**Comment by bhousel** [comment]
Ok, you convinced me.. I removed the post boxes in 0de5108b6.  I didn't realize people were so uptight about seeing `name` tags on them.

Let me know if you find anything else in our index that you want removed.

**Comment by Recoil016** [comment]
Please be aware that I never meant to have the post boxes removed from the index, I just wanted to point to the idea that maybe the "name" should be moved to the "operator".

**Comment by bhousel** [comment]
> Please be aware that I never meant to have the post boxes removed from the index, I just wanted to point to the idea that maybe the "name" should be moved to the "operator".

That's ok!  We can put them back once the code is set up to work with `operator` tags.  They've been gone since #2816, but we know there are some situations where they make sense.
