### ISSUE TITLE
Vue cinemas

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#3420]
Normally in iD when you have a plain POI - e.g. with amenity=cinema and name=Vue - iD would prompt you to upgrade the tag if it is present in the NSI. 

For Vue Cinemas, if you click in the name field and press space iD offers the UK/Ireland and Netherlands versions.

Can this be fixed in the NSI so that Vue on its own in the UK is recognised as a brand needing to be upgraded? As it seems like the "(IrelandAndUK)" part of the name is causing a problem.

Let me know if this issue should be in the iD github instead.

**Comment by bhousel** [comment]
I think iD will not offer to upgrade names that are ambiguous.
These are names with a `~(something)` on the end.  Users will need to perform these upgrades manually for now.

**Comment by boothym** [comment]
Ok. Would it be possible for iD to compare only the first part of the name (i.e. before the ~)? And then since there is a country code to separate the UK/IRL and Netherlands brands, only one brand will match, which could be offered as an upgrade?

**Comment by bhousel** [comment]
> Ok. Would it be possible for iD to compare only the first part of the name (i.e. before the ~)? And then since there is a country code to separate the UK/IRL and Netherlands brands, only one brand will match, which could be offered as an upgrade?

I think _sometime in the future_, the geometry will be what disambiguates the entries and all the tools that we use will have the ability to know whether a user is editing within that geographical region.  iD won't need string disambiguators.  But for right now - we use strings because that was the fastest way to get something working that isn't broken.

What makes this problem tricky is:
- iD's country code awareness only recently (last month) got a boost by integrating the [country-coder](https://github.com/ideditor/country-coder) dataset.  Before that, we needed to do nominatim lookups and those are slow.
- But it's not just limited to country codes.. Even within countries we have brands with the same name operating independently.

A good example of this is "Price Chopper", which has 2 different entries (New York and Kansas City).  https://nsi.guide/index.html?k=shop&v=supermarket#Price%20Chopper~(Kansas%20City)
https://overpass-turbo.eu/s/OJZ

Another is "Giant" fuel stations - one is related to a Supermarket  (and there are multiple ambiguous Giant supermarkets), another is a southwestern chain that is in the middle of a rebrand to "Marathon" or maybe "Speedway" (see 9e1668ad1c)  https://overpass-turbo.eu/s/OK0

**Comment by UKChris-osm** [comment]
Could the two Vue entries have the "_~(IrelandAndUK)_" and "_~(Netherlands)_" removed, as both have country code references?

I tried placing a random node in the UK, and the Vue suggested was the UK one, and placing a node in the Netherlands resulted in the Netherlands Vue being suggested.

**Comment by SilentSpike** [comment]
@UKChris-osm: They still need unique keys in the json data which is why we add those.

In theory iD (or any downstream software) could remove that bit of the string when shown to the user, but you'd need to make sure two disambiguated brands are exclusive to regions with no overlap before doing that - which is quite sophisticated to implement for such a small change.

**Comment by UKChris-osm** [comment]
Ah I see, I wasn't sure as I saw both entries had the same "_Vue_" name & brand tag and assumed this meant the same initial value (_amenity/cinema|Vue_) could appear in multiple entries with different Country Codes.

**Comment by bhousel** [comment]
> I think _sometime in the future_, the geometry will be what disambiguates the entries and all the tools that we use will have the ability to know whether a user is editing within that geographical region.

The work on https://github.com/osmlab/name-suggestion-index/issues/2714#issuecomment-646296593 unblocks us to being able to disambiguate the entries by their locationSet geometry instead of a string like "(IrelandAndUK)" .

Closing this issue in favor of #3995, which is the same idea.
