### ISSUE TITLE
Add Christian Science Reading Room

### ISSUE THREAD

**Issue by wireguy** [osmlab/name-suggestion-index#3520]
https://en.wikipedia.org/wiki/Christian_Science_Reading_Room
https://www.wikidata.org/wiki/Q5110122

some have shop=books
some have amenity=place_of_worship  or library
some have shop=religion

**Comment by mds08011** [comment]
Do you have a preference in tags?  `shop=religion` seems appropriate based on my vague understanding of these facilities, but I am a bit nervous that it could turn controversial if viewed as a "downgrade" compared to `amenity=place_of_worship`.

**Comment by wireguy** [comment]
I have less than vague understanding. 😄   I just added one as a poi to the map and was surprised that it wasn't in nsi.    Thought it would be good to get added and try and get some consistency in the tagging.

**Comment by Adamant36** [comment]
Personally, I would go with shop=books + amenity=place_of_worship. Shop=religion seems to broad since they mainly or only sell books and I don't see why amenity=place_of_worship can't still be tagged on them. Since the tags aren't mutually exclusive. Although, I wonder how that would work in the NSI.

**Comment by bhousel** [comment]
I just checked [taginfo](https://taginfo.openstreetmap.org/keys/books#values)

lets go with `shop=books` + `books=religion`
