### ISSUE TITLE
The "Gino's Pizza" in fast_food.json is not US-wide.

### ISSUE THREAD

**Issue by SomeoneElseOSM** [osmlab/name-suggestion-index#3521]
The name suggestion index 

https://github.com/osmlab/name-suggestion-index/blob/eff7ae0093aaa15b14406aafe7e3c5bbf7520c5d/brands/amenity/fast_food.json

suggests

      "brand:wikidata": "Q5563205",
      "brand:wikipedia": "en:Gino's Pizza and Spaghetti",

but that (following the links through from wikipedia) seems to be a local WV chain http://ginospizza.com/ .

Many of the ones in OSM are in the Toronto area and appear to be actually https://ginospizza.ca/ .  I suspect that some of the others elsewhere aren't branded chains at all but just opened by people called "Gino".

Can the existing "Gino's Pizza and Spaghetti" suggestion be restricted to West Virginia only?

For the avoidance of doubt this is nothing to do with "Papa Gino's" - they exist in OSM in New England, which matches https://www.papaginos.com/locations .

**Comment by maxerickson** [comment]
I think there's not yet support for country sub-regions.

Really the issue here is that support for the countryCodes restriction wasn't turned on in iD until, I think, December 2019.

Searching with Overpass, there's only 1 false positive in the US (and that place has the wrong name entirely, apparently due to going out of business and reopening).

**Comment by maxerickson** [comment]
I've created a wikidata item for the Canadian chain and added an entry here, which should help in contexts where the countryCode isn't considered.

Closing this now, as adding smaller regions isn't likely to happen soon.

**Comment by SomeoneElseOSM** [comment]
> Searching with Overpass, there's only 1 false positive in the US

I think that's because I fixed some and commented on the changesets of others a couple of days ago...

The problem with "generic" names like this is that many of the establishments with that name (perhaps even in WV, but certainly elsewhere) are just going to be independent establishments that have chosen an "Italian" name (and similar for other styled establishments too, like "Irish" pubs).  A quick search for Gino's in the UK (where a long way from either West Virginia or Ontario) finds ones in [Cleethorpes](https://ginospizzagrill.co.uk/), [Bradford](https://ginospizzas.co.uk/), [Cradley Heath](https://ginosperfectpizza.co.uk/), [Seaford](https://ginosofseaford.com/) and more.

Until the name suggestion index supports geographical areas smaller than a country, if a chain operates in only one US state presumably it makes sense to not suggest it at all rather than suggest it in 49 states where the chain doesn't operate?

**Comment by maxerickson** [comment]
I dunno, I'm pretty comfortable with it. Here we are talking about ~10 items (on Jan 1 anyway: https://overpass-turbo.eu/s/QfY ) that were mostly added because of miss-applied enthusiasm, not because the editor had a button.

I also don't really buy the argument that extremely defensive presets are a net benefit. The number 1 thing the US data needs to get more users (and thus more mappers) is POIs. Being able to do a nice job of adding them by searching names is *fantastic*, and worth a little friction on the data quality end of things (I don't kid myself that bloody, sweaty, hand tagged data is particularly perfect, so I'm forgiving of data that is added using nice features like NSI also not being perfect).

**Comment by SomeoneElseOSM** [comment]
For completeness, that overpass query shows **29** items, not 10 (19 of them over the border in Ontario - but hopefully your addition [above](https://github.com/osmlab/name-suggestion-index/issues/3521#issuecomment-580217050) will pick those up).  1 was in WV, so the "accuracy" of this particular brand tagging was about **3%**.

**Comment by maxerickson** [comment]
Sorry, I thought it was clear from context, I meant the ~10 entries that would be impacted by moving the scoping from "us" to "us-wv". The "us" scoping should be enough to prevent any new entries in Canada.
