### ISSUE TITLE
shop/beauty|Yves Rocher  ( brand:wikipedia != brand:wikidata )

### ISSUE THREAD

**Issue by ImreSamu** [osmlab/name-suggestion-index#3603]
The current `shop/beauty|Yves Rocher` tags is:
```
      "beauty": "cosmetics",
      "brand": "Yves Rocher",
      "brand:wikidata": "Q28496595",
      "brand:wikipedia": "en:Yves Rocher (company)",
      "name": "Yves Rocher",
      "shop": "beauty"
```
imho `"brand:wikipedia": "en:Yves Rocher (company)"`  -->  https://en.wikipedia.org/wiki/Yves_Rocher_(company)  --> [Q1477321](https://www.wikidata.org/wiki/Special:EntityPage/Q1477321) 
and not the current "brand:wikidata":  [Q28496595](https://www.wikidata.org/wiki/Q28496595)

so now  ( brand:wikipedia != brand:wikidata )

**Comment by 1ec5** [comment]
Q28496595 is more specifically about the cosmetics company, while Q1477321 is about the parent company, also known as Groupe Rocher. The English Wikipedia article vaguely covers both. The `brand:wikidata` tag is accurate, but the `brand:wikipedia` tag should be removed because data consumers probably expect the two tags to correspond to one another, and the brand tags aren’t meant to express corporate hierarchy.

**Comment by Adamant36** [comment]
Done in 0882b54

**Comment by Cj-Malone** [comment]
> Q28496595 is more specifically about the cosmetics company, while Q1477321 is about the parent company, also known as Groupe Rocher

This seems to have switched now, [Q28496595](https://www.wikidata.org/wiki/Q28496595) is about the parent org, [Q1477321](https://www.wikidata.org/wiki/Q1477321) is the cosmetics company.
