### ISSUE TITLE
Carphone Warehouse in the UK

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#3641]
In the UK, the brand "_Carphone Warehouse_" is closing all of its standalone branches, and only having concession stands / counters inside "Currys PC World" stores.

When it comes to the NSI entry for Carphone Warehouse, is there:

A) Any OSM tag that can be included with a Carphone Warehouse node that indicates it is inside a Currys PC World? (e.g. 'is_in:Currys PC World' or 'location:Currys PC World')

B) If there is such a tag as mentioned in A), can this tag be included in the NSI entry as standard?

**Comment by Adamant36** [comment]
Personally, I would approch this the same way we handle pharmacies inside drug stores, banks inside grocery stores, etc etc. Just have a normal entry and let people map it as a stand alone node if need be. It seems to work fine that way. There isnt a need for a tag like is_in. It would be pointless to use a tag IMO because people can see what its in when looking at the map.

**Comment by bhousel** [comment]
I agree we can leave this as it is.  We can't support tags like `is_in:`, but if people want to add these things as standalone nodes inside an existing store, that's fine.
