### ISSUE TITLE
Add french jewellery Marc Orian

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#3677]
```
name=Marc orian
shop=jewelry

```
28 objects in osm: https://overpass-turbo.eu/s/Ss8
109 shops: https://www.marc-orian.com/fr_FR/notre-liste-bijouteries/storelocator-stores-list-page.html
Website: https://www.marc-orian.com
wikidata: not yet

**Comment by ankita2210** [comment]
I would like to work on this

**Comment by Identitaet** [comment]
No problem we'll wait for your pr

**Comment by ankita2210** [comment]
Can you suggest why ci build failed in spite of successful local build  @Identitaet  for PR https://github.com/osmlab/name-suggestion-index/pull/4245

**Comment by bhousel** [comment]
> Can you suggest why ci build failed in spite of successful local build @Identitaet for PR #4245

Yes, you can click on "details" next to the failed build - it will take you to Travis where you can view the logs.

The logs show this:
<img width="610" alt="Screen Shot 2020-10-02 at 10 31 50 AM" src="https://user-images.githubusercontent.com/38784/94935164-ab478d80-049a-11eb-928a-b015e05cdf0b.png">

So I think something got broken in the `validate.js` script, because "validateLocationSet of undefined" means it can't call some function it wants to.

I've been changing the build scripts a bunch lately, so I'll check and see what I might have broken.

**Comment by bhousel** [comment]
> Once the build passes this PR can be reviewed or shall I fork again and create fresh PR for this issue?

I just merged it, it's probably fine

**Comment by ankita2210** [comment]
> > Once the build passes this PR can be reviewed or shall I fork again and create fresh PR for this issue?
> 
> I just merged it, it's probably fine

Thank you very much for the quick support here :-)

**Comment by UKChris-osm** [comment]
@ankita2210 I'm not sure if you created the Wikidata for Marc Orian, but if you did, just a quick heads up that for the entry for Facebook (in fact for all social media entries), you only need to use the name / ID of the Facebook page, and not the whole web address :)

**Comment by ankita2210** [comment]
> @ankita2210 I'm not sure if you created the Wikidata for Marc Orian, but if you did, just a quick heads up that for the entry for Facebook (in fact for all social media entries), you only need to use the name / ID of the Facebook page, and not the whole web address :)

Yes I created the wikidata for Marc Orian . Will keep this in mind. Thanks for the tip :-)
