### ISSUE TITLE
Best way to update Co-op Food

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#3686]
Currently there are two entries for "**The Co-operative Food (UK)**", one as a supermarket and one as a convenience store.

However, the Co-op have now re-branded to "**Co-op Food**", so can the names simply be updated in the master file, or is there a proper process for dealing with name changes for entries that already have quite a high usage?

**Comment by bhousel** [comment]
I’d update the keys and name tags for these entries in NSI, then also preserve the old name as a `matchName` because it’s likely to remain in the OSM database this way for a while (and we don’t want the old name reintroduced).

If the stores have all been rebranded in real life, someone could rename them all quickly in OSM with overpass and JOSM or level0.  If the stores are slowly rebranding, then it’s ok to leave them alone until mappers with local knowledge can rename each location. 

(Either way is probably ok - this rename is unlikely to cause confusion if someone looks at a map and the map pin says “Co-op Food” instead of “The Co-operative Food”).

**Comment by UKChris-osm** [comment]
Updated via https://github.com/osmlab/name-suggestion-index/commit/2c16174df2e3546137db7e3c1e8522751a79a373 & https://github.com/osmlab/name-suggestion-index/commit/72fbbe14d50372556a3305c7e48583db1b53ead8.

**Comment by bhousel** [comment]
@UKChris-osm I had to cleanup what you did in a followup commit because the build script was trying to reintroduce the old "The Co-operative Food" entry.  The `matchName` shouldn't include the "~(uk)" part, because that's not actually part of the name.

**Comment by UKChris-osm** [comment]
Thank you @bhousel
