### ISSUE TITLE
Amazon Locker

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#3748]
I've just noticed two entries under **vending_machine** for Amazon Locker, which differ in language only and use the same wikidata article, and just wanted to ask:

- Can these be merged into a single "_Amazon Locker_" entry with multiple languages and locations?
- Does this entry need its own "_Amazon Locker_" wikidata entry, or could it just use the standard "_Amazon_" wikidata entry, and as such the standard Twitter hosted logo that accompanies it?

**Comment by tas50** [comment]
Amazon is fine as the wikidata entry if there isn't one for amazon locker specifically.

**Comment by bhousel** [comment]
These are the entries:
https://github.com/osmlab/name-suggestion-index/blob/8cae61bbbe18be164e46256593b5517818015414/brands/amenity/vending_machine.json#L2-L29

(Pro tip! You can link to lines of code on GitHub by shift-selecting the lines, clicking the … meatball menu, and selecting "copy permalink".  Then paste it into an issue so we can talk about it easier).

Because Amazon Locker has its own wikidata and wikipedia identies (like many Amazon products and sub-businesses do), what we have in NSI is correct.

* They should not be merged, because they use different languages
* The Amazon Locker wikidata and wikipedia links are correct and should not be changed to the parent Amazon entry.
