### ISSUE TITLE
Add french pharmacy Lafayette

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#3756]
`name=Lafayette `
`amenity=pharmacy`
`healthcare=pharmacy`
`dispensing=yes`

Curently 53 / [160](https://www.pharmacielafayette.com/enseigne/pharmacies) in France (métropole + DOM) : https://overpass-turbo.eu/s/T6J
website: https://www.pharmacielafayette.com
wikidata: [Q91301346](https://www.wikidata.org/wiki/Q91301346)

**Comment by bmillemathias** [comment]
Hello,

Ok I already come across (https://www.openstreetmap.org/node/1811696848) , we should not set the name because each point has it's own name (locally everyone knows this pharmacy but its name), but set the brand and network keys.

**Comment by pyrog** [comment]
> we should not set the name

Yes 😃 
For me name is the name of the brand in [brands/amenity/pharmacy.json](https://github.com/osmlab/name-suggestion-index/blob/master/brands/amenity/pharmacy.json) and brands/healthcare/pharmacy.json 😉

>  but set the brand and network keys.

Does we really need to set the `network` key ?

PS: That's why we need a template to avoid ambiguities (cf. #3755)

**Comment by bhousel** [comment]
I'm having trouble following this discussion, but 
- If these pharmacies all have very different names than we can't support them in the name-suggestion-index right now, (see Wetherspoons,  https://github.com/osmlab/name-suggestion-index/issues/3009#issuecomment-583870522 and https://github.com/osmlab/name-suggestion-index/pull/3103#issuecomment-542804294 )
- We don't set `network` keys now for pharmacies (or anything else yet), and I'm not sure what information would be stored in it in the context of a pharmacy. (see [network](https://wiki.openstreetmap.org/wiki/Key:network) on osm wiki)

**Comment by pyrog** [comment]
Hi Bryan,

I read your comments. Thank for the explanations 😃 

I thought that NSI also work on brand's names.
Could be fine to add this feature 😃 

> We don't set network keys now for pharmacies (or anything else yet)

I founded these keys in french data, but they should be deleted.

**Comment by pyrog** [comment]
> I thought that NSI also work on brand's names.

A workaround could be:

1. we type the name
1. the editor add brand and other tags
1. we replace the name by the real one

What do you think of that ?

**Comment by bmillemathias-1a** [comment]
> > I thought that NSI also work on brand's names.
> 
> A workaround could be:
> 
>     1. we type the name
>     2. the editor add brand and other tags
>     3. we replace the name by the real one
> 
> 
> What do you think of that ?

How a contributor in ID would know he was to remove the name (and actually iD locks the field when it comes from nsi). That's no go for me.

**Comment by bmillemathias-1a** [comment]
>     * We don't set `network` keys now for pharmacies (or anything else yet), and I'm not sure what information would be stored in it in the context of a pharmacy. (see [network](https://wiki.openstreetmap.org/wiki/Key:network) on osm wiki)

I was talking about network because Lafayette as I understand it, from the local pharmacy I know is not really a brand , but a network of pharmacy. The logo and the name is present of the front but this is not the main name as it would be for a real brand (Tesco, Target, ...). Perhaps this name is not correct in the context of OSM (but I saw use of it in the very same spirit of what I suggested on the taginfo). The corporate site even use the word "network" ("réseau" in French) in https://www.pharmacielafayette.com/enseigne/pharmacies

But.... After looking few seconds some pharmacies actually use Lafayette name and logos (https://www.pharmacielafayettetoulouse.com/) and the corporate site reports each pharmacy includes "Lafayette" in their name but the name is different for each.
(https://www.pharmacielafayette.com/enseigne/pharmacies)

So I've hard time giving a finite answer. What I know, is I'd like to be able to set the local name, Any thought ?

Best.

**Comment by pyrog** [comment]
> How a contributor in ID would know he was to remove the name

If he don't know, he keep the name 😉 

> actually iD locks the field when it comes from nsi

For information, iD locks the field if there is a `brand:wikidata`.

Go to **All tags**, change the name value to "Pharmacie du Centre" and… that's all 😃

**Comment by pyrog** [comment]
> I was talking about network because Lafayette as I understand it, from the local pharmacy I know is **not really a brand , but a network of pharmacy**. 

👍 

In France, there are ~ hundreds of "networks", trade unions : https://www.labodata.com/annuaire-des-groupements-de-pharmacies
