### ISSUE TITLE
Add name, brand, and brand:wikidata=* for common franchises

### ISSUE THREAD

**Issue by picsi** [osmlab/name-suggestion-index#38]
For example, if I'm going to use the McDonald's iD preset to tag a restaurant, it would automatically add `operator:wikidata=Q38076`. 

The tag `brand:wikidata=*` can also be conceivably be used if any iD presets make use of `brand`.

**Comment by pnorman** [comment]
There was discussion somewhere of a mechanical edit or software change adding other `*:wikidata` tags which concluded against them. I wish I could find it.

**Comment by picsi** [comment]
@pnorman Are you referring to Mapbox's mechanical import of Wikidata IDs?

**Comment by picsi** [comment]
Elaborating further, this would not be more mechanical than what iD currently does, when it fetches Wikidata IDs from Wikipedia entries.

**Comment by planemad** [comment]
Sounds like a practical idea that makes the OSM data more valuable by providing linkages to an external crowdsourced database. 

@pnorman It would be great if you could recall why this would not be a positive addition to the data.

**Comment by ImreSamu** [comment]
imho: **it is very hard to maintain, because franchise shops change quickly**  (closing and re-opening in the new place) and hard to detect the error/changes with other OSM editors, which not implemented this feature.
Like pushpin ( http://www.pushpinosm.org/ ) with this editor I can't see all key-values, 
so I can't modify or change the old `brand:wikidata=*` tags, 
So if the "McDonalds" closed and a  now it is a "Burger King", I will modify to "name=Burger King" but I can't modify the `brand:wikidata=Q38076` , so it will be a wrong value.

The **"Adding Wikidata tag to Cities and Towns"** is not a same case, because it is not change as frequently.  
So editing with a different editors not cause a trouble, because Towns wikidata tags usually not change.

But creating a metadata for post-processing will be very useful. Like a lookup table,  
So If somebody need it,  it is easy to add this information with a minimal code.

So my vote:
* YES: for creating this metadata for post-processing as a separate table ( lookup table )
*  NO : for Automatically add this tags with iD editor.


Probably it can be a similar but separated file, like: 

```json
    "amenity/fast_food|McDonalds": Q38076,
    "amenity/restaurant|McDonald's": Q38076,
    "amenity/fast_food|McDrive": Q38076,
    "amenity/restaurant|McDrive": Q38076,    
    "amenity/fast_food|Макдоналдс": Q38076,
    "amenity/restaurant|Макдоналдс": Q38076,
    "amenity/fast_food|Мекдоналдс": Q38076,
    "amenity/restaurant|Мекдоналдс": Q38076,
    "amenity/fast_food|맥도날드": Q38076,
    "amenity/restaurant|맥도날드": Q38076,
    ...
    "shop/supermarket|Carrefour Market": Q2689639,
    "shop/convenience|CBA": Q779845,
    ...        

```


Probably the metadata can be generated from the wikidata tags https://www.wikidata.org/wiki/Q38076
see names in different languages:
af:McDonald's
ar:ماكدونالدز
arz:ماكدونالدز
ast:McDonald's
az:McDonald's
bcl:Mc Donald's
be:McDonald’s
bg:Макдоналдс
bn:ম্যাকডোনাল্ড’স
ca:McDonald's
...

**Comment by tyrasd** [comment]
@ImreSamu interestingly, such a mechanism can almost already be implemented directly in the wikidata database: It is possible to link any wikidata entry to a specified OpenStreetMap tag (key or key/value pair); here's an example: https://www.wikidata.org/wiki/Q7321974. See http://www.openstreetmap.org/user/PlaneMad/diary/40537 or @species [osm&wikidata talk](https://frab.fossgis-konferenz.de/de/2016/public/events/5053) (in German). One would only need to extend the definition of this wikidata property [(P1282)](https://www.wikidata.org/wiki/Property:P1282) to accomodate tag combinations (an maybe tag aliases).

**Comment by ImreSamu** [comment]
@tyrasd : Thanks for the info!   So my imaginary  "Metadata"/"LookUp table"  (` "amenity/fast_food|McDonalds": Q38076, ` )  can be fully generated from the Wikidata. ( in the future )  
Good News!

**Comment by 1ec5** [comment]
> For example, if I'm going to use the McDonald's iD preset to tag a restaurant, it would automatically add `operator:wikidata=Q38076`. 
> 
> The tag `brand:wikidata=*` can also be conceivably be used if any iD presets make use of `brand`.

Note that `operator:wikidata` would likely indicate the franchisee, while [`brand:wikidata`](https://wiki.openstreetmap.org/wiki/Key:brand:wikidata) would indicate the franchisor (McDonald’s in this case).

**Comment by nyurik** [comment]
Based on a few discussions I saw on forums and chats, it seems it is far better to use `brand:wikidata` for almost everything. The "operator" is usually hard to find, especially with all the franchises, companies creating local sub-companies, etc. The brand is always customer-facing, and is always designed to communicate the content of the store/restaurant, so has much higher value to the consumers.

**Comment by matkoniecz** [comment]
Also, brand:wikidata/brand is far more likely to be useful for data consumers.

**Comment by bhousel** [comment]
Updating the title.. I think by now tagging has settled on `brand` & `brand:wikidata`

**Comment by picsi** [comment]
Sounds good to me!

**Comment by ImreSamu** [comment]
@bhousel : 
Thank you for working on this topic! :heart: 

checking:  `"Add brand tag for everything"` -  https://github.com/osmlab/name-suggestion-index/commit/d4c1b8437d47d63c6344e448c4c937b42f7b432d  - I have some comments.


### 1.  general words -  inside.
 
We need some time to check and clean the list, because some hungarian general words are still inside.
It is not an extreme problem without a 'brand' , but with a brand= it is bad. 

example :  "Gyógyszertár" ->  Hungarian word for pharmacy,  sometimes this is the _real name_ of the amenity  and  it is not an extremely bad practice.
 
But "brand"="Gyógyszertár"  is bad tags.
```
  "amenity/pharmacy|Gyógyszertár": {
    "count": 68,
    "tags": {
      "amenity": "pharmacy",
      "brand": "Gyógyszertár",
      "name": "Gyógyszertár"
    }
```


so **this is a frequent name - but not a brand.**

So probably we need to
*  remove the  "amenity/pharmacy|Gyógyszertár"  from the list.
* or remove the brand= tag



### 2.    local vs. global brands ...    `Tesco` vs.  `Tesco Express`

Imho - need some data cleaning, and re-checking the global brands 

quick example:  Tesco 

name= | (now) brand=  | (imho) brand=  
------------ | ------------- | ------------------
Tesco | Tesco |  Tesco
Tesco Metro| Tesco Metro  | Tesco
Tesco Express |  Tesco Express |  Tesco
Tesco Lotus Express | Tesco Lotus Express | Tesco
TESCO Lotus Express | TESCO Lotus Express | Tesco

### summary 

imho :  We (  local communities )  need some time to re-check, and clean -  before this is going to the live system.

**Comment by bhousel** [comment]
Hey @ImreSamu thanks for your thoughts!

> 1. general words - inside.
> We need some time to check and clean the list, because some hungarian general words are still inside. It is not an extreme problem without a 'brand' , but with a brand= it is bad.
> example : "Gyógyszertár" -> Hungarian word for pharmacy, sometimes this is the _real name_ of the amenity and it is not an extremely bad practice.

☝️ Yes - I will definitely need help from local mappers to know which of these things are "noise" words and which are actual brand franchises.  I tried to take a first pass here:  
https://github.com/osmlab/name-suggestion-index/blob/master/config/filters.json

Adding more regexes to the discardName filters will help.  I'm also thinking of adding a property to limit some entries only for certain languages..  I guess that's also #11.


> 2. local vs. global brands ... `Tesco` vs. `Tesco Express`
> Imho - need some data cleaning, and re-checking the global brands

☝️ For this part, I still need to do a first pass at merging all the obvious duplicates so that only one entry appears in `canonical.json`:
https://github.com/osmlab/name-suggestion-index/blob/master/config/canonical.json

I'm not quite ready to have people help yet, but my goal is to get this project to a place in the next few days where I can spread the word and ask for a lot of volunteers to help hunt down the missing tags like `brand:wikidata` and make sure everything looks ok.

**Comment by matkoniecz** [comment]
> I will definitely need help from local mappers to know which of these things are "noise" words and which are actual brand franchises

Are these terms actually used as values of a brand tag?

https://taginfo.openstreetmap.org//search?q=brand%3DPiekarnia
https://taginfo.openstreetmap.org//search?q=brand%3Dpiekarnia

appears to be unused.

I think that it would be useful to generate list of proposed brand tag values that are not currently used or usage is really low (below 10?).

**Comment by bhousel** [comment]
> I think that it would be useful to generate list of proposed brand tag values that are not currently used or usage is really low (below 10?).

We can do that in `config/canonical.json` now - add entries for things that are rare.

Currently I did this only for "shop/wholesale|Costco".   In the current osm planet, Costco is more frequently tagged as a "shop=supermarket" or "shop=department_store", but these really should be changed to "shop=wholesale" (based on previous tagging threads and the osm wiki).  

I like the idea that this project can help find features like this so that volunteers can review and fix (#98)

**Comment by matkoniecz** [comment]
> I will definitely need help from local mappers to know which of these things are "noise" words and which are actual brand franchises

It may be a good idea to generate a website listing entries appearing in each country. So for example somebody from Poland will not need to scroll through screens of Cyrillic, Japanese, Korean and Chinese names and someone from Japan will not look at names with ążółćźż.

**Comment by bhousel** [comment]
Closing here because we are starting to do this.  

Deduplication and assignment of `brand`, `brand:wikipedia`, and `brand:wikidata` tags will be the main focus of this project starting in a few days.  I'll open up new issues for people to help out with this.

**Comment by matkoniecz** [comment]
> brand:wikipedia, and brand:wikidata

Do you plan to add them all manually or is there a smarter way to do that?

I thought about importing existing OSM data, but I worry about quality (and coverage would be small), automatic fetching from Wikidata/WIkipedia would likely contain at least some errors and require a full review...

I ask as I though about making some PRs, but it would be sad to do manually what will be soon automated.

**Comment by bhousel** [comment]
> Do you plan to add them all manually or is there a smarter way to do that?
> 
> I thought about importing existing OSM data, but I worry about quality (and coverage would be small), automatic fetching from Wikidata/Wikipedia would likely contain at least some errors and require a full review...
> 
> I ask as I thought about making some PRs, but it would be sad to do manually what will be soon automated.

I'm also worried about the quality and coverage of existing wiki tags in OSM.  That still might get us a head start though, which would be useful.

My real plan is to automatically open up GitHub issues for everything that needs checking (this may be thousands of things) and then ask [Hacktoberfest](https://hacktoberfest.digitalocean.com/) volunteers to send us PRs.  That promotion runs throughout October and is specifically designed for people who are new to open source and want to submit simple pull requests.

For that idea to work, I need to really improve the contributing document, so that people know how to find the wiki tags and where to put them in canonical.json.
