### ISSUE TITLE
Dissolved filter in the UI

### ISSUE THREAD

**Issue by Crashillo** [osmlab/name-suggestion-index#3800]
Since the NSI is able to store the dissolved brands, it would be strongly recommended do not use that brands. 
Could be possible hide those dissolved brands from startup and append another checkbox, as the `incomplete` does, in order to enable displaying dissolved brands? 

Proposal:
![imagen](https://user-images.githubusercontent.com/817526/80864035-40dab900-8c80-11ea-97e4-6a46d2c56fb4.png)

**Comment by Adamant36** [comment]
> Since the NSI is able to store the dissolved brands, it would be strongly recommended do not use that brands.

It's still useful to get icons for them and update their Wikidata information where we can IMO. What's exactly is the disadvantage of showing them? Especially when if you add their logo to Wikidata they will be filtered out anyway by checking "incomplete."

**Comment by Crashillo** [comment]
Does *incomplete* tag mean they don't have yet a matching wikidata, right? But a dissolved brand may have an wikidata anyway. It could be complete, besides dissolved.
I say so because, imho, it's not clear enough when a brand is dissolved, thus using the tag should be discouraged. Currently, you've to notice at the description column, the *former* word, haven't you? And sometimes, it's missing, for instance *Banco Pastor*, it does appear in dissolved.json, even though there is nothing to identify the brand as dissolved.
My idea is about letting the editor know: "hey, this brand is dissolved, be careful", to encourage him to use the current brand name, or update the tags properly (perhaps, move the name to old_name), so a visual tip (different color, checkbox, filter, whatever...) would be quite helpful.

**Comment by Adamant36** [comment]
> Does incomplete tag mean they don't have yet a matching wikidata, right?

Yeah exactly. If you add an icon for them in Wikidata and then check incomplete after the site is updated it should filter them out. 

> imho, it's not clear enough when a brand is dissolved, thus using the tag should be discouraged.

IMO this is just a list of brands and the NSI just serves as a way to show what entries need Wikidata information still. Whatever their status might be. It's not intended to push the user in one way or another. A more practical thing in that respect would be to have a "possibly dissolved" warring in iD Editors side or something. Although, the it might unintentionally encourage people to delete POI's for brands that are not actually dissolved yet. Which is why I was never solid on a check box to filter the entries out. 

The important thing is to add information to Wikidata. Whatever state the business is in. As it could be slow dissolution, they could be bought out and come back, it could be fake news, etc etc.

I was reading the other day that there was still one Blockbuster out there until a few months ago even though they have technically been out of business for years. Same with Toys R Us, who is currently coming back I think. So on our end if it is "dissolved" or not is semi-meaningless IMO. 

> My idea is about letting the editor know: "hey, this brand is dissolved, be careful"

They can always read the description for the entry. I always make to sure state something like "defunct whatever" on Wikidata's side for the description so it will show up that way on the NSI site. Plus, it improves Wikidata. A lot of entries are missing both labels and descriptions. BTW, I'm not necessarily saying I'm against a way to filter them out, just weighing the pros and cons. I've been sure how it works for dissolved brands on NSI/iD Editors side. But it seems to me the ultimate best answer would be to re-tag all of the dissolved brands mapped locations to whatever they are now so it's just not in the index or iD Editor anymore.

**Comment by bhousel** [comment]
Thanks, I agree this flag might be useful, but with caveat that "dissolved" is kind of messy data currently.  @Adamant36's comments above are spot-on.  A brand is marked this way if it has an end_date property on wikidata.  It would be good to surface this on https://nsi.guide somehow.

#3154 has some thoughts on the limitations of "dissolved" in this index.  We currently have many brands that should be in "dissolved" and aren't, and others that are in "dissolved" state and shouldn't be.

**Comment by bhousel** [comment]
I added this today 👍 

Now there is a checkbox so that people can filter items that have a dissolved date that we've collected from Wikidata:
<img width="700" alt="Screenshot 2023-07-19 at 1 19 12 PM" src="https://github.com/osmlab/name-suggestion-index/assets/38784/3ba086f3-0018-4a2a-bee0-41ddbe3e5e88">


And the nsi.guide site will show the year of dissolution (if any) alongside the other info that we show:
<img width="300" alt="Screenshot 2023-07-19 at 1 17 19 PM" src="https://github.com/osmlab/name-suggestion-index/assets/38784/c4f66574-081b-481a-ab78-6b799c44c9de">
