### ISSUE TITLE
modify the "Tobaccoland cigarette vending machine" preset

### ISSUE THREAD

**Issue by Lukas458** [osmlab/name-suggestion-index#3880]
Hi,
I have some issues on the preset for cigarette vending machines of the operator "Tobaccoland", in Germany.

1. There is set brand=Tobaccoland, brand:wikidata etc. Don't you think it would be better to add this information with the "operator" key? "Tobaccoland" is only the company which operates the vending machines, but "Tobaccoland" is _neither_ the brand of the vending machine itself (in my eyes) _nor_ the brand of the cigarettes which are sold.

2. The presets sets "name=Tobaccoland". I'm not very fine with this. Vending machines should not get any name at all. Vending machines do not have a name. It's like tagging all recycling containers with the name of the company which operates them. Not fitting really.

3. I think there are some more tags which could be added to the preset, because there are some tags which are valid for all of Tobaccoland's vending machines. In Germany, only people 18+ are (allowed and) able to operate them - age verifying is needed. So min_age=18 would fit.

Furthermore, I think material=metal and button_operated=yes should fit for all these vending machines, but I know those are more "general" tags which do not really carry very useful information...

**Comment by bhousel** [comment]
All of the entries in this index currently need to have a `name`, and the index is seeded from objects from OSM that have that name.  In other words, if we have a Tobaccoland entry, it's because that feature already exists at least 50 times in OSM with `name=Tobaccoland` .  (I did look at the history and the Tobaccoland entry seems to have been in the index since [at least v1.0](https://github.com/osmlab/name-suggestion-index/blob/v1.0.0/config/canonical.json#L15127) a few years ago).

If the Tobaccoland entry is problematic, I'd prefer just remove it rather than try to modify the project code to work with features that don't use consistent `name` and `brand` tags.

**Comment by Adamant36** [comment]
Tobaccoland is printed on the vending machines. So it's still a brand/name in the sense that people are mentally associating the location (the vending machines) with the name Tobaccoland. So, I don't see how it's any different then a regular shop. The semantic difference between a shop brand and a vending machine brand is kind of thin to a point anyway. At least as far we are concerned here IMO. What's important is that the person has a way to associate what is displayed on the map (or what they are editing in iD Editor) with the real life object through branding. Which I think having Tobacooland as the name satisfies. 

![Tabaccoland](https://user-images.githubusercontent.com/30259065/82516193-015cfb00-9acf-11ea-92e9-4abfe4e32834.jpg)

**Comment by Lukas458** [comment]
I can see your point that people associate these vending machines with a brand, but not really with a name. Noone would say "I will go to Tobaccoland and buy some cigarettes". On many things the label of the brand or operator is printed, but if there is printed "National Bank" on an atm we also use operator (or maybe brand) for it, but not name. Furthermore, not on every vending machine "Tobaccoland" is printed so big. At some you do not see the brand from far away at all. But if that might crash the consistency of the entries in this index, I would rather prefer to remove the preset.

**Comment by bhousel** [comment]
@Lukas458 please check with your local community how they want it mapped and let us know what they say.  I'm happy to remove it, but I'd prefer for a bit more discussion to take place rather than just relying on one person who saw a thing that they didn't like.

A lot of your statements sound like - your personal opinions about mapping.  We've seen that many people do map these tobaccoland machines and other vending machines and ATMs by putting something in the name tag, and this a practice going back many years, and this style of mapping is how these features made it into this name-suggestion-index project in the first place.  I really don't see any harm in having a vending machine named "tobaccoland" or an ATM named "Citibank".

**Comment by natrius** [comment]
It is getting discussed in https://forum.openstreetmap.org/viewtopic.php?id=69486 FYI

My opinion:
Nah, that would be the operator=*

On an ATM i also tag the `operator=Sparkasse` or whatever and not a `name=Sparkasse` - it just doesn't get an name. Also, comparing to a postal-box in america USPS is used approximately 5.800 times with `operator=*` ( https://taginfo.openstreetmap.org/tags/operator=USPS ) and just 880 times with `name=*` ( https://taginfo.openstreetmap.org/tags/name=USPS )

And to your last comment @bhousel let me just quote https://wiki.openstreetmap.org/wiki/Key:name

> Names recorded in name=* tag are ones that are locally used, especially ones typically signposted.

Nobody is saying anywhere near i live "I'm going to the tobaccoland" is he just wants some ciggys. Its just "I'm going to the ciggy-vending-machine". Same, nobody is saying "I go and get some money at Citibank". They just say "I go and get some money at the atm" because nobody cares in this case how it is called. 

The operator on the other hand is an useful information for a lot of people who are getting data out of the OSM-Database. And thats the main-function, its a database.

**Comment by Adamant36** [comment]
> On an ATM i also tag the operator=Sparkasse or whatever and not a name=Sparkasse - it just doesn't get an name.

You and the people in the discussion are missing the point in @bhousel's other comment though that there has to be something in the name field for it to have an entry in the index. So, there is no option where we just have entry with either the operator or brand tags, but completely void of a name.

**Comment by bhousel** [comment]
Ok thanks @natrius and @Lukas458 for your comments.. I've removed it in 4c673e15
