### ISSUE TITLE
IT: Sella Bank / Banca Sella

### ISSUE THREAD

**Issue by fansanelli** [osmlab/name-suggestion-index#3967]
Hello,

I have a question about the preset in subject: are the English version of name and brand really necessary?
Do this bank exists abroad (not just as an office or group of banks) with the "Sella bank" name?
Is there a guideline to follow in this case?

Many thanks
Cheers
Francesco

**Comment by Adamant36** [comment]
It depends. Usually the English name is only needed for none Latin derived languages so we can tell what the entry is. In this case, it looks like there is or was a [Sella Bank](https://www.bloomberg.com/profile/company/4071492Z:SW) in Switzerland. Maybe the English name is because of or confusion with that. While it looks like there are none of this bank mapped in Switzerland it doesn't mean there wasn't or that there might not be in the future and it's hard to tell if they are the same company or not. Since the Bloomberg profile says their business "includes branches or agencies of foreign banks." 

Is there a particular problem with there being an English label? If so, maybe we can just create two different entries or get rid of the English altogether. Although, that might get in the way of people mapping non Italian branches if it turns out there are any. So, it really depends. Also, I know there's just a lot of anti-English sentiment lately and I don't feel like "English is evil" is a good enough reason alone to modify an entry. Although I have sympathy for where it's coming from.

**Comment by fansanelli** [comment]
Dear @Adamant36 

thanks for replying.
My only concern is about over-tagging a bank when is not needed and I think that if it doesn't exist an abroad counterpart we should get rid of the tags...
I'm not against the English name, but I am afraid that it doesn't reflect the reality.

Thanks
Francesco

**Comment by dieterdreist** [comment]
I have found an edit where the object had just 2 tags: name and amenity=bank. A well meaning mapper has added a lot of repetitive tags which IMHO hardly add anything to the object. They added name:it (in Italy), name:en (the Bank does not have an English name, it is a useless translation because you can find this translated name nowhere), a brand (same as name), a brand:it (again the same), a brand:en (with a typo, "Sandrio" instead of "Sondrio", again a translation like in the name), a "brand:wikidata", and a "brand:wikipedia" (a link to the English Wikipedia which indeed has the Italian name as title, as there isn't any English name). 
So to 2 useful tags, 7 derivatives have been added, with completely invented, non-existing English versions.
Generally, the translation of brands seems more harmful than good because someone who prefers the display of English-namespace tags will not find these on the ground (or in this case, anywhere else). There may for sure be cases where the same company uses different brands in different cultural / linguistic context, but otherwise it does not make sense.

https://www.openstreetmap.org/node/7090473329

**Comment by bhousel** [comment]
@Adamant36 it looks like you added these tags in e782cc72 - are you ok if I remove them for this Bank?

I think for now it's valuable to have the multilingual tags on the brands where we maintainers can't read the language (for example `"name": "日本銀行", "name:en": "Bank of Japan", "name:ja": "日本銀行"`) - and we can maybe avoid this after #3995 - but we don't really need transliterated names for Italian.

Many people have added localized names, and they are really useful in a place where multiple languages are spoken, but I think if a local mapper really wants them removed we should remove them.

**Comment by dieterdreist** [comment]
Transliterated brands may have a reason, translated brands don’t. A brand is a brand, if you see a brand you can recognize it, but if it’s translated you only recognize it well if you speak the language, as an English speaking person you would be better of with the Italian brand when you were looking for the bank, because the English version does not exist. Have a look at wikipedia:en, they do not translate the brands, it would be pointless.

**Comment by Adamant36** [comment]
Personally, I don't care if the English is removed. I had planned to do it myself after I researched if the bank in Switzerland was owned by the same company or not. I never got around to it though and it's not like another English entry can't be created if it is. 

I take issue with the insinuation that it was just an off the cuff random translation for no though when I said in my last comment that it was based on there being a Sella Bank. 

Also, it would be wrong IMO to treat Wikipedia pages as if they are somehow authoritative as to what a brand should be called or that people who create Wikipedia articles put more effort into the titles then just doing a basic search. Sometimes they do, but usually they don't. 

In my experience people on Wikipedia tend to go with whatever source or spelling fits their opinion of how things should be and it rarely has anything to do with reality. As an example, I was reported to the admins for vandalism once because I used the English name of an Italian bank in an English Wikipedia article, by someone who thought Bloomberg's usage of the brand name in Italian was more authoritative then the bank itself using an English spelling of their name in multiple places, including press releases. So, you can't just go off of Wikipedia.

**Comment by Adamant36** [comment]
I modified it in 6e565b8. It's worth mentioning that sometimes IMO it's better to go with the English Wikipedia article even if it's technically the "wrong" language because a lot of times articles in other languages unfortunately just aren't that developed. If it's between a stub article in the "native" language or a well developed one in English that web browser can translate anyway I much rather go with the well developed one. Although, that doesn't really apply here.

**Comment by fansanelli** [comment]
@Adamant36 thanks for your change. I would remove the "name:it" and "brand:it" too as the only language is Italian now...
About the Wikipedia tag I think will be deprecated with the wikidata growing, so I don't mind to swap the English with Italian ones.
Just to be clear, @dieterdreist wrote about a similar issue (Banca Di Sondrio): can we apply the same rule of translations vs transliteration and clean up the list of Italian banks? I could hack around it if you agree and nobody beats me on this.
Thanks
Cheers
Francesco

**Comment by dieterdreist** [comment]
I don’t understand why Italian bank brands have gotten translated, but for example German bank brands haven’t. There is (rightfully) no “German Bank” suggestion for “Deutsche Bank” and no “Popular Bank Berlin” for “Volksbank Berlin”. This is not about a single Italian bank, it is a systematic problem with Italian banks (and apparently Spanish banks as well).

**Comment by Adamant36** [comment]
> I don’t understand why Italian bank brands have gotten translated, but for example German bank brands haven’t. There is (rightfully) no “German Bank” suggestion for “Deutsche Bank” and no “Popular Bank Berlin” for “Volksbank Berlin”. This is not about a single Italian bank, it is a systematic problem with Italian banks (and apparently Spanish banks as well).

Some of that was due to ignorance on my part when I first contributed to the project back in like the end of 2018 when @bhousel first started asking people to contribute and there was no guidance on at that point. There was like a couple of thousand issues that I was trying to go through quickly though so they would just be done with and that's how I choose to it. Because again, there wasn't saying not to at point and @bhousel never said anything about it. I did stop doing it and removed some when it did became something we decided not to do anymore. I don't think any English translation, transliterations, or whatevers have been added since then though. At least not in any meaningful or intentional manor. Except for maybe with entries that are none Latin. 

Also, it wasn't mainly done to Italian or Spanish entries because of some particular thing against them. Just that those where the languages that there was open issues for. If I remember correctly there wasn't that many entries or issues open for German banks. Except for Sparkasse banks and the  German community decided early on that they didn't want them having entries in the NSI. So we never really dealt with them, to add English or otherwise. Also, if I remember correctly at least the Spanish entries some of them were originally in English and I added a bunch of Spanish translations to them. So, it wasn't like it was only a one way attempt to push English on Latin America or anything. I had planned to remove the English entries myself at some point and add more localized Wikipedia links, but I just never had the time. Anyone could have (and did) open issues or PRs to have the English removed in the meantime though. That's it and there's nothing more to read into it. 

Anyway, @fansanelli your welcome. I guess I could have removed the it entries also, but I didn't think about it. I will at some point though if no one else does. I've never been to solid on the Wikipedia links myself. I could see benefits to keeping them or depreciating them. I it's kind of wash if they should be included or not at this point. No one seems super into them, but then there isn't really a will with anyone to remove them completely either. Although, they are sort of obsolete with Wikidata, but it doesn't make me want to go toward the side of depreciating them 🤷 

If you want to go through the Italian banks and delete the English go for it. I don't really care at this point. Like I said, English was only added originally because there wasn't a guideline about it when it was added. It's not super important to keep the English though. I appreciate being asked if I mind it being removed though 👍 

I'd just add the caveat to maybe check first to make sure the companies don't use English somewhere in their branding before you remove it. In cases where they do we can always create separate English only entries, but there's a lot less chance of that happening if they aren't double checked.

**Comment by Adamant36** [comment]
BTW, I also seem to remember that at one point there was an issue where some QA tool would throw up an error if there was an entry like name=whatever + name:it=whatever without there also being name:en=whatever. If I'm remembering correctly some of the English tags were added because of that.

**Comment by dieterdreist** [comment]
sent from a phone

> On 23. Jun 2020, at 10:29, Adamant36 <notifications@github.com> wrote:
> 
> Although, they are sort of obsolete with Wikidata, but it doesn't make me want to go toward the side of depreciating them 🤷


AFAIK there was not a clear decision about wikidata and wikipedia WRT one of them being redundant (which they may well be in general), but as you can get a wikidata item for any wikipedia article automatically, and wikipedia values are human readable, one could argue as well to remove wikidata tags as less appropriate for OpenStreetMap.
FWIW, it seems less desirable to automatically add any of these, as manually added items could help to find inconsistencies, while duplication without double checking will not help for this and only make these things apparently consistent but not actually better

**Comment by Adamant36** [comment]
> FWIW, it seems less desirable to automatically add any of these, as manually added items could help to find inconsistencies, while duplication without double checking will not help for this and only make these things apparently consistent but not actually better

IMO "better" is highly subjective and dependent on where in the world your talking about. Especially when the equation is between something done manually versus being automated. Nothing is completely error proof, but in my experience less errors are created by these things being automated (even with issues like this) then there would be if this was done manually. If it ever would be done manually in the first place. 

My bet is that way less people would be willing to enter all this data on their own then they are to click an "upgrade tag" button. Otherwise, there wouldn't be a point in even having this. Also, a main benefit of iD Editor is so people don't have to deal with the nuances of tags. Which automating these things fits in with. Most users don't want (or know how) to deal with tags at all. Let alone do they want to enter tags repeatedly in an extremely repetitive manor like they would have to do if this wasn't automated. 

I don't think it would be good to take a "if people aren't entering it on their own then it's not worth having in OSM" approach to this either because it's more about standardizing things like the name tag then it is anything else. So, the data is already there. It's completely scattered and barely usable. I just got done "upgrading" a bunch of U-Haul places in the US and it was ridiculous how many different names and tags people were using. IMO them being uniform in tagging now out weighs the few errors I might introduced by automating it. 

The equation might be different in somewhere like Europe where there is a more robust community and the map is already well developed though. I could see where this process might reach a point of diminishing returns. Especially with one slip up in a PR possibly having a huge effect on brands that were already correctly tagged, but I don't think that reflects on the process as whole though. Maybe there should be a standard where if a certain percent of a brands locations are mapped and upgraded that the entry is removed or something so errors won't accidentally introduced after the fact. When the NSI is no longer useful to improving that brand anymore.

**Comment by Adamant36** [comment]
> Maybe there should be a standard where if a certain percent of a brands locations are mapped and upgraded that the entry is removed or something. That way errors won't accidentally be introduced when the NSI isn't important to improving the brand anymore.

One possibility might be to use the location conflation tool to exclude locations where the brands tagging is already "upgraded."

**Comment by dieterdreist** [comment]
sent from a phone

> On 23. Jun 2020, at 12:10, Adamant36 <notifications@github.com> wrote:
> 
> because it's more about standardizing things like the name tag then it is anything else.


names are a highly sensitive topic and should be changed only by people knowing the situation on the ground and the language. The case I have given as an example is a good example how an error (typo in english name/brand) gets multiplied by automatic tagging.
There are now 2x18 https://taginfo.openstreetmap.org/search?q=Popular+Bank+of+Sandrio#values

Last year I have fixed hundreds of craft=sculpter which have been used partly for craft=sculptor but more often for tourism=artwork and artwork:type=sculpture . They had been lingering there for years.

brands are slightly different to names, as names are what people refer to things while brands are about how the things advertise themselves. For names transliterations can make sense, for brands not

**Comment by Adamant36** [comment]
>Names are a highly sensitive topic and should be changed only by people knowing the situation on the ground and the language. 

I'd love to see some data about if people on the ground, or who speak the language, makes less mistakes then a preset does. I just don't think that data exists though. I know it's something that sounds true intuitively, but a lot of things that are wrong (or at least not very sound) do. There are POIs all over the place that have wrong names added to them by locals, who really should have known better. To look at this fairly you have to put away the mythical Utopian ideal of virtuous local mappers that never make mistakes. The question should be does  the NSI improve things more then it harms them. Otherwise, your just working backwards from your own conclusions, whatever they are.  

Personally, I spent the last week using the NSI upgrading 600 U-Haul places mapped by locals that had all kinds of problems. Including with the names. So, is my positive experience with the NSI and negative one with local mappers more important or is your negative one with the NSI and positive with locals mappers? I'd say neither, because neither is based on a complete picture and just confirms our own opinions. Mine that the NSI is good and yours that it isn't. Although 600 objects being improved compared to 32 not being is just intrinsically better IMO. 

I also don't think names are that super special like you make them out to be. Maybe in the long-term and in large amounts, but not in the short term with smaller numbers like 18 when your talking about something like a bank with 154 locations. Not to say it isn't important to correct the miss-spelled ones, but it's fundamentally flowed to suggest throwing out the whole system over it. More so because it's only been 18 or less out of 154 total that were miss-tagged due to the NSI since 2018 and no one has even opened an issue about it. So it appears it never became that much of a problem or one big enough to get on anyone's radar. If it had of though, we would have fixed it when someone requested and I probably would have helped with the re-tagging. That can't be said about those 600 people that tagged those U-Haul places wrongly though. Good luck getting any of them to correct their errors.

**Comment by dieterdreist** [comment]
sent from a phone

> On 23. Jun 2020, at 14:02, Adamant36 <notifications@github.com> wrote:
> 
> To look at this fairly you have to put away the mythical Utopian ideal of virtuous local mappers that never make mistakes.


of course the local mappers make mistakes, individual mistakes, not systematic mistakes.

**Comment by bhousel** [comment]
Good morning - just would like to remind everyone to keep your comments concise, leave actionable feedback, avoid strong opinions about tagging, and assume good intent.  This thread feels like it's gone off topic, and I can't really follow it.

I'll remove some of the translated names for the Italian POIs and close this issue.

**Comment by fansanelli** [comment]
@bhousel I had a similar patch, for Italy everything seems fine. Thanks.
