### ISSUE TITLE
Add brand: WIND mobile phone stores in Greece

### ISSUE THREAD

**Issue by sucrerouge123** [osmlab/name-suggestion-index#4009]
Hi!

I would like to request the addition of Wind mobile telecommunications chain stores in Greece.

shop:mobile_phone
name:WIND
brand:WIND Hellas
brand:wikidata:Q10711016
brand:wikipedia=el:WIND Hellas
country codes:gr

Thanks!

**Comment by sucrerouge123** [comment]
Please add the tag:

website=https://www.wind.gr

Thanks!

**Comment by bhousel** [comment]
> Please add the tag:
> 
> website=https://www.wind.gr

Thanks for the suggestion but we don't actually add `website` tags in this index.. 

OSM convention is that:
- tags like `website` and `contact:website` should be for a website for _that specific POI's branch location_, and
- tags like `brand:website` or `operator:website` are for the overall brand or operator - however these tags have fallen out of favor because this information can just be fetched more accurately from that brand or operator's Wikidata page.

**Comment by sucrerouge123** [comment]
Thanks!
