### ISSUE TITLE
Update https://github.com/osmlab/name-suggestion-index/releases to a newer version

### ISSUE THREAD

**Issue by MASangys** [osmlab/name-suggestion-index#4040]
FYI, the iD editor just updated yesterday, seehttps://twitter.com/quincylvania/status/1285613343093424129. I am glad to see more improvement on this toll. But sadly, the NSI idex still same as the older version, so that means at lease 100 brands that had added recently cannot be utilise, unless the new release was out.  so I really hope that @bhousel or other person that manage to create a release to update the release to a new version. So that this will ease iD mappers more. Thank you very much for working for this project.

**Comment by bhousel** [comment]
> FYI, the iD editor just updated yesterday, seehttps://twitter.com/quincylvania/status/1285613343093424129. I am glad to see more improvement on this toll. But sadly, the NSI idex still same as the older version, so that means at lease 100 brands that had added recently cannot be utilise, unless the new release was out. so I really hope that @bhousel or other person that manage to create a release to update the release to a new version. So that this will ease iD mappers more. Thank you very much for working for this project.

iD still requires the presets to be built by the `build_data` script and saved to the `dist/` folder - so @quincylvania's tweet about the latest brand presets is a bit inaccurate.  They are still bundling v4.0.2 presets, and probably will for a while.

The next release of NSI will be a major bump v5 because the switch from countryCodes to locationSets is a major change.

**Comment by quincylvania** [comment]
> iD still requires the presets to be built by the build_data script and saved to the dist/ folder - so @quincylvania's tweet about the latest brand presets is a bit inaccurate. 

Oh whoops, I made an incorrect assumption here. Apologies!

**Comment by bhousel** [comment]
> Oh whoops, I made an incorrect assumption here. Apologies!

It's alright - we'll get there eventually.  The original plan was to spin off the presets after the imagery, and you know how that went.

**Comment by MASangys** [comment]
> > Oh whoops, I made an incorrect assumption here. Apologies!
> 
> It's alright - we'll get there eventually. The original plan was to spin off the presets after the imagery, and you know how that went.

So may I know when is the exact date that iD got this latest NSI update? I just hope that it can be done ASAP as I will become buzy in August, and surely now got more times to rearrange the label tag via the iD editor. Anyway, your work are much appreciate

**Comment by bhousel** [comment]
> So may I know when is the exact date that iD got this latest NSI update?

We publish versions of this NPM and iD pulls automatically the most recent compatible one.  It looks like 4.0.2 is 3 months old.
https://www.npmjs.com/package/name-suggestion-index

I can't give you an exact date when the next release will happen because that will depend on things like how much time it takes to implement things, and whether I have the time.  The schedule for iD is even more up in the air.  My primary focus is on RapiD going forward, so we may see updates arrive in that editor sooner.
