### ISSUE TITLE
Tenpin bowling brand

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#4096]
I was going to open an issue to add the UK bowling alley brand "tenpin", but I saw it had already been added by @UKChris-osm https://github.com/osmlab/name-suggestion-index/commit/f56f189e50684b10f6def4015ca28ac97836c09b

However, I noticed that Tenpin's name/brand are lower case - looking at overpass-turbo it's only tagged once as **tenpin**, whilst there are 17 occurrences of **Tenpin**. Any chance the name could be changed to capitalise the first letter?

P.S. how often does the NSI get updated in iD? As the tenpin brand was added in May but it's not yet in iD.

**Comment by Adamant36** [comment]
> I think capitalising names is something people do by default, as it's such a common thing

Plus it's just weird not  to. I really wonder what some brands are thinking with how their names are.

> others may disagree with my selection of all lowercase.

Whatever people's opinions are the best thing to do is to go with what's on the signs. Which it seems like you did here. 

> I don't think the Index is going to be updated into iD for a little while

It would be cool if the update came after Hacktober. Since we tend to get a lot of PRs during that time. Especially since I plan to open a bunch of "Good first issue" issues at some point between now and then to take advantage of it. 

Also, I'm going to close this since it seems resolved. If it's not though, feel free to re-open it.
