### ISSUE TITLE
FR: Add Emmaüs (charity)

### ISSUE THREAD

**Issue by gendy54** [osmlab/name-suggestion-index#4136]
Hello,

Country code: FR (only)

"shop":"charity"
"second_hand":"yes"
"operator":"Mouvement Emmaüs"
"operator:wikidata":"Q989437"
"operator:wikipedia":"fr:Mouvement Emmaüs"

I deliberately changed "brand" to "operator".

**Comment by UKChris-osm** [comment]
> I deliberately changed "brand" to "operator".

Why so?

**Comment by Adamant36** [comment]
> I deliberately changed "brand" to "operator".

We're only doing brand:* at this point. The operator tag was intentionally removed awhile back because it wasn't really clear.

**Comment by gendy54** [comment]
Because Emmaus is an association. So the brand tag doesn't seem at all appropriate to me.

**Comment by bhousel** [comment]
Hey @gendy54 - OpenStreetMap convention is to use the `operator` tag for the company, corporation, person or any other entity who is directly in charge of the current operation of a single location.. People have been confused by this, so we don't add them right now.  See https://wiki.openstreetmap.org/wiki/Key:operator for more info, also these old issues.

#2471   
#2736
#2816

If these are storefronts with common signage or logo, `brand` is ok.

**Comment by pyrog** [comment]
Hi Brian,

Just an explanation from this side of the Atlantic 😃 

Brand mean (profit) company, GAFAM…
Emmaüs is a non profit, a charity association.

So at least french couldn't use brand 😅

**Comment by bhousel** [comment]
@pyrog You can see from here that there are quite a lot of charity shops, blood banks, social facilities, (on both sides of the Atlantic) using the `brand` tag in this way:  
https://nsi.guide/index.html?t=brands&k=shop&v=charity
https://nsi.guide/index.html?t=brands&k=healthcare&v=blood_donation
https://nsi.guide/index.html?t=brands&k=amenity&v=social_centre

Brand really doesn't mean "for profit company". 

I'd strongly encourage the French community to try to do what everyone else in OSM does, but if the `brand` tag really bothers you, we can use `operator` now.  

(For a long time we didn't include `operator` tags here because many contributors were misusing it, but it is allowed now).

**Comment by gendy54** [comment]
If the tag `operator `is accepted, that's fine. Honestly, no French person will put a tag `brand `on structures carried by non-commercial entities: associations, foundations, public services,... It's counter-intuitive.

**Comment by Adamant36** [comment]
> no French person will put a tag brand on structures carried by non-commercial entities: associations, foundations, public services,... It's counter-intuitive.

How is something like a bus company not a brand just because its a public service? I know where I live that the local bus network, Butte Regional Transit, is branded "B-Line." Its on the sides of their website, sides of buses, stickers, mugs, bus passes, people refer to it as that etc etc. They are operated by Veolia Transport though (ironically a French company btw who seems to be fine with the whole arrangement and doesn't seem to think the bus service should just be refered to as "Veolia Transport"). No one calls it "Veolia Transport bus line" either. The fact that its a "public service" is a distinction without a purpose and there would be zero counter-intuitive about using the brand=B-Line tag on the bus line. There's clearly a difference between the brand, "B-Line", and the operator, "Veolia Transport." Sure there are examples out there where the "operator" and "brand" are likely the same thing, maybe Transports Bordeaux Métropole/TBM for a French example, but then either tag or both would be fine IMO. Personally, id just go with brand and leave out operator or use both. TBM isnt any less a "brand" just because its the name of an operations company though (if it even is). Since its still on the sides of trains etc etc. Otherwise your way over thinking this.

**Comment by peternewman** [comment]
FYI the shop=charity wiki page does explicitly mention operator, rather than brand, I assume we're happy to ignore that for now?:
https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcharity
