### ISSUE TITLE
Jewson needs changing from shop=doityourself to shop=trade

### ISSUE THREAD

**Issue by lakedistrictOSM** [osmlab/name-suggestion-index#4140]
Q6190226

The chain is aimed at builders, rather than regular DIY customers.

**Comment by UKChris-osm** [comment]
Would you say [Travis Perkin](https://nsi.guide/index.html?k=shop&v=doityourself#Travis%20Perkins) should also be listed as trade??

**Comment by peternewman** [comment]
From:
https://www.travisperkins.co.uk/content/faqs

> Q1 - I'm new to Travis Perkins. Do you only supply to the Trade? And do I need to have an account to buy from you?
> Anyone can buy from Travis Perkins and you don't need to open an account.

I can't find something so clear cut with Jewson:
https://forums.moneysavingexpert.com/discussion/5063042/buying-from-trade-only-shops

They may be aimed at trade more so than B&Q say, I'd say that's probably true of both.

According to that MSE forum, Howdens is trade only.

**Comment by matkoniecz** [comment]
https://en.wikipedia.org/wiki/Jewson 

> Jewson is one of the largest chains of British general builders' merchants, selling to small and medium building contractors.

On the other hand https://www.jewson.co.uk/tools-fixings/hand-tools lists things that would perfectly fit DIY...

**Comment by peternewman** [comment]
> On the other hand https://www.jewson.co.uk/tools-fixings/hand-tools lists things that would perfectly fit DIY...

Erm yes, because the building trade is basically paid DIY, or vice-versa.

> I asked on talk-gb for more feedback.

I'd suggest it's a more general issue. From the wiki:
"A place of business that sells to a particular trade or trades, but normally also retails to normal consumers."

Then you're supposed to use trade=* to distinguish which trade it sells to. trade=building_supplies in this case.

Then later relative to DIY:
"TODO: document how to distinguish"

To me, this is a bit of a messy tagging scheme, unless it ONLY sells to people with a trade account (e.g. proof of trade employment), then if I want to buy some paint or wood, I just want the nearest store selling them, I may even favour the trade supplier as they may be cheaper. Perhaps if I'm at the more naive end of things, I might go to a DIY store to ask advice, although that can be mixed (but I think it's generally better there then in Maplins (as was)/Currys/PC World etc).

**Comment by peternewman** [comment]
See also #4190
