### ISSUE TITLE
FR: Add Établissement français du sang (blood_donation)

### ISSUE THREAD

**Issue by gendy54** [osmlab/name-suggestion-index#4155]
Hello,

Country code: FR (only)

"brand":"Établissement français du sang"
"brand:wikidata":"Q3591543"
"brand:wikipedia":"fr:Établissement français du sang"
"donation:compensation":"no"
"healthcare":"blood_donation"
"operator:type":"public"
"name":"Établissement français du sang"
"short_name":"EFS"

**Comment by Adamant36** [comment]
Just a minor thing, but it's better to go with EFS for the name and use the official_name tag for Établissement français du sang. Since EFS is used 4 times more and it's always better to go with the shorter thing for the name when we can anyway. Also, as you should already know from #4136 we don't do the operator tag. So it would probably be a safe bet to assume we aren't going to add operator:type either.

**Comment by modaserMoj** [comment]
Is this still open? if it is the only change recommended is to use the official_name tag instead of name tag?

**Comment by gendy54** [comment]
In this case, you can actually remove operator:type

**Comment by bhousel** [comment]
ah yeah this was done in #4217 

> In this case, you can actually remove operator:type.
> concerning the name, one can indeed take name=EFS and official_name=French Blood Establishment instead of name=French Blood Establishment and short_name=EFS

Sounds good, I made these changes in b186d810
