### ISSUE TITLE
Hacktoberfest challenge - name-suggestion-index has transit now!

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#4231]
Happy Hacktober! 👻 

The past few days I've been updating the core code to add another "tree" to the name-suggestion-index project for **transit**.  I've collected frequently-occuring `network` tag values on for several route features, and we're going to canonicalize all the transit networks in OpenStreetMap to be linked to a `network:wikidata` tag.

🚄  Check out the transit networks of OpenStreetMap here:  https://nsi.guide/index.html?t=transit

This is going to be **a lot** of work, so I'll be opening **a lot** of research tickets looking for volunteers to go through the lists and figure out the wikidata identifier for each transit network, and update the locationSet to say which country they operate in.  You can even now draw a GeoJSON around the bounds of where the transit network operates, if you want to be even more helpful!.  Also, make sure those wikidata pages are updated with the transit company's social media information, so we can fetch those sweet logos. 

If you haven't already, sign up for Hacktoberfest here - https://hacktoberfest.digitalocean.com/
👕 Make 4 pull requests during the month of October and you will receive a free t-shirt (or you have the option to plant a tree if you already have enough t-shirts  )

_Important: If you don't want to receive a LOT of email about the name-suggestion-index project - you should unsubscribe now for a few days at least!_

**Comment by 3Hearts** [comment]
Looking to cut my teeth on some work this month and happy to assist with this.

**Comment by camelCaseNick** [comment]
>  You can even now draw a GeoJSON around the bounds of where the transit network operates [...]

Is it possible to extract it from OSM's boundary=public_transport? [Taginfo says, we have 263.](https://taginfo.openstreetmap.org/tags/boundary=public_transport)

**Comment by bhousel** [comment]
> Is it possible to extract it from OSM's boundary=public_transport? Taginfo says, we have 263.

Interesting! I’ll look into it.. boundaries in OSM are often waaaay more complex than what we want for our needs (a fast point-in-polygon test to answer questions like “do MTA bus stops belong here?”)

In every situation I’ve needed a polygon, it’s a lot faster for me to just go to http://geojson.io and draw it myself - again keeping the point count as low as possible.

**Comment by peternewman** [comment]
Cool, a few questions/thoughts.

While I'm not just here for a free T-shirt (as hopefully my history shows: https://github.com/osmlab/name-suggestion-index/pulls?q=is%3Apr+author%3Apeternewman ), currently no-one will get them:
`Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.`

More on topic:

From #4260 
> I'm assuming you only want proper networks of these, not point to point ones like this:
> https://en.wikipedia.org/wiki/Emirates_Air_Line_(cable_car)

I guess likewise for other transit, how many stops does it need to have to be a network/operator?

How does bicycle rental fit into transit, or does it?
https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/bicycle_rental.json

UK Network Rail
In the UK there is a company owns the tracks and most of the stations:
https://en.wikipedia.org/wiki/Network_Rail

But the stations are often operated by one of the operators who stops there:
https://en.wikipedia.org/wiki/Network_Rail#Stations

UK National Rail
This seems to be down as the network at a lot of stations (e.g. London Euston), i.e. OSM doesn't care which operator is running it, the whole mainline network is one network.

So this means you've got:
The country operator (Network Rail) which runs some stations, but isn't really a network.
A virtual network (National Rail) which isn't an operator
Some stations may have other networks too (e.g. London Overground) in a semicolon separated list
Stations will have (I think only one) operator, which won't have the network (as it's virtual).

I think the right of this table is a full list:
https://en.wikipedia.org/wiki/Train_operating_company#Current_operators

At least one company has two brands running different sets of services:
https://en.wikipedia.org/wiki/West_Midlands_Trains#Branding

The national booking site still refers to the former Train Operating Company who ran this route in some places (LM=London Midland):
https://www.nationalrail.co.uk/tocs_maps/tocs/LM.aspx

CC @UKChris-osm

**Comment by UKChris-osm** [comment]
> While I'm not just here for a free T-shirt, currently no-one will get them:
> `Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.`

Where did you see this? The only place I saw it was under the "legend" text, which I think is just there to be informative, and not specifically about the NSI project.

> I'm assuming you only want proper networks of these, not point to point ones like this:
> https://en.wikipedia.org/wiki/Emirates_Air_Line_(cable_car)

I can't answer this for certain, but I expect you are right, as the Emirates Air Line is just a single route with two points (and unlikely to expand), and doesn't need to be in the NSI - similar to how a brand with only two shops wouldn't be needed.

> I guess likewise for other transit, how many stops does it need to have to be a network/operator?

Again, I don't have a definitive answer, but I did add a PR for West Somerset Railway, which has 11 stations and a 22 miles of track, which isn't that big, but I felt big enough to be included. Perhaps if you have a smallish network to suggest, consider if you're going to add all the points to the map yourself? If you are, then maybe it doesn't need to be included in the NSI (as you're planning on added the data anyway) but if you're not planning on mapping the whole network, then submit a PR and see if it's accepted, allowing others to map it a little easier.

> How does bicycle rental fit into transit, or does it?
> https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/bicycle_rental.json

I would have thought bicycle rental could remain as it is, outside of transit, as there isn't necessarily a network route to add, as people can cycle anywhere, but I could be mistaken.

I'm not to sure how best to go with the British Railway system. To me, the network would be the stations and routes of, say, Great Western Railways (GWR) or CrossCountry, rather than Network Rail itself. However, I think these tags would be set as transit "relations" rather than on the actual track or station nodes / ways.

Transit is still pretty new to me, so I'm learning at the moment as well :)

**Comment by peternewman** [comment]
> > While I'm not just here for a free T-shirt, currently no-one will get them:
> > `Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.`
> 
> Where did you see this? The only place I saw it was under the "legend" text, which I think is just there to be informative, and not specifically about the NSI project.

In my profile for it, also all over the tech news and here:
https://hacktoberfest.digitalocean.com/hacktoberfest-update

You got through on grandfather rights so you're okay:
> We will honor all valid pull requests prior to this change, and as of October 3, 2020 at 12:00:00 UTC – and October 3 in all time zones

Sorry I was mostly CCing you regarding the UK rail network @UKChris-osm but thanks for the input.

> I can't answer this for certain, but I expect you are right, as the Emirates Air Line is just a single route with two points (and unlikely to expand), and doesn't need to be in the NSI - similar to how a brand with only two shops wouldn't be needed.
> 
> > I guess likewise for other transit, how many stops does it need to have to be a network/operator?
> 
> Again, I don't have a definitive answer, but I did add a PR for West Somerset Railway, which has 11 stations and a 22 miles of track, which isn't that big, but I felt big enough to be included. Perhaps if you have a smallish network to suggest, consider if you're going to add all the points to the map yourself? If you are, then maybe it doesn't need to be included in the NSI (as you're planning on added the data anyway) but if you're not planning on mapping the whole network, then submit a PR and see if it's accepted, allowing others to map it a little easier.

Although you do get some pretty icons too, but perhaps they're mostly via wikidata rather than anything actually needing to exist here? I guess it was a bit of an indirect question for @bhousel perhaps to put in the readme? Should it differ between brands and railways too, it's a lot cheaper and easier to expand a shop than a transit system!

> > How does bicycle rental fit into transit, or does it?
> > https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/bicycle_rental.json
> 
> I would have thought bicycle rental could remain as it is, outside of transit, as there isn't necessarily a network route to add, as people can cycle anywhere, but I could be mistaken.

Yeah I was slightly being pedantic about whether it should it live in transit, the London bike hire has network tagged as TfL cycle and then operator populated too. I guess the logic being for the docked bikes, you still need to "get off" the network at a dock to return the bike.

> I'm not to sure how best to go with the British Railway system. To me, the network would be the stations and routes of, say, Great Western Railways (GWR) or CrossCountry, rather than Network Rail itself. However, I think these tags would be set as transit "relations" rather than on the actual track or station nodes / ways.

I wonder if the UK is rather unique in that regard? I guess the track could be tagged as network=National Rail and operator=Network Rail, then the relations tagged appropriately, although from my quick look that's not how it's currently done. If the station is managed by GWR, then presumably they should be the "operator" of it, e.g. who you'd complain to about it.

Certainly at the moment on OSM, and in the real world, there are trains from multiple lines/routes running on the same bits of track.

> Transit is still pretty new to me, so I'm learning at the moment as well :)

Heh, yeah I guess we all are.

**Comment by UKChris-osm** [comment]
I've had a look at the [hacktoberfest web site](https://hacktoberfest.digitalocean.com/hacktoberfest-update) and added a topic tag to the Name Suggestion Index, not sure if there is anything else that needs doing to achieve validity on our side?

I look at Network Rail track in the same way as I would Highways England roads, in that they they own and maintain the physical network, and operate them (railway signals, road closures, etc) but virtual networks exists on top (train routes, bus & coach routes, etc) which is why I think the track itself would be better tagged as Network Rail as network and operator, with relations probably being the way to go for many transit entries, as you can attach multiple relations to a road / track.

Train Stations I would think best tagged as Network Rail for the network, and like you say operator as the railway company that operates it, like GWR, for example. Then the route relations for each railway service that uses the station would take care of the rest.

**Comment by peternewman** [comment]
> I've had a look at the [hacktoberfest web site](https://hacktoberfest.digitalocean.com/hacktoberfest-update) and added a topic tag to the Name Suggestion Index, not sure if there is anything else that needs doing to achieve validity on our side?

Yeah that's done the trick for mine thanks, they're now just saying they're waiting merging/review as I'd expect.

> I look at Network Rail track in the same way as I would Highways England roads, in that they they own and maintain the physical network, and operate them (railway signals, road closures, etc) but virtual networks exists on top (train routes, bus & coach routes, etc) which is why I think the track itself would be better tagged as Network Rail as network and operator, with relations probably being the way to go for many transit entries, as you can attach multiple relations to a road / track.

Yeah that seems sense if you can get everyone to change. :laughing: 

> Train Stations I would think best tagged as Network Rail for the network, and like you say operator as the railway company that operates it, like GWR, for example. Then the route relations for each railway service that uses the station would take care of the rest.

Not **National** Rail, that sort of looks more relevant here to me:
https://en.wikipedia.org/wiki/National_Rail#National_Rail_and_Network_Rail

I guess relations would also deal with stations where services don't stop at, but pass through, like Avanti West Coast and some of the slower stations.

**Comment by TheDynamicPunk** [comment]
> > I've had a look at the [hacktoberfest web site](https://hacktoberfest.digitalocean.com/hacktoberfest-update) and added a topic tag to the Name Suggestion Index, not sure if there is anything else that needs doing to achieve validity on our side?
> 
> Yeah that's done the trick for mine thanks, they're now just saying they're waiting merging/review as I'd expect.

Hey @peternewman, Just wanted to know if your merged PRs are still in review in Hacktoberfest website? Cuz mine are still stuck in Review even though they are already merged? What can I do?

**Comment by bhousel** [comment]
> Just wanted to know if your merged PRs are still in review in Hacktoberfest website? Cuz mine are still stuck in Review even though they are already merged? What can I do? This is what it's saying in my profile

Yes my profile shows a similar thing.  It looks like the review period lasts up to 14 days.  As long as the PR is merged by us, it will eventually be accepted for credit.

**Comment by TheDynamicPunk** [comment]
The thing I'm concerned about is if it's for everyone or is it something because I or we in this repo are doing wrong, which is keeping us from qualifying. I'm concerned not because I won't get a T-shirt but mainly because it'll hurt to be notified after 14 days that our PRs might not count due to some issues. I hope Digital Ocean provides some update to make this clear 😅

**Comment by Identitaet** [comment]
```
to get a prize, you must make four eligible pull requests (PRs) between October 1–31 in any time zone.

Pull requests prior to the rule change on October 3, 2020 at 12:00:00 UTC can be to any public repository on GitHub, not just the ones highlighted.

Pull requests following the rule change must be to a participating public repository on GitHub, and have been merged, labelled as hacktoberfest-accepted, or approved.

Pull requests labelled as hacktoberfest-accepted will count toward to Hacktoberest from any public repository on GitHub, with or without the hacktoberfest topic.

The pull request must contain commits you made yourself. If a maintainer reports your pull request as spam, it will not be counted toward your participation in Hacktoberfest. If a maintainer reports behavior that’s not in line with the values of Hacktoberfest or the project’s code of conduct, you will be ineligible to participate. This year, the first 70,000 participants can earn a T-shirt or plant a tree.

To put it in terms that some folks will more easily understand:
```

and for that also changed the time for a pr to be counted to 14 days

**Comment by Identitaet** [comment]
basically they changed the rules on the 3rd october

**Comment by peternewman** [comment]
> Yes my profile shows a similar thing. It looks like the review period lasts up to 14 days. As long as the PR is merged by us, it will eventually be accepted for credit.

I was going to suggest @bhousel tried tagging one of their PRs, but looking at their code it doesn't make a difference, you just have to wait 14 days for them to become eligible currently, even if they've been merged. I think if @bhousel was feeling really mean he could retrospectively tag them as invalid before the 14 day window expires if we haven't kept updating transit for the rest of October! :imp: :rofl:

**Comment by TheDynamicPunk** [comment]
Lol. Yeah maybe, but it seems like nothing much we can do, so it's a suspense if I'll even be eligible or not 😅 

By the way I was thinking of continuing this conversation (regarding Hacktoberfest) in it's own separate issue so as not to pollute this issue further. Should I create a separate issue where we all can talk Hacktoberfest or share any updates? @bhousel @peternewman

**Comment by Adamant36** [comment]
Hey now, there's nothing wrong with getting a free T-shirt. I got a cool purple one and some stickers a few Hacktoberfests ago. I signed up for it last year as a calibrator to see if I could score another one, but unknown to me at the time they don't count merging other people's PRs 🤦‍♂️ Anyway, the time it worked it took them like a month to register the PRs and send me the shirt. So I wouldn't expect them to do either any time soon. I think they have like 7 thousand people singed up for it this year. Or it might have been 70 thousand, but that seems high. Either way though. There's no point in being impatient or worrying about it. They will get to it when they can. I say that assomeone who thought they forgot about me the first time I did it to.

**Comment by TheDynamicPunk** [comment]
Hey @Adamant36, Sorry for sounding a bit impatient, it's just that it's my first time and I really appreciate someone like you with prior experience sharing your experience with us... Thanks! Happy hacktober everyone!

**Comment by bhousel** [comment]
Yeah I'm not worried - it's only October 6th.

If in 14ish days the contributions don't start showing up as accepted on people's profiles, I will add the label to all the old accepted PRs.  I just don't want to do it now because it makes a bunch of extra work for us.

**Comment by UKChris-osm** [comment]
Just as an update, I have seen some PR's of mine are now marked as competed, so anybody submitting a PR here should be fine as well :)

**Comment by TheDynamicPunk** [comment]
My 4 pull requests are shown as complete with one of them maturing in front of my eyes 😉. Thanks everyone, for this opportunity and helping me feel welcome to this project. I'm proud to say my real open source journey began through this project!

Happy hacktober!

**Comment by bhousel** [comment]
> I'm proud to say my real open source journey began through this project!

Great! We are happy to have you helping us out  🙇

**Comment by UKChris-osm** [comment]
Thank you to everybody who contributed in October, don't forget to claim your t-shirt if you submitted 4 qualifying PR's 🥇
