### ISSUE TITLE
`npm run wikidata` is adding duplicate P8253 Name-Suggestion-Index Identifier claim values

### ISSUE THREAD

**Issue by Robot8A** [osmlab/name-suggestion-index#4436]
See https://www.wikidata.org/w/index.php?title=Q98456614&action=history

**Comment by bhousel** [comment]
Yes, that is what the script does.. Why do you want to remove it?

**Comment by bhousel** [comment]
Oh sorry, I realize now what you mean.  It's adding duplicates and it shouldn't do that.

**Comment by Identitaet** [comment]
So looking around it seems to only be a problem for this item (as far as I did look at least)

**Comment by peternewman** [comment]
It's not because there are two entries for the `brand:wikidata` is it:
https://nsi.guide/?t=brands&k=shop&v=confectionery&tt=Q98456614

But both linking to the same item, compared to e.g. Tesco, which have that, but not in the same category:
https://nsi.guide/index.html?t=brands&k=shop&v=convenience&tt=tesco

Nope, because M&S does that properly:
https://nsi.guide/index.html?t=brands&k=shop&v=department_store&tt=marks

Although that is the only one I can quickly find with brand and category matching identically.

**Comment by bhousel** [comment]
The issue seems to be caused by this line:
https://github.com/osmlab/name-suggestion-index/blob/56b287fbaec00c3d8c1d0eb02abb733cee51c04a/scripts/build_wikidata.js#L365-L366
Where we fetch all the existing P8253, the "simplify" part is oversimplifying them and only returning the first one. 😆

**Comment by bhousel** [comment]
Turns out that `simplify` was only returning one because the first one has a "preferred" rank.  This makes sense!
The fix is to pass the `keepNonTruthy: true` option, to ensure we get all the claims...

<img width="948" alt="Screen Shot 2020-10-10 at 11 20 46 PM" src="https://user-images.githubusercontent.com/38784/95669753-f70ccd80-0b51-11eb-85ab-65c78f647bc3.png">

**Comment by Robot8A** [comment]
Thanks to everybody!
