### ISSUE TITLE
Add multiple GB brands

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#4474]
A few GB brands that I don't think are in the index yet, a little research and Wikidata creation / updating is also required.

- [ ] National Plastics - Q100297552
https://www.nationalplastics.co.uk/

- [ ] Howarth Timber - Q100298474
https://www.howarth-timber.co.uk/

- [ ] Howdens
https://www.howdens.com/ ~ en:Howdens_Joinery ~ Q5921438

- [ ] City Plumbing
https://www.cityplumbing.co.uk/

- [ ] Benchmarx
https://www.benchmarxkitchens.co.uk/

- [ ] CCF
https://www.ccfltd.co.uk/

- [ ] BSS
https://www.bssindustrial.co.uk/

- [ ] EH Smith - Q100299126
https://ehsmith.co.uk/

- [x] Flavour Vapour
https://www.flavourvapour.co.uk/

**Comment by Adamant36** [comment]
If you don't mind I'm probably going to split some of these off into individual issues. It seems like they are getting done quicker that way. Since we still have multiple German brands, multiple India brands, etc. etc. that haven't been added yet. Plus, then we won't risk someone trying to do all of them at once and making a bunch of mistakes in the process as much either. Feel free to keep adding to the list in the meantime though. At least I created Wikidata entries for some of them.

**Comment by UKChris-osm** [comment]
@Adamant36 no problem with that idea at all :)

**Comment by ashutoshshisodia** [comment]
Hey @Adamant36 I am from India and I see many brands are not listed. Shall I create an issue for that ? Or just create a PR without the issue ?

**Comment by Adamant36** [comment]
Either one is fine. If you want to add them yourself then a PR works. If not the feel free to open an issue. Although if its a lot of brands id suggest opening multiple issues. Since it seems like they get dealt with quicker that way.

**Comment by xhika** [comment]
#4541 Took the liberty to fix all :) hope its alright

**Comment by amous4822** [comment]
I think this issue is solved. @UKChris-osm
