### ISSUE TITLE
add BudMil

### ISSUE THREAD

**Issue by debyos** [osmlab/name-suggestion-index#4483]
Hi,

budmil is a small but well-known Hungarian sportswear brand:
- https://budmil.eu/en
- https://hu.wikipedia.org/wiki/Budmil
- http://overpass-turbo.eu/s/YYB

It may be too small to deal with it.

**Comment by Adamant36** [comment]
> It may be too small to deal with it.

From their website it looks like they have 42 stores. Which is usually enough. What's included or not isn't a hard and fast rule anyway. Things are usually included if it would be a hassle for someone to add the tags to the POIs on their own. For me at least that's usually 15 or 20 locations. Although, sometimes it's lower. For instance, I'm pretty sure I've added a few banks with only like 7 locations because the entries helped separate them from different banks with the same names in the same locations. So, I wouldn't worry about it to much. 

(I know that's probably a needlessly detailed response, but whatever 😄)

**Comment by debyos** [comment]
> (I know that's probably a needlessly detailed response, but whatever 😄)

Nevertheless, thank you!

**Comment by UKChris-osm** [comment]
Added via [ad4df05](https://github.com/osmlab/name-suggestion-index/commit/ad4df05116e30961d0aa546b61d05505f5219f8b), let me know if you think I missed anything :)
