### ISSUE TITLE
NSI.guide missing data present in source

### ISSUE THREAD

**Issue by michaelblyons** [osmlab/name-suggestion-index#4617]
I am trying to understand why the [nsi.guide entry for TriMet](https://nsi.guide/index.html?t=transit&k=route&v=bus&cc=us#trimet-a21cc9) has all the Wikidata tags and so on from [its source](https://github.com/osmlab/name-suggestion-index/blob/3d783662c1a1a49dc348afecc46cfc12d0c4c3a8/data/transit/route/bus.json#L11390-L11402) when [this source data](https://github.com/osmlab/name-suggestion-index/blob/87a2b9c3ebf90cb1f8b3879e1f7dfe7065d5f3fc/data/transit/route/subway.json#L414-L427) for "Washington Metro" only results in [a few tags](https://nsi.guide/index.html?t=transit&k=route&v=subway&cc=us#washingtonmetro-c94044).

Maybe I misunderstand how it works.

**Comment by Identitaet** [comment]
Basically the logos  so on need to be pulled from wikidata and that hasn't happened yet but just give it a bit of time

**Comment by bhousel** [comment]
That's because the Washington Metro item was only updated an hour ago.  

Next steps are that I need to run these commands:
- `npm run wikidata` - This step takes about 10 minutes but will fetch all the related wikidata links and logo urls and update the wikidata pages to have the correct nsi identifiers. This script also generates a lot of warnings for things worth looking into (like if a wikidata page or social media account disappears).
- `npm run dist` - This step takes a few seconds, but updates the files in `dist/*` that https://nsi.guide looks for

**Comment by bhousel** [comment]
> Wow. I guess I discovered your site at juuuust the wrong time. Thanks, and carry on. 😉

Haha I am happy you discovered it and hope you find it useful. 😄 
I just ran the commands and I'm seeing the updated data on [Washington Metro](https://nsi.guide/index.html?t=transit&k=route&v=subway&cc=us#washingtonmetro-c94044) now.

We're always looking for help with updating the Wikidata pages or adding the links, so browsing https://nsi.guide is a great way to see what needs updating 👍
