### ISSUE TITLE
BBVA Francés is the former name of BBVA Argentina

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#4650]
According wikipedia, [BBVA Francés](https://nsi.guide/index.html?t=brands&k=amenity&v=bank&tt=BBVA%20Francés) is the former name of [BBVA Argentina](https://www.bbva.com.ar).

See [brands/amenity/bank.json#L2184-L2199](https://github.com/osmlab/name-suggestion-index/blob/c9e02f02b60016c84001899c63b8375c0f04f619/data/brands/amenity/bank.json#L2184-L2199).

I suggest to remove theses tags too :
```json
"brand:en": "BBVA France"
"brand:fr": "BBVA France"
"brand:wikipedia": "en:BBVA Francés"
"name:en": "BBVA France"
"name:fr": "BBVA Francés"
```

I don't know if it's possible to keep the former name as a "synonym" with `displayName` ?
 ```json
    {
      "displayName": "BBVA Argentina (formely BBVA Francés)",
      "id": "bbvafrances-841353",
      "locationSet": {"include": ["ar"]},
      "tags": {
        "amenity": "bank",
        "brand": "BBVA Argentina",
        "brand:wikidata": "Q2876788",
        "name": "BBVA Argentina",
      }
    },
```

**Comment by pyrog** [comment]
It seem that the former name should be in `matchNames, does it ?

 ```json
    {
      "displayName": "BBVA Argentina",
      "id": "bbvafrances-841353",
      "locationSet": {"include": ["ar"]},
      "matchNames": ["BBVA Francés"],
      "tags": {
        "amenity": "bank",
        "brand": "BBVA Argentina",
        "brand:wikidata": "Q2876788",
        "name": "BBVA Argentina",
      }
    },
```

**Comment by Adamant36** [comment]
> According wikipedia, BBVA Francés is the former name of BBVA Argentina.

From what I understand they unified their brand globally and now it's just BBVA. 
https://www.bbva.com/en/bbva-to-unify-its-brand-worldwide-changes-its-logo/

**Comment by pyrog** [comment]
So should we:

1. Delete
   - [BBVA Francés](https://nsi.guide/index.html?t=brands&k=amenity&v=bank&tt=Q2876788)
   - [BBVA Bancomer](https://nsi.guide/index.html?t=brands&k=amenity&v=bank&tt=Q2876794) and [Bancomer](https://nsi.guide/index.html?t=brands&k=amenity&v=bank&tt=Q2876794)
   - [BBVA Continental](https://nsi.guide/index.html?t=brands&k=amenity&v=bank&tt=Q4835089) and [Banco Continental (Peru)](https://nsi.guide/index.html?t=brands&k=amenity&v=bank&tt=Q4835089)
   - [BBVA Compass](https://nsi.guide/index.html?t=brands&k=amenity&v=bank&tt=Q4835088)
1. Edit [BBVA](https://nsi.guide/index.html?t=brands&k=amenity&v=bank&tt=Q806189)
   - add `"matchNames": ["BBVA Francés", "BBVA Bancomer", "BBVA Continental", "BBVA Compass"],` or
   - add `"matchNames": ["Francés", "Bancomer", "Banco Continental"],` or
   - add both ?
1. Update OSM datas:
   - do a "mass edit" to replace old `brand:*` values to new ones ?
   - or update osmose analysers to suggest manual editions ?
1. Update Wikidata items

**Comment by Adamant36** [comment]
All four options sound like possible solutions. Which one to go with though? No clue 🤷‍♂️ Which is kind of why I never took action on it myself when I found out they were consolidating things.

**Comment by bhousel** [comment]
I think it would be a lot simpler for mappers and data consumers alike if people could agree to just map them all as "BBVA" and make it a global brand.

**Comment by pyrog** [comment]
Yes 😃, but should we keep old name in NSI ?

And does we update OSM data ?

Name | Count
--|--
BBVA Francés | 157
BBVA Bancomer| 263
Bancomer| 321
BBVA Continental| 94
Banco Continental (Peru)| 46
BBVA Compass| 163

**Comment by gedankenstuecke** [comment]
I wanted to pull this up again, as by now [the Wikidata entry itself at `Q2876788`](https://www.wikidata.org/wiki/Q2876788) has been updated to give _BBVA Argentina_ as the main name. And by now the naming scheme leads to a conflict of e.g. the iD editor recommending changing the name of a  generic _BBVA_ branch to the outdated _BBVA Francés_ (c.f. [here for an example](https://www.openstreetmap.org/way/310976414), in which an editor has already replaced the values with the current correct name, but iD will flag it to rename to the old name). 

Given the state of the rebranding according to the different Wikipedia pages I'd suggest the following changes instead of outright deletions:

BBVA Bancomer -> [BBVA México](https://en.wikipedia.org/wiki/BBVA_M%C3%A9xico) ([Q2876794](https://www.wikidata.org/wiki/Q2876794))
BBVA Continental -> [BBVA Perú](https://en.wikipedia.org/wiki/BBVA_Per%C3%BA) ([Q4835089](https://www.wikidata.org/wiki/Q4835089))
BBVA Compass -> [BBVA USA](https://en.wikipedia.org/wiki/BBVA_USA) ([Q4835088](https://www.wikidata.org/wiki/Q4835088))
BBVA Francés -> [BBVA Argentina](https://en.wikipedia.org/wiki/BBVA_Argentina) ([Q2876788](https://www.wikidata.org/wiki/Q2876788))
