### ISSUE TITLE
Remove redundant data

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#4672]
Hi all,

At least for France, there are a lot of **redundant** tags.

`*:wikipedia` could be removed.

By example, for ATM or post box, (at least french) community could choose to keep `brand` or `operator` tags, **not both** 😃 

Related to #2883

```
amenity=atm
brand=Banque Populaire
brand:wikidata=Q846647
brand:wikipedia=fr:Banque populaire
name=Banque Populaire
operator=Banque Populaire
operator:wikidata=Q846647
operator:wikipedia=fr:Banque populaire
```

```
amenity=post_box
brand=La Poste
brand:wikidata=Q373724
brand:wikipedia=fr:La Poste (entreprise française)
name=La Poste
operator=La Poste
operator:wikidata=Q373724
operator:wikipedia=fr:La Poste (entreprise française)
```

**Comment by bhousel** [comment]
Yes, I'm pretty ok with this redundancy.  I don't really see it as a problem.

**Comment by Adamant36** [comment]
@pyrog do they just not have brands in France? Or is it that they don't think an entity can be an operator and a brand at the same time?

**Comment by pyrog** [comment]
We have brands and operators in France,
And some could be both 😃 

But:
1. `brand:wikipedia=fr:La Poste (entreprise française)` is redondant
1. And especially not welcome when it link to a english page (cf. `brand:wikipedia=en:Bank of France`)

Apps should display the appropriate wikipedia page according to the user language.
So that's why I think that `brand:wikipedia` should be removed from NSI (at least for France 😉)

In the first exemple this should be enough to display useful information in iD or any other application:

```
amenity=atm
name=Banque Populaire
operator=Banque Populaire
operator:wikidata=Q846647

```

Or even 😉 
```
amenity=atm
operator:wikidata=Q846647
```

It could be `brand:wikidata=Q846647` (this is a detail for me), just avoid ~"Banque Populaire" 7 times for an ATM of this brand/operator.

**Comment by Adamant36** [comment]
> brand:wikipedia=fr:La Poste (entreprise française) is redondant

Why when it's both the operator and a brand?

> And especially not welcome when it link to a English page (cf. brand:wikipedia=en:Bank of France)

The fix for that would be to change it to the French Wikipedia article. 

> Apps should display the appropriate wikipedia page according to the user language.

Well, the apps aren't going to display any Wikipedia page, "appropriate" or otherwise, if there is not a Wikipedia related tag on the POI. As far as I know, there isn't any app that currently gets that information directly from Wikidata. The other option would be that people have to click the Wikidata link from the POI, which would open the Wikidata page in a separate browser window, then click through to the "correct" article, but that isn't simpler then just changing the brand:wikipedia tag on our end to the French article. Also, I'm pretty sure some apps, like OsmAnd, open Wikipedia pages in the app as information panels. Which you would be losing the ability to do.

**Comment by pyrog** [comment]
> Why when it's both the operator and a brand?

You're right, in all cases (operator or brand, or both) 😃 

> The fix for that would be to change it to the French Wikipedia article.

Yes 😃 
Or simply remove this "redundant" data 😉 


> Well, the apps aren't going to display any Wikipedia page, "appropriate" or otherwise, if there is not a Wikipedia related tag on the POI. As far as I know, there isn't any app that currently gets that information directly from Wikidata.

At least the **Map of historical objects**. See this [memorial](https://gk.historic.place/historische_objekte/l/en/index.html?zoom=17&lat=48.86213&lon=2.24467&select=n4484420031&pid=HaHbHcSaHe).
```
historic=memorial
name=Monument aux fusillés
wikidata=Q3091182
```
<img width="33%" alt="Node 4484420031" src="https://user-images.githubusercontent.com/2158081/99180476-e8a06b80-2726-11eb-91fb-3045b253c5e7.png">

**Comment by bhousel** [comment]
@pyrog ... I agree with you that many of the tags are redundant.  I'd also love for the redundant tags to go away from OSM.  You and I are living 20 years in the future maybe..

But for today, we add them because having them there is OSM community convention and there are apps and validations that depend on them.  The point of OSM is not to remove all redundancies and make a normalized database, but rather to just collect a bunch of factual stuff about the world for people to make maps out of.

* Yes `*:wikipedia` can go away and people can use `*:wikidata` for everything.  Maybe someday, but for today people use wikipedia tags.
* Yes multilingual name tags can go away and people can use `*:wikidata` to pick a local name for things.  Maybe someday, but for today people need them to be there, and JOSM/KeepRight validators even complain if they are missing.
* Yes `brand/operator` is redundant. This is because people use the tags interchangeably for some kinds of POIs, and different communities have different opinions about them. Maybe someday we'll have a community where stakeholders and developers make the rules about what the tags are. 
* (Aside: I will be adding some more things to `operators` that are definitely not "brands" and will not have `brand` tags.  Think stuff like power lines and other infrastructure - we are gathering the tags to do this.  Post Offices and bank ATMs exist in a middle area that are kind of both brands and operators).

Anyway I'm going to close this because we're going to keep the redundant tags.  If you want, you can just put out your own distribution of OSM that has all the redundant tags removed.  Nothing is stopping you from making a "simplified OSM" that's ODBL licensed and has the minimal set of tags, maybe with more wikidata integration.  And I think people might use it and see the value.

**Comment by pyrog** [comment]
> I'd also love for the redundant tags to go away from OSM.

Nice 😉 

> You and I are living 20 years in the future maybe..

> But for today, we add them because having them there is OSM community convention and there are apps and validations that depend on them.

I see NSI like a tool that help communities to normalise tagging.

I don't want to change all the world myself (I'am not Samantha in [Bewitched](https://en.wikipedia.org/wiki/Bewitched) 😆)
But I could discuss to evolve this (at least with the french community) and change this before 20 years 😉 

So, if all french brands don't have any `brand:wikipedia` or `operator:wikipedia` does it hurt other communities, I don't think so.

> Aside: I will be adding some more things to operators that are definitely not "brands" and will not have brand tags. 

I saw this. This is a good improvement of NSI. Sincerely, thank you 😃 

Maybe my english is not good enough ? I never asked to remove all `operator:*`, just want to "discuss" the necessity to spread a lot of redundant tags.
