### ISSUE TITLE
Add La Cervoiserie

### ISSUE THREAD

**Issue by MatthieuOSM** [osmlab/name-suggestion-index#4697]
La Cervoiserie is a French beer retailer, also considered as a bar/cellar (I also went in that place, similar concept like [V&B](https://github.com/osmlab/name-suggestion-index/issues/4696) but specialised in beers).
In their website they provide some stats: 500 beers, 56 liquors (that's the reason why I put `shop=beer` + `drink:liquor=yes`, their main product remains beer).
Delivery and takeaway options are not available (during covid19 there's call/clic and collect option in my city, but I cannot confirm they offer such an option for their usual business).

I'm not a fan of multi-tagging for an activity, as you buy for sure drinks but do not consume it in the same place, should we put as a secondary tag `amenity=bar`?

https://www.wikidata.org/wiki/Q101788539
No Wikipedia page.

`brand=La Cervoiserie`
`brand:wikidata=Q101788539`
`drink:liquor=yes`
`name=La Cervoiserie`
`shop=beer`

**Comment by bhousel** [comment]
Same comments I made on #4696 apply here.
* Definitely not `amenity=bar` (I think we agree on this)
* Avoid location-specific tags about what they sell, hours, payment, etc (we prefer ground survey for these)
* I'd use `shop=alcohol` which is more established, instead of `shop=beer` which is undocumented.
