### ISSUE TITLE
Have build_wikidata.js script fix broken *:wikipedia tags?

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#4717]
Following up from #4716 - if we can add missing `*:wikipedia` tags, we can also check all of them and fix any that are broken.

**Comment by UKChris-osm** [comment]
One other thing I did wonder about with "_build_wikidata.js_", with the web being more of an "_SSL_" platform these days, and with so many web sites listed as "_non-https_" on Wikidata which have since moved to "_https_", could the build script highlight any "_non-https_" web sites, or even auto-check if a redirect to "_https_" exists?

**Comment by bhousel** [comment]
> One other thing I did wonder about with "_build_wikidata.js_", with the web being more of an "_SSL_" platform these days, and with so many web sites listed as "_non-https_" on Wikidata which have since moved to "_https_", could the build script highlight any "_non-https_" web sites, or even auto-check if a redirect to "_https_" exists?

I think it's kind of out of scope for this project to clean up links in Wikidata, but do I agree that it's worth doing.  Someone could write a script to go through `dist/wikipedia.json` and check the links.  Or even a SPARQL query to check all the official_website links in Wikidata.  A process like that might be a thing that exists already - I'm less familiar with how things work on the Wikidata side.
