### ISSUE TITLE
Smythies took over the Toys R Us stores in EU

### ISSUE THREAD

**Issue by Identitaet** [osmlab/name-suggestion-index#4722]
see PR 4721
Smythies took over the Toys R Us stores in EU (and UK) so we should probably represent that.
The confusing thing is that the United States are not affected by that.

**Comment by tas50** [comment]
Toys R Us in the US is just gone.

**Comment by Identitaet** [comment]
yeah but it isn't replaced by smythies that's what I mean

**Comment by Identitaet** [comment]
okay so I read a bit more and apparently they only bought the german austrian and swiss stores (weird stuff)

**Comment by bhousel** [comment]
Yeah Toys R Us is a weird situation. Weirdly, there is still a few operating in US in mega malls, one in Paramus NJ and one in Houston TX.  (Wikidata doesn't seem current on this, but the situation is different every time I look into it).

My preference - for Toys R Us because of how weird it is - is to leave it alone in NSI for now but keep an eye on it.
We have it in NSI as a global brand, but there are only 200 or so in OSM - that's not too many:  
https://nsi.guide/index.html?t=brands&k=shop&v=toys#toysrus-80bf0f

- People can just update these by hand or use Overpass/JOSM/level0.  So, if you know for sure they should all be changed in the UK, then go ahead and do it in OSM.
- It's ok for people to map disused stores in OSM and then change the tag to say `disused:amenity` or something.
- I'm more worried about making changes in NSI that (whenever we release a new version) would introduce iD validation rules that encourage a tag upgrade that isn't universally true..
