### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Klumbumbus** [osmlab/name-suggestion-index#4780]
The link on https://josm.openstreetmap.de/wiki/PresetsSource is dead (https://raw.githubusercontent.com/osmlab/name-suggestion-index/main/dist/presets/name-suggestions.presets.min.xml)

**Comment by UKChris-osm** [comment]
Hi @Klumbumbus 

Because of some changes to the NSI, I think the URL you're looking for is now:
https://raw.githubusercontent.com/osmlab/name-suggestion-index/main/dist/presets/nsi-josm-presets.min.xml

**Comment by bhousel** [comment]
Thanks @Klumbumbus - It would be great to have more people testing our JOSM presets.  I tried to get them working in JOSM a few months ago but I wasn't successful.

For most people, links should probably go to the most recent stable published version.  I encourage people to use the JSDelivr CDN, which mirrors everything on npm and github and is fast everywhere:
https://cdn.jsdelivr.net/npm/name-suggestion-index@4/dist/name-suggestions.presets.xml
https://cdn.jsdelivr.net/npm/name-suggestion-index@4.0.2/dist/name-suggestions.presets.xml

For people who want the latest development version, what @UKChris-osm linked is good too, or can use this link:
https://cdn.jsdelivr.net/gh/osmlab/name-suggestion-index@main/dist/presets/nsi-josm-presets.xml
(as one might expect, stuff in the main development branch can go broken anytime)

We will be releasing v5 soon, and when that happens it will be published at:
https://cdn.jsdelivr.net/npm/name-suggestion-index@5/dist/presets/nsi-josm-presets.xml

I'll leave this issue open because I should update the README to reflect this.

**Comment by Klumbumbus** [comment]
I didn't test the preset :) JOSMs CI Jenkins noticed it.
Anyway a maintainer of this repo should know which is the correct link of the stable version and fix it on https://josm.openstreetmap.de/wiki/PresetsSource

**Comment by UKChris-osm** [comment]
> I encourage people to use the JSDelivr CDN, which mirrors everything on npm and github and is fast everywhere:

Does using the "_githubusercontent.com_" data have any effect on this project (such as data caps or anything)? I just tried the JSDelivr links and they were very slow, much slower than the "_githubusercontent.com_" links.

> We will be releasing v5 soon

Certainly looking forward to this :) Will it be available in iD soon after, or will that take a little more time?

**Comment by bhousel** [comment]
> Does using the "_githubusercontent.com_" data have any effect on this project (such as data caps or anything)? I just tried the JSDelivr links and they were very slow, much slower than the "_githubusercontent.com_" links.

I just checked again and you're right - the githubusercontent links are much faster than the jsdelivr mirror.  It doesn't have any effect on the project which links people use, so I'll update the readme with several options.

> Certainly looking forward to this :) Will it be available in iD soon after, or will that take a little more time?

Pretty soon after!  I'll open a PR for it.

**Comment by don-vip** [comment]
The link is now OK but the XML contents can't be parsed correctly:

```
[https://raw.githubusercontent.com/osmlab/name-suggestion-index/main/dist/presets/nsi-josm-presets.min.xml =>
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1692881; cvc-complex-type.2.4.b: The content of element 'group' is not complete. One of '{"http://josm.openstreetmap.de/tagging-preset-1.0":chunk, "http://josm.openstreetmap.de/tagging-preset-1.0":group, "http://josm.openstreetmap.de/tagging-preset-1.0":item, "http://josm.openstreetmap.de/tagging-preset-1.0":separator}' is expected.]
```

**Comment by bhousel** [comment]
> The link is now OK but the XML contents can't be parsed correctly:

Thanks for the tip @don-vip - I added some code to avoid generating empty menu groups.
