### ISSUE TITLE
merge financial.json and financial_advisor.json?

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#4842]
Currently we have [`financial.json`](https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/office/financial.json) and [`financial_advisor.json`](https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/office/financial_advisor.json) in the index.
Is there a meaningful difference between those or can they be merged? And what would be the preferred tag?

**Comment by michaelblyons** [comment]
[`office=financial`](https://wiki.openstreetmap.org/wiki/Tag:office=financial) wiki guidance sounds like non-customer-facing financial offices. (IDK? Wall Street?) There is no wiki tag for `office=financial_advisor` or guidance on [`office`](https://wiki.openstreetmap.org/wiki/Key:office) itself.

The places I've heard of that we have in `office=financial_advisor` are not the same as the guidance for `office=financial`, but I'm curious whether there's some other tagging or taxonomy we should be using instead.

**Comment by bhousel** [comment]
I looked into this today but I don't know where that `financial_advisor` tag came from.  

As far as I can tell NSI is the only place that the `office=financial_advisor` tag is used, so I'm ok with merging those entries (Edward Jones, NM Money, and TD Ameritrade) into `office=financial`.

**Comment by michaelblyons** [comment]
There's a low-use tag for [`amenity=financial_advice`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfinancial_advice) that roughly matches what we have in `office=financial_advisor`.

There's also a French (?) [wiki page](https://wiki.openstreetmap.org/wiki/Nantes/Projets/Commerces#Valeurs_pour_le_tag_.22Office.22) with a breakdown of finance-related offices that _does_ have `office=financial_advisor` in it.

**Comment by bhousel** [comment]
@1ec5 it looks like you introduced this tag in 8ec28dd
Can you share more about your thinking?  I don't see it on the osm wiki, nor used frequently in taginfo, and it wasn't a preset in iD until we got it from NSI.

(It's totally possible that it used to be a recommended tag on the osm wiki at one time and someone erased all use of the tag and didn't tell anyone).

**Comment by 1ec5** [comment]
> [`office=financial`](https://wiki.openstreetmap.org/wiki/Tag:office=financial) wiki guidance sounds like non-customer-facing financial offices. (Wall Street stuff? I do not know) There is no wiki tag for `office=financial_advisor` or guidance on [`office`](https://wiki.openstreetmap.org/wiki/Key:office) itself.

Right, I do think it’s useful to distinguish between financial advisors’ retail storefronts and non-retail financial offices (e.g., a bank headquarters or stock trading firm), just as that page distinguishes `amenity=bank` and `office=tax_advisor` for other kinds of retail financial offices. [The `office` page](https://wiki.openstreetmap.org/wiki/Special:PermanentLink/1984328#Usage) has encouraged the coining of new values [since the beginning](https://wiki.openstreetmap.org/wiki/Special:Diff/469717), though `financial_advisor` was already in use when I added Edward Jones to the index.

I added [this wiki page](https://wiki.openstreetmap.org/wiki/Tag:office%3Dfinancial_advisor) describing the tag as it’s currently used. My fault for overlooking that step when adding the NSI entry originally.

**Comment by bhousel** [comment]
> I added [this wiki page](https://wiki.openstreetmap.org/wiki/Tag:office%3Dfinancial_advisor) describing the tag as it’s currently used. My bad for overlooking that step when adding the NSI entry originally.

Thanks! I think we can close this since there is a difference between the two tags, and they are documented now.
