### ISSUE TITLE
Wiphala / Bolivia

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#4892]
Following a convo on Slack with @1ec5 and @ArloJamesBarnes 
Bolivia is an interesting case because their constitution allows the Wiphala as a _dual flag_.
https://en.wikipedia.org/wiki/Flag_of_Bolivia
https://en.wikipedia.org/wiki/Wiphala

So we want to make sure that
- there is a suitable item in NSI for the Wiphala (possibly https://www.wikidata.org/wiki/Q1193967 as the symbol or a new QID as the flag?)
- test the matcher can handle a reasonable tagging of this, and won't try upgrading a Wiphala flag to Bolivian national flags based on the `country` or `subject` tags.

example flagpole:
https://www.openstreetmap.org/node/8393427376

**Comment by ArloJamesBarnes** [comment]
(research brain dump, not immediately actionable)

Apropos of https://github.com/osmlab/name-suggestion-index/discussions/4759, there are four colour-order variants (from hoist to fly, and using the same looping sequence with different start points) for the four suyus (quadrants of the former Inca holdings as centered on Cusco), which Wiki[pedia/media Commons] refers to by the major diagonal: `yellow;orange;red;purple;blue;green;white;yellow;orange;red;purple;blue;green` (white diagonal, this seems to be the most common in photos and stands for Qulla Suyu), `orange;red;purple;blue;green;white;yellow;orange;red;purple;blue;green;white` (yellow diagonal, stands for [Q/K]unti[n] Suyu), `purple;blue;green;white;yellow;orange;red;purple;blue;green;white;yellow;orange` (red diagonal, stands for Chincha[y/u] Suyu), and `white;yellow;orange;red;purple;blue;green;white;yellow;orange;red;purple;blue` (green diagonal, stands for Anti[n] Suyu which has an alternate too). Sometimes pink is used instead of purple in these. There's also a couple unlikely to be on the map, as they are historical, designed by Túpac Katari.

Other test case: https://osm.org/node/8403476132

**Comment by bhousel** [comment]
I added a Wiphala entry in 426fbd45 :
```js
{
  "displayName": "Wiphala",
  "id": "wiphala-e5dc93",
  "locationSet": {"include": ["001"]},
  "tags": {
    "flag:name": "Wiphala",
    "flag:type": "cultural",
    "flag:wikidata": "Q1193967",
    "man_made": "flagpole"
  }
},
```

This might not be perfect, but here's what I was thinking:
- locationSet `001` makes it worldwide. This is because some of the examples we've seen show it flying at embassies or cultural centers outside of South America.
- We need an entry for it in case someone has mapped one with `country=BO` - the matcher should match this item before the Bolivian flag, and not try to upgrade it to a Bolivian flag.
- I've added `flag:type=cultural` instead of `national`.. OSM wiki doesn't have a documentation for "cultural", but [taginfo shows it has some use](https://taginfo.openstreetmap.org/keys/flag%3Atype#values).  I didn't feel right using "religious" or "national".
- As @ArloJamesBarnes mentioned above there are several color variants.. I left this off so that mappers can supply it if known.

Anyway, we can revisit it later if we need to, but I think it's great to have some initial support for it.  It's a really pretty flag!

<img width="100" alt="Wiphala" src="https://user-images.githubusercontent.com/38784/110501726-76cea200-80c8-11eb-8503-3e3750b03b3f.png">
