### ISSUE TITLE
Research needed for: amenity/fuel|GPL

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#491]
#### :thinking: We need help deciding what to do with "amenity/fuel|GPL"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/fuel|GPL` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/fuel|GPL`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/fuel|GPL`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by Adamant36** [comment]
Global Petroleum Logistics

**Comment by ENT8R** [comment]
GPL stands for 'Autogas' in countries like [Italy](https://www.mylpg.eu/stations/italy/) and [Romania](https://www.mylpg.eu/stations/romania/), where, according to [Overpass Turbo](https://overpass-turbo.eu/s/Hgm), all entries exist. I could not find anything which says 'Global Petroleum Logistics'...

**Comment by Adamant36** [comment]
Maybe you could have waited for me to respond before you closed the issue. Since I might have had a reference you just didn't find. What's the rush?  I'm pretty sure I didn't just come up with Global Petroleum Logistics off the top of my head. Like I said in another issue, some of this pretty obscure. 

Also, it doesn't even seem like you dealt with it in the PR that's referenced. The only thing filtered there is GNV. Unless I'm missing something.

**Comment by ENT8R** [comment]
Sorry that I was too fast... The entry for `amenity/fuel|GPL` has now a lower count than 50 meaning that it was removed somewhere between October and now. Nethertheless I added a regex to filter out the entries of this name if the amount will grow again to something above 50.
Because of the absence of this entry in the index I thought this might not be that important anymore so I just closed this issue without any further comment.
And in addition to that the data supplied by Overpass Turbo led to my fast conclusion that this is just a generic name after all.
But if you are finding some more information, I'm happy to add it again!

**Comment by Adamant36** [comment]
Its cool. I think this is the rare exception where it was ok. I just wanted to bring it to your attention for the future. Personally, I probably check this for activity way to much. So it wont take to long for me to reply to something if need be. 

How come entries with less then 50 uses gets removed? I was under the impression that @bhousel didn't really have a lower usage limit for entries anymore. 

It would be worth keeping entried with less then 50 uses just to improve bad tagging if nothing else. Plus, people who tag them back up to that amount wont have the extra tags or information about the company they would otherwise.  

@matkoniecz, I seem to remember you mentioning the <50 thing a few times in issues recently.

**Comment by matkoniecz** [comment]
> @matkoniecz, I seem to remember you mentioning the <50 thing a few times in issues recently.

Two entries dropped below 50 with recent planet update, both stayed in index but started to emit warnings. I solved this two.

It is possible that other entries got dropped in https://github.com/osmlab/name-suggestion-index/commit/5e6f2a4e6441f3fc74d2174d91e2239e491e8dfc

But GPL is not affected by the most recent data update - see https://github.com/osmlab/name-suggestion-index/commit/5e6f2a4e6441f3fc74d2174d91e2239e491e8dfc.patch

**Comment by Adamant36** [comment]
Hhhmmm. Ok. Maybe I'll open an issue to see if the threshold can be lowered.

**Comment by bhousel** [comment]
> How come entries with less then 50 uses gets removed? I was under the impression that @bhousel didn't really have a lower usage limit for entries anymore.
> 
> It would be worth keeping entried with less then 50 uses just to improve bad tagging if nothing else. Plus, people who tag them back up to that amount wont have the extra tags or information about the company they would otherwise.

Yes it is ok to leave real brands in the index that have <50 entries.
It is ok to add `"nocount": true` to suppress the warning.

I think I should change the `build_all_names` script so that it also collects any name which already has a `brand:wikidata` tag.

**Comment by matkoniecz** [comment]
Note #2500 - some minimal usage is required, flood of single use names would not be helpful.

Maybe 10 `brand:wikidata` with given name as the low bar?
