### ISSUE TITLE
operator tags on post_box and atms (at least in France)

### ISSUE THREAD

**Issue by nuxper** [osmlab/name-suggestion-index#4925]
Note : related to https://github.com/osm-fr/osmose-backend/issues/1174

I implemented a tag suggestion analysis in osmose: http://osmose.openstreetmap.fr/fr/map/#item=3130&class=31302&country=france_rhone_alpes_rhone&zoom=15&lat=45.75165&lon=4.83582&level=1%2C2%2C3&tags=&fixable=

I find the nsi quite verbose for atms and post_box. I'd like your thoughts before I change anything to the nsi:

I observe the following in France at least:
Post boxes are currently all tagged with the following tags:
amenity = post_box
collection_times = Mo-Fr 14:30, Sa 09:00
operator = La Poste
ref = A1N4G1
source = data.gouv.fr:LaPoste - 05/2016 

In France, all post_boxes are operated by La Poste.
If I follow the name suggestion index, I would add:
**brand = La Poste
brand:wikidata = Q373724
brand:wikipedia = fr:La Poste (entreprise française)
operator:wikidata = Q373724
operator:wikipedia = fr:La Poste (entreprise française)**
Even though that's not incorrect, I believe that's a lot of redundant information to add to all 16000 post_boxes in the country. If we wanted to add those tags, a mechanical edit would be more appropriate.

I suggest to exclude "La Poste" from the post_box template.

In a similar way, atms now suggest adding:
**brand = Crédit Mutuel
brand:wikidata = Q642627
brand:wikipedia = en:Crédit Mutuel
operator:wikidata = Q642627
operator:wikipedia = en:Crédit Mutuel**
amenity = atm
name = Crédit Mutuel
operator = Crédit Mutuel
source = Credit-Mutuel-de-Bretagne_20090205 

Maybe operator:wikidata could be useful but but wikipedia for atms ? brand for atm ?
less than 1% of the nodes have a brand tag: https://taginfo.openstreetmap.org/tags/amenity=atm#combinations

**Comment by UKChris-osm** [comment]
Using [Royal Mail](https://nsi.guide/index.html?t=operators&k=amenity&v=post_box#royalmail-f65bfd) Post Boxes as an example, I don't think having both "_brand_" and "_operator_" is necessary if both sets of data are the same, so I'd probably suggest that with entries where "_operator_" is the primary focus (such as Post Box's) that "_brand_" data should be removed.

**Comment by bhousel** [comment]
Good suggestion @nuxper  - I agree that it's redundant to have both the `brand:` and the `operator:` tags for post offices and post boxes.  I will remove the redundant `brand:` tags . 👍 

For context, this is because the post offices were originally added as brands back when NSI only supported brands.  We support `operator` now, and they currently live in the "operators" tree.  There is even some code in the build script to copy the tags, and I commented "note: we can change this later if people hate it". 😆 

We are still also duplicating the `brand`/`operator` tags for amenity/bicycle_parking and amenity/car_sharing.
Should I remove brand tags from them too?  These categories might be more brand-like, I don't know.

https://github.com/osmlab/name-suggestion-index/blob/c353bb2c972c6a3a10243873299d28ab8de5ecbc/scripts/build_index.js#L400-L424

**Comment by UKChris-osm** [comment]
When it comes to "_operator_", could the build script check to see if this is the same data that exists in the brand tag, and if so, remove it?

**Comment by bhousel** [comment]
> When it comes to "_operator_", could the build script check to see if this is the same data that exists in the brand tag, and if so, remove it?

Yea, that's what I'm going to do, at least as a first pass.

**Comment by bhousel** [comment]
I just removed all the redundant brand tags.

The only one that remains is for Speedy, which kind of makes sense.. They are a brand that DPD uses in Bulgaria only.
https://github.com/osmlab/name-suggestion-index/blob/551de0a47bc74fb026a39eaccd9965080e76f5ab/data/operators/amenity/post_office.json#L1160-L1170
