### ISSUE TITLE
Can entries in different languages be merged?

### ISSUE THREAD

**Issue by chuqtas** [osmlab/name-suggestion-index#4994]
For example, these two:

![image](https://user-images.githubusercontent.com/51102336/112426889-d5fd0980-8d8c-11eb-9bc8-c55293ad8313.png)

Could they be listed under a single entity with:

brand:en=Nissan
brand:ja=日産
brand:wikidata=Q20165
brand:wikipedia=en:Nissan
brand:wikipedia=ja:日産自動車
name:en=Nissan
name:ja=日産
shop=car

?

If there is no "brand=" entry will it default to using the user's preferred language? "brand:xx=" ?

**Comment by bhousel** [comment]
This is intentional - we support regional variations in the index to allow mappers in different parts of the world to use the tags that they want to use locally.   So this brand will be tagged with as `name=日産` in Japan, and `name=Nissan` elsewhere.  

OSM doesn't yet support having map rendering in the user's preferred language, or fetching localizations from elsewhere (like using the Q20165 Wikidata link).  If they ever did support something like that, we could eliminate a lot of redundancy, but for now it's best to keep all the regional tagging variations in the index.
