### ISSUE TITLE
IKI Lithuania.

### ISSUE THREAD

**Issue by empersOSM** [osmlab/name-suggestion-index#5023]
IKI is a shopping chain in Lithuania, operated by UAB Palink. The tags are as follows:

name=IKI
operator=UAB Palink
shop=supermarket
brand=IKI
brand:wikidata=https://www.wikidata.org/wiki/Q1653981
brand:wikipedia=lt:IKI (parduotuvių tinklas)
opening_hours=Mo-Su 08:00-20:00

**Comment by bhousel** [comment]
Thanks, @empersOSM I just added it..
I skipped `operator` and `operning_hours` because these are tags we don't usually include for supermarkets (we encourage mappers to ground survey the hours, and I don't know for sure how franchising works for this brand - operator might be the parent company or might not be).

**Comment by empersOSM** [comment]
The operator is correct. Every single store is owned directly by UAB Palink and not by franchisers. Franchising is heavily regulated here and in general, is rare.

**Comment by bhousel** [comment]
> The operator is correct. Every single store is owned directly by UAB Palink and not by franchisers. Franchising is heavily regulated here and in general, is rare.

OK thanks, I just added it as "Palink" - OSM doesn't typically include the company format in these tags (like "inc" "llc" "gmbh" "ag" and so on)
