### ISSUE TITLE
backery Fischer???

### ISSUE THREAD

**Issue by Bibi56** [osmlab/name-suggestion-index#5136]
https://nsi.guide/index.html?t=brands&k=shop&v=bakery&tt=fischer
=> nothing on the website indicates that it has Fischer as brand, nothing indicates that they have bakeries (i.e. shops selling bread) at all.

They do produce bread, it's said in the history that "The history of Panelux is closely linked to that of the Fischer Bakery. The two companies, which were once part of the same whole, became separate entities in 2010". Half of a eternity in OpenStreetMap time range, isn't it? ;-)

**Comment by Adamant36** [comment]
It looks like they only entries for Panelux in OSM are a building and a window place. Neither of those are bakeries. So, there should probably at least be some real world tagging before the is changed. Or I guess it could just be deleted.

**Comment by Bibi56** [comment]
@Adamant36 I believe the entry is due to the history (as owner of the Fischer bakeries), deletion sounds correct to me.

**Comment by bhousel** [comment]
Thanks for flagging this @Bibi56 , I removed the "Fischer" item and set it as a generic bakery name.

From overpass, I thought that there was a brand in Germany, but it turns out that most of those red dots are not bakeries, it's just a common name used for many things.   Many of them _are_ bakeries, in Germany and elsewhere, but they don't seem to be operating as a larger chain that we would track in NSI.

<img width="1048" alt="Screen Shot 2021-08-24 at 11 06 51 AM" src="https://user-images.githubusercontent.com/38784/130641620-bf06475f-c4fb-4f3d-9411-44d91a21b5a4.png">
