### ISSUE TITLE
Scottish Water

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#5193]
Had a look at the operators section for the first time, noticed the drinking water tag had some entries - here's another one to add since they are installing lots of these: https://www.yourwateryourlife.co.uk/find-your-nearest-top-up-tap/

However, how is this supposed to work in terms of iD adding the tags - if you start typing in "Scottish Water" in the operator field, will it autocomplete the info or just prompt you to upgrade once you type it in?

location=gb-sct
amenity=drinking_water
operator=Scottish Water 
operator:wikidata=Q7438022
operator:wikipedia=en:Scottish Water

**Comment by bhousel** [comment]
> However, how is this supposed to work in terms of iD adding the tags - if you start typing in "Scottish Water" in the operator field, will it autocomplete the info or just prompt you to upgrade once you type it in?

Sounds good to me - here is the tl;dr of how it works:

**Presets:**  Each item in NSI with a wikidata tag will have a preset in iD generated for it.  So if you start typing "Scottish Water" in the preset search field, it should appear in the list.

**Validator:** The iD tag validator will also look at the tags of every feature and try to match to an NSI item based on tag/name combinations.  So if you have a feature with `amenity=drinking_water` and `operator=Scottish Water` (the matcher is fuzzy and can check several tags and spelling combinations), it can prompt the mapper to add any missing tags so that the feature has all the tags NSI thinks it should have.

These behaviors are also location-dependent, so you can scope "Scottish Water" to be a thing that only exits in some places, or you can have different "Scottish Water" items in different places.

**Comment by UKChris-osm** [comment]
Added via [3301cde](https://github.com/osmlab/name-suggestion-index/commit/3301cde5f70c9c45f171b072cc1ceb96d545a451) - are you happy with this @boothym as I also added a name tag for "_Top Up Tap_"?

**Comment by boothym** [comment]
@bhousel makes sense, I noticed that happening to a post box with the Royal Mail operator. 

Though I was thinking more of an existing post box or ambulance station for example, where a user starts typing in the operator field - similar to how the name field suggested brands when you started typing. More intuitive than typing an operator name in th preset field?

@UKChris-osm thanks, that looks fine, can always change/remove the name later (bottle=yes and fee=no could be added as well I suppose!)

**Comment by bhousel** [comment]
> Though I was thinking more of an existing post box or ambulance station for example, where a user starts typing in the operator field - similar to how the name field suggested brands when you started typing. More intuitive than typing an operator name in th preset field?

I actually removed this behavior because people said that typing in the `name` field and having it auto-complete was confusing 😄 
https://github.com/openstreetmap/iD/issues/8304 , https://github.com/openstreetmap/iD/issues/8271, etc..

**Comment by boothym** [comment]
Oh right, I wondered about that as I hadn't seen any name autocompletes recently!

However those issues - and also https://github.com/openstreetmap/iD/issues/8588 - are surely things that could be fixed so that iD doesn't select the wrong name or prevents users from using the same name as a brand when it's not in fact that brand?

Shouldn't be so much as _autocomplete_, but "show suggestions to click on/select as you type". And if you limit it to the particular tag, amenity=drinking_water tag in this case, that would also help limit mistakes.
