### ISSUE TITLE
List recycling amenities in operator tree?

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#5210]
Recycling stations are usually managed by and branded after the operator. They are often named differently depending on their location, see e.g. the [website](https://www.bsr.de/recyclinghoefe-20503.php?view=map) of the municipal recycling operator in Berlin. I think it would therefor make sense to list `amenity=recycling` station in the operator tree.

**Comment by bhousel** [comment]
This makes sense to me too - I can move them over.

**Comment by bhousel** [comment]
I started doing this but realized the existing BottleDrop items already have a `brand` and `operator`.  

So I don't want to change them just yet, but I want to think about whether it's possible to have a category in both trees without it causing problems. (This is like the bike sharing category, re #5167) 

https://github.com/osmlab/name-suggestion-index/blob/3f701749a29a42a6330e6b3dcf93d187627a045e/data/brands/amenity/recycling.json#L14-L27

**Comment by bhousel** [comment]
Ok, we are now collecting the recycling providers based on their `operator` instead of their `brand`.  
There is a new `operators/amenity/recycling.json`  file with lots of unmatched items to work through..

I have kept a few items in the `brands/amenity/recycling.json` file that work like brands (the BottleDrop ones, and some of the donation bins).
