### ISSUE TITLE
Add Polaris

### ISSUE THREAD

**Issue by cliffordsnow** [osmlab/name-suggestion-index#5233]
Polaris is a US based manufacturer of ATV, snowmobiles, and motorcycles with sales offices worldwide except for a small handful of countries.

name=Polaris Inc.
brand:wikipedia=en:Polaris Inc.
brand:wikidata=Q1850587
shop=atv;snowmobile;motorcycle;boats

logo https://en.wikipedia.org/wiki/Polaris_Inc.#/media/File:Polaris_Industries_logo.svg

Notes: 
1. Most Polaris dealers I'm familiar with have different names, much like car dealers. 
2. Not all dealers sell all Polaris products.
3. Products may have different brand names, such as the Indian Motorcycle or the Slingshot 3 wheel motorcycle.

**Comment by arch0345** [comment]
After looking at all the brands Polaris offers, here are the brands that should be added:

ATV:
- [ ] Polaris
- [ ] Hammerhead

Motorcycle:

- [ ] Indian Motorcycle
- [ ] Polaris

Snowmobile:
- [ ] Polaris
- [ ] Timbersled

Boat:
- [ ] Bennington
- [ ] Godfrey
- [ ] Hurricane

Car:
- [ ] Axiam

Other (potentially):
- [ ] Goupil
- [ ] Taylor-Dunn

We don't have categories for shop=atv and shop=snowmobile right now, but those could be added in the future.

**Comment by arch0345** [comment]
I've added car/motorcycle brands for now as they had wikidata pages.

**Comment by bhousel** [comment]
Was looking into this issue today and I'm kind of confused by this.. Polaris sells through dealers, they don't have "Polaris" retail stores .  We don't really use the `brand` tags this way in NSI.  

I think this sort of tagging might be more compatible with the proposed [`sells:` namespace](https://wiki.openstreetmap.org/wiki/Proposed_features/Sells)

**Comment by arch0345** [comment]
> Was looking into this issue today and I'm kind of confused by this.. Polaris sells through dealers, they don't have "Polaris" retail stores . We don't really use the `brand` tags this way in NSI.
> 
> I think this sort of tagging might be more compatible with the proposed [`sells:` namespace](https://wiki.openstreetmap.org/wiki/Proposed_features/Sells)

Polaris does have a dealership in Portland named [Polaris of Portland](https://sknorthwest.com/Polaris-of-Portland), although it's kind of a dealership within a dealership. This is similar to other motorcycle brands in the Portland area. Maybe this is just because of Portland's smaller market, but we don't really have 'retail stores' for Honda, Suzuki, and other brands found in motorcycle.json. Unlike car dealerships, most motorcycle dealerships sell more than one brand.

Other brands that I've added from this issue, Indian Motorcycle and Aixam, seem to have dealerships that sell their respective brands solely. As for the other brands on the checklist, I'll remove these as there doesn't seem to be any stores that offer just that brand.

**Comment by bhousel** [comment]
I think this is good enough for now..  There are a handful of brands that are well known for selling their stuff only at authorized dealers (like Weber grills, Stihl chainsaws, Rolex watches) instead of their own retail stores.  I guess Polaris and their brands are like this too.
