### ISSUE TITLE
Branch tag added 

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#5281]
Not come across this before, don't know if it's an NSI or iD issue?

A shop=storage_rental with the name name=Safestore Self Storage had a suggested upgrade which basically split the name into two parts.

![self](https://user-images.githubusercontent.com/16965772/131218789-0a51fd8e-ebde-4e74-b0b4-78487a873f50.JPG)

**Comment by LaoshuBaby** [comment]
Related item：https://github.com/osmlab/name-suggestion-index/blob/0317da9fa454dcc73f6b0c33b15997ad614306af/data/brands/shop/storage_rental.json#L106-L114

**Comment by LaoshuBaby** [comment]
Maybe this is because you are lived in GB and the safestore you are mapping is a branch store of this chain brand.

**Comment by bhousel** [comment]
For now I added a matchname that should match "Safestore Self Storage", so it will not suggest the "Self Storage" as a `branch` name. 

The branch splitting code lives in iD, and it is trying to do a very difficult thing. We tested it a lot ([see comments around here](https://github.com/openstreetmap/iD/pull/8305#issuecomment-805454952)) but I do think that people who get a suggestion like this should consider whether it's correct.  (They can always delete the `branch` tag if it is detected wrong, like in this case)..  

I will try to adjust the iD code so that it won't suggest a `branch` that also matches a generic string like "Self Storage".

**Comment by boothym** [comment]
Thanks.

I didn't know about the branch tag implementation in iD, but I've since seen it suggested on another object named "Brand <name of town>" which split off the town into the branch tag - good idea.

I was also slightly confused as I thought the actual name was "Safestore Self Storage" but I see in NSI it's just Safestore, which is fine,.
