### ISSUE TITLE
Will NSI inside iD be trated as automatic edit?

### ISSUE THREAD

**Issue by LaoshuBaby** [osmlab/name-suggestion-index#5333]
According to OSM-talk mailing list, a DWG member is uncomfortable with this.

Will iD import a way to limit the use for those kind of suggestion such as this project?

https://lists.openstreetmap.org/pipermail/talk/2021-July/086868.html
https://lists.openstreetmap.org/pipermail/talk/2021-July/086872.html

**Comment by LaoshuBaby** [comment]
This news is in https://weeklyosm.eu/archives/14762

**Comment by bhousel** [comment]
I think most people would take the position that it's _not_ an automatic edit if the user needs to select and look at each thing being suggested and click a button to take action. 

The automatic edit and import policies are more for the situation where someone loads up a bunch of data and import or change a lot of stuff in OSM without reviewing each change.  You can't even do edits like this in iD.  (For an edit like this, I would always use JOSM with a dedicated bot account and discuss with somebody first).

**Comment by 1ec5** [comment]
As I understand it, the discussion on the talk list was occasioned by edits made in a different editor. [This post by Andy Townsend](https://lists.openstreetmap.org/pipermail/talk/2021-July/086872.html) (another DWG member) offers important context. iD’s NSI integration was not being singled out versus, say, a find-and-replace feature that iD currently lacks (#3137). Rather, the emphasis is on due diligence in general when using editor conveniences of any kind to carry out edits, especially in areas one is unfamiliar with.

If you have concrete suggestions for how iD’s NSI integration could make mappers more circumspect about the changes they’re making, please provide more detail so that the project can consider them. Thank you.

**Comment by LaoshuBaby** [comment]
Oh, I'v been a little frightened at first, but now I’m a little relieved.
Asking about this is question, mainly for fear of being judged as automatic editing when using NSI to fix the label and being banned, and for fear that this discussion in mailing list will adversely affect the future development of NSI, because 
>"fixing" in editors
it mentioned in the first e-mail.

And I seem to have misunderstood Andy's meaning when raising this issue, so I mistakenly thought that the community might prohibit NSI from doing this.

I'm very sorry to bother you everyone, and thank you for your patient reply.

Best wishes
