### ISSUE TITLE
Store names which include the branch name

### ISSUE THREAD

**Issue by NKAmapper** [osmlab/name-suggestion-index#5500]
Store names in Norway includes the branch name, for example "Spar Arendal Sentrum", not just "Spar", as [discussed](https://lists.nuug.no/pipermail/kart/2012-April/003391.html) by the local community. This is also the case for other categories such as fuel stations, hotels, restaurants etc .

How could this be specified in the index?

Currently, iD is encouraging users to strip the name tag for everything but the brand name, causing a lot of unwanted edits.

**Comment by arch0345** [comment]
By adding `"preserveTags": ["^name"],` to the entry, iD will keep the name of the locations and not suggest splitting into `name=*` and `branch=*`. The `name=*` will only be used when a new POI is added. Here is an example of this:
```
    {
      "displayName": "Verizon",
      "id": "verizon-ce3e5c",
      "locationSet": {"include": ["us"]},
      "preserveTags": ["^name"],
      "tags": {
        "alt_name": "Verizon Wireless",
        "brand": "Verizon",
        "brand:wikidata": "Q919641",
        "brand:wikipedia": "en:Verizon (mobile network)",
        "name": "Verizon",
        "shop": "mobile_phone"
      }
    },
```
All of the entries can be easily viewed under the `data` folder on the main page. Let me know if you need any help with this.

**Comment by NKAmapper** [comment]
I think the index is a great idea, I just did not realize that it would enforce one way of using the name=* tag. I just discovered that a large number of store names had been edited in Norway and tried to understand how that happened.

I guess both methods (name=* with and without the branch name) are being used in other countries as well, but I have not checked. A problem with branch is that search is in general not supported, at least not in Nominatim and in all the apps I have tried. A search will then usually just produce a list of identical brand names within the same city, which is not very helpful.

The practice of name=brand+branch has in fact been used since 2012, and is being actively maintained that way. We have put a lot of effort into getting a complete and well structured set of the most common retail chains in the country into OSM. It has been discussed several times on IRC/#osm-no, including today.

**Comment by Adamant36** [comment]
> No, but not everything in OSM can be seen on the ground. It doesn't mean it isn't the correct information. Many roads have names, but only the ref has a sign, many houses have a house number without having an actual number on the wall.

Sure, but that's a false equivalency because in this case the information is actually on the ground. So they aren't comparable. Otherwise, that would be like saying "you can't tag this as a house even though you can see it's a house because the boundary of the city where house is located can't be confirmed to exist in the real world." Who cares? They have nothing to do with each other. 

> Yes, NKA has put a lot of work into building a uniform dataset for all shops in Norway and I don't see why the "iD fiddlers" should have some special right to override these, because they are not mapping whats on the ground either, they'll be mapping what iD tells them to because there is a warning.

How do you know whoever is using ID Editor to "fiddle with the tags" didn't visit the location of the store before they used the preset? conversely, I highly doubt NKA has visited every single store in Norway to check that how they are tagging things is correct. So why should NKA have special right sitting at his home computer to make a judgement over anyone else that's doing the same thing if they haven't ground verified the name of the store? 

> The name of the restaurant is "Egon Lagunen" in all places (search engines, restaurant rating services, untappd, Egon's official website etc).

Generally I probably wouldn't have a problem with a brand that's only located in Norway excluding the name field if that's what the local community decides. Although, it would have to be a better reason then the mediocre ones I've heard so far. Especially if the people fronting those reasons are unwilling to consider alternatives. 

That said, brands like Shell, Shell Express, 7-Eleven (and I'm sure others) are global brands. As such the wider global OSM communities preferences should be considered. Since it would be weird and detrimental to the quality of the map if we fragmented how global brands are tagged into silos based on the country, state, town, neighborhood Etc. Etc. that they are located in. Say Germany's prefer "Seven-Eleven", Norwegians prefer "Seven-11 Arendal Sentrum" or whatever, and American's prefer "7-Eleven." Maybe we could technically accommodate that in the Index, but I don't think it would be a good idea to because it essentially makes finding a 7-Eleven impossible for anyone that's not a local.

**Comment by 1ec5** [comment]
The crux of the issue seems to be how to name branches of multinational brands: is the brand’s consistency across the globe more important, or is the brand’s consistency with local naming practices more important? Depends on the use case, I suppose.

Unlike most of the keys NSI standardizes, `name` is prone to regional variation due to variations in cultural naming practices. For any data consumer that isn’t aware of all the ways `brand` and `branch` can be combined to form a `name` in the (unspecified) local language, a fully-qualified `name` can add information that’s hard to obtain otherwise.

There’s a limit to how well some of the American examples above translate to other countries – the U.S. is the land of strong brand identity! But even here, one could make the case that the `name` of an IGA supermarket should generally include the branch name, and NSI already has plenty of other per-category and per-brand exceptions. As I explained in openstreetmap/iD#8734, there can even be inconsistency even within a single brand in a single country, but at least `branch` should be a way for a mapper to affirm that `name` intentionally includes the branch name.

[![Tatsuda IGA](https://upload.wikimedia.org/wikipedia/commons/9/93/Tatsuda_IGA.jpg)](https://commons.wikimedia.org/wiki/File:Tatsuda_IGA.jpg)
_`branch` + `brand`, not the other way around._

**Comment by Adamant36** [comment]
>we should have consistent naming.

Adding special words or characters to the end of a name isn't "consistent naming" though. Its literally a different name. "Walmart" isn't the same name as "Walmart, Sacramento, California." Its weird to act like it is. 

> Whenever someone tells me to meet me at "Esso Nesttun" I go to my map provider and search for "Esso Nesttun", then I expect to find a gas station names "Esso Nesttun", not "Esso" and then I have to go into the hidden information five steps down with a tag like branch in order to know if this is the Esso I am looking for.

I assume depending on the software that if Esso Nesttun was in the local_name field (or whatever alternative) and you searched it that you'd still be getting the Esso Nesttum in the results whatever the name field has in it. So you wouldn't have to go five steps down if you trusted the software and (or) knew it supported the alternative tag ahead of time. We literally have to do that with everything already. 

In the meantime if it turns out you get the wrong result then its on Nominatim or whoever to figure out why you aren't getting the correct results in their software. Otherwise we could justify adding the location of anything in the name field  just to make it more easily findable. "I don't know if I'm getting whatever mountain in the search or something else. So I'm going to put 'mountain, country, state, county, nearest locality, etc.' in the name field so I'm sure I get what I want." 

>Another use case is that shop websites using "click and retrieve" (order and pay on website -> Pickup in store) will tell me to pick up my item at "Clas Ohlson Bergen Storsenter" -> I will then lookup in the map where this store is (searching on name as this is defacto standard in all applications).

Every brand in the world that has pickup says what store location you should do the pickup at when you order something. Again, just because the location isn't in the name field doesn't stop you from finding it if the information is in a different one. 

I should have clarified that by useful I meant within in the context of a use case that is unique to the name field and that can't just as easily (and probably better) be served by a different tag. If its a 1/1 where every reason that the name field should contain the location can also apply to something else, then the case should be made why we shouldn't just go with that something else instead. 

Like @bhousel said, the branch tag is a more "modern" way of tagging store locations as opposed to puting the information in the name field and it has its advantages. Same with the other options. Looking at line 23 of https://github.com/osm-search/Nominatim/blob/master/settings/import-extratags.style it appears they support a ton of alternatives to the normal name tag. I don't see the branch tag listed there, but maybe its worth asking them to support it. If they don't want to for some reason its not like there isn't many other options though. My guess is that eventually someone will want to use them anyway. Realistically you can't edit war them over it if they do. So......

**Comment by 1ec5** [comment]
> P.S. I asked a few messages back if the branch name had a real world use and my question was ignored. Of course if there is one then I'm willing to adjust my opinion, but ultimately there is numerous options of what can go in the name field and the usefulness of the information IMO is best way to decide what should or shouldn't go in it. People should also be able to say what the benefit of what they are asking for is.

I don’t want to muddy this conversation even more, but since you asked, one underappreciated use case for the fully qualified name has little to do with rendered maps. Bulk geocoding services are often used for “location tagging” in news reports, receipts, bank statements, spreadsheets, etc. There isn’t a user meticulously choosing the best result for each query, but often the input does contain the fully-qualified name. The geocoder will yield higher-quality results if it’s able to index that fully qualified name. This isn’t the same as indexing “Walmart, Sacramento, California” just because the Walmart location happens to be in Sacramento; rather, it’s about indexing “Tatsuda IGA”, “East Springfield Avenue Shell”, or “Safeway #5052”. Someone looking at a map might regard that as clutter, but location data is used for more than maps.

Personally, I don’t consider it of utmost importance that the fully qualified name go in the `name` key. `official_name` would be fine by me. But I’m currently participating in an import where we have both brand names and fully qualified names for thousands of POIs, potentially allowing us to locally achieve more precision _and_ consistency than the competitors named above. It would be sad if we had to toss out all that information and wind up less detailed than those competitors; hopefully we can accommodate that data without forcing data consumers to guess. (The “`brand` `branch`” formula would get it wrong maybe half the time, and this is in the U.S.)

> Yes `branch` tag is still gaining acceptance, but I heard about it a few years ago and it already seemed to have a significant usage at that point.  I believe it's up well over 100k uses today.  Part of what makes this an extra tricky problem is that `name` tag is _special_ and often the thing that gets rendered on map pins, so most users will type whatever they want into there in order to get it rendered.  That makes it not a great tag to use as the "primary key" for a POI.

Having editor support for the `branch` and `official_name` keys could take some of the pressure off the `name` key, at least for POI types where the branch name is clearly secondary to the brand name. openstreetmap/id-tagging-schema#215 and openstreetmap/id-tagging-schema#249 add fields to iD for the official and branch names, respectively.

**Comment by Adamant36** [comment]
> Keep it simple I say.

One more tag doesn't complicate things that much. 

> If consumer wants to read brand and branch then that's fine, if not then combine them in the name value.

The problem is we don't really know what consumers prefer. Just what the opinions of you and a few other Norwegian mappers do. For all we know consumers might not actually prefer your method of tagging the name though. 

> When searching in an app and getting a list, having the full name is kind of essential.

Not really. Most of the world doesn't have the location in the name and we do perfectly fine. I find businesses in California with OSM all the time without issue and we don't do that way. Except in a few rare instances, like with hotels. That's not because we have to though or else everyone in America will run screaming from the project like your acting. 

> This might result in less people picking apps based on OSM data as they find them inferior to say Google maps (From what I can tell they have the full name in the name field for a POI). They might not understand what OSM is and just think its a shitty app and move on.

Sure, it might result in less people picking up apps based on OSM data, but there's zero evidence that it has in places where the name doesn't include the location. While on the flip side there's zero evidence that including it increases usage of OSM data. hat OSM isn't a direct competitor to Google Maps anyway. Most OSM "map consumers" are actually "geographical data consumers" and aren't using OSM as a map directly. So your average Google Maps user isn't really the intended audience. Like @1ec5 mentioned, one of the use cases for a fully qualified name (which is large but mostly ignored in these discussions) has little to do with rendered maps.

**Comment by Gazer75** [comment]
By using the combination of brand and branch in the name field the developers can pick how they want to index without loosing important information.

So if I am in my car and is supposed to meet someone at a specific shop, which would be given with brand and location here, and I start searching only to find 10 in a list of a brand but nothing else. How do you suggest I find the right one?
There is no indication other than perhaps an address that have no meaning to me as I don't know the area and street names.

Just because this is not common practice in the US doesn't mean the rest of the world should do it like you do.
Being told by someone almost on the other side of the globe how to tag stuff in my country doesn't feel right.
If you want to only use brand name in the name tag in the US then please do, but that is not common practice here.

The branch definition is really not a thing here for regular shops, but to help internationally we used it to make it clear.
The shops have a name that consists of the brand and the location, that's it. If they don't use that name on the building shouldn't matter, its probably a cost saving thing not having to put up more lit signs than needed.
Which to me is a good thing, to many big logo signs and light pollution as it is.

Some grocery brands use simple non lit signs for the location name. 
Nærbutikken is one example of this. A brand of more rural and small grocery stores.

**Comment by NKAmapper** [comment]
Thank you for your edits to the supermarket and convenience files, @bhousel. Much appreciated. These are the other Norwegian brands in the index which would need a similar preserveTags rule:

_Shop:_
Trade: Bygger’n
Plumber: Bademiljø, Comfort
General: Europris
Agrarian: Felleskjøpet
Garden centre: Hageland, Plantasjen
Hardware: Jernia
DIY: Biltema
Furniture: Bohus
Alcohol: Vinmonopolet
Sports: XXL
Mobile phone: Mobit, Telenorbutikken
Tyres: Dekkman
Optician: Synsam
Car parts: Bilxtra
Books: Norli
Clothes: Carlings
Shoes: Din Sko

_Amenitiy:_
Pharmacy: Apotek 1
Restaurant: Beefeater, Egon
Post office: Posten Norge
Fitness centre: Sats
Car repair: Mekonomen
Cafe: Espresso House

Is it possible to have the same rule for the Norwegian stores of the Spar and the 7-Eleven brands? These two chains are not part of the international organisation in Norway. They have a different owner and operator in Norway, which have just acquired the right to use the logo (so the wikipedia reference is not correct either).

**Comment by Adamant36** [comment]
> update, I did this

Not to beat a dead horse, but I'm sort of bummed I didn't get my question about Starbucks' in Barns & Nobles answered because I asked the manager my local Barns & Nobles about it and he said they are actually "Barns & Nobles Cafe" even if though they use the Starbucks branding. So it might be something worth looking into and changing. I'll probably open an issue for it at some point if no one else does, but at least the discussion in this one helped clarify things. Even if some people thought it was argumentative. So I appreciate the constructive feedback that was given. As well as @1ec5 clarifying things about the branch tag in the Nominatim issue tracker 👍
