### ISSUE TITLE
Wrong suggestion for Coop (Sweden)

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#5505]
from @JohanEntur on #5500
>We are not regulars, but NKA is really speaking for the rest of us (Norway) here. Individual shop names is a thing, and NKA has put a lot of work into building several import structures (incl. shops) to both populate and keep these POIs up to date in Norway. It would be unfortunate if the presets and users of iD would unwittingly degrade these items.
>
>I can tell you right now, the same issue will be relevant for Sweden:
The suggestion iD gives here is not sound.
![image](https://user-images.githubusercontent.com/33256409/137204218-50041a46-8f3f-4190-a714-c2fd4b916d2e.png)

_Originally posted by @JohanEntur in https://github.com/osmlab/name-suggestion-index/issues/5500#issuecomment-942672822_

**Comment by JohanEntur** [comment]
I don't feel like I either know enough about the subject, despite local knowledge or that I care very strongly - and I can't be bothered with all the argumentation. But basically, if I was mapping out that city and I saw that it had "name=Coop" I would probably re-tag that because that's not how it's known locally. It's Coop @ Palmviken and the official name is "Stora Coop Palmviken", https://www.coop.se/butiker-erbjudanden/stora-coop/stora-coop-palmviken/. I haven't been there for a while but I think the signs on the building will to some extent reflect this (they keep changing the name and the signs).

It is also to differentiate it from the other Coop in town https://www.openstreetmap.org/node/2271656207. I know that it has the branch tag and all that, but the name field irks me :) It doesn't sit right with me.

Either way, the argumentation is the same as in the case with the Norwegian issue, so whatever happens there could be applied here.

I have no problem with the _added_ tags, just the change of the `name` tag.

**Comment by JohanEntur** [comment]
@Adamant36 Why all this aggro? I said argumentation. It means I have no strong feelings on the matter. Leave it.
