### ISSUE TITLE
NSI upgrade changes feature type in iD

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#5610]
When upgrading e.g. [this](https://www.openstreetmap.org/way/382654692) nursing home in iD with `brand` tags, the feature type (as displayed in the top left corner) changes from `Nursing Home` to `Social Facility`. In addition to that, the map icon in iD changes as well. Is this an NSI or an iD issue?

**Comment by bhousel** [comment]
It looks like the iD preset for nursing home is here:
https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/social_facility/nursing_home.json

So if we add ...
```js
        "social_facility": "nursing_home",
        "social_facility:for": "senior"
``` 
...to the NSI tags, it will use the more specific "Nursing Home" preset instead of the more generic "Social Facility" preset.

**Comment by bhousel** [comment]
I did a bit more research and I guess Caritas operate all kinds of social facilities, not just nursing homes, so I'm going to add the "preserveTags" property for these, so they won't be removed if somebody clicks the "upgrade tags" button.

**Comment by kjonosm** [comment]
with the suggested upgrade, no tags are removed from the feature, only `brand` and `brand:*` tags are added. This shouldn't change the feature type...

**Comment by kjonosm** [comment]
[Here](https://www.openstreetmap.org/node/7649568573) is another example

**Comment by bhousel** [comment]
I'm going to close this for now because I don't see a way to improve the display label in iD that doesn't involve multiplying the presets we already generate ("Social Facility - Caritas") into a whole lot of other sub-presets with slightly more specific names ("Nursing Home", "Homeless Center", "Group Home", "Food Bank", etc..)

The tags on the feature are still correct, which is the most important thing.
