### ISSUE TITLE
Citizens Advice in UK

### ISSUE THREAD

**Issue by codeinabox** [osmlab/name-suggestion-index#5868]
I've noticed there is no established standard or preset for Citizens Advice previously known as Citizens Advice Bureau. Given they are an independent charity organisation with 316 branches specialising in giving advice to assist people with legal, debt, consumer, housing and other problems I'd suggest the tag `office=charity` though I am very open to suggestions if there is a more appropriate tag. However I can't see where I'd put this - would I need to create `charity.json` under `brands/amenity`?

There is also the question of the match tags as to date people have been tagging it using:

- amenity=advice
- office=citizens_advice
- social_facility=outreach
- office=lawyer
- office=ngo
- amenity=information
- office=government

**Comment by rjw62** [comment]
Since the branches are intended to be pubic facing for people to attend, I don't think office=* is appropriate. I struggled to find a suitable tagging myself when coming across these while mapping. I think the existing tag social_facility=outreach https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Doutreach fits reasonably well.

**Comment by codeinabox** [comment]
@rjw62 thank you for the suggestion, it sounds like this would be a sensible way to tag them:

```
amenity=social_facility
brand:wikidata=Q5122657
brand:wikipedia=en:Citizens Advice
name=Citizens Advice
social_facility=outreach
```

**Comment by codeinabox** [comment]
@UKChris-osm @rjw62 I've almost got a PR ready for this but not sure on the match tags. To date people have used these tags:
    
* amenity=advice
* amenity=information
* office=charity
* office=citizens_advice
* office=government
* office=lawyer
* office=ngo
* social_facility=outreach

Should I match against all of them or just a subset?

**Comment by bhousel** [comment]
> Should I match against all of them or just a subset?

You can match all of the less-preferred tag pairs, (so I guess everything on that list except for the `social_facility=outreach`).

`matchTags` is used to catch the less-preferred tagging so that the iD validator can suggest an upgrade to the preferred tagging.

https://github.com/osmlab/name-suggestion-index/wiki/Item-Property-Reference#matchnames-matchtags
