### ISSUE TITLE
npm run build is resulting in duplicate IDs

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#5898]
I'm seeing really odd behavior from the npm run build command lately. After updating nsi-collector data and then running `npm run build` I end up with duplicate IDs. The duplicate IDs always seem to be two brand with the same name, but different case. Sometimes it seems like the generic regex should also be removing them.  Here's an example of a failure: https://github.com/osmlab/name-suggestion-index/actions/runs/1595091609

**Comment by UKChris-osm** [comment]
Is this likely due to the NSI having multiple trees? Previously any matches would be grouped as a brand, whereas now they can be split up between brand / operator / network, causing the same name data to appear in different tree files.

I thought ID's were generated from display name + location hash?

If that's the case, then having two brands / operators with the same name set to world (001, nsi-collector default), but in different trees, will I think always cause this issue?

Perhaps display name + location hash + tree hash could be a solution?

**Comment by LaoshuBaby** [comment]
This also affected in https://github.com/osmlab/name-suggestion-index/commit/7631228f3071c9e3df9022170ea79f82c8ad59a4

**Comment by UKChris-osm** [comment]
> This also affected in [7631228](https://github.com/osmlab/name-suggestion-index/commit/7631228f3071c9e3df9022170ea79f82c8ad59a4)

I think this was a RegEx issue that should now be fixed :)

**Comment by bhousel** [comment]
> I'm seeing really odd behavior from the npm run build command lately. After updating nsi-collector data and then running `npm run build` I end up with duplicate IDs. The duplicate IDs always seem to be two brand with the same name, but different case. Sometimes it seems like the generic regex should also be removing them.

Yeah this has been an issue with the build script for a while (maybe a year or more) whenever we process new planet data for the first time. 

The issue is that we build the matching index on _existing_ names, but then when as names get checked, it's matching on the existing index.  This means that if a planet file contains 2 new conflicting names, they both get added at the same time with a duplicate id, and subsequent builds will fail until someone fixes it.  

I kind of mentioned it in the instructions, but I do want to fix it at some point.
https://github.com/osmlab/name-suggestion-index/wiki/Info-for-Maintainers#a-new-challenge

It's sort of a hard problem, and there's only a few humans that actually will run into this.. 😅

**Comment by bhousel** [comment]
I think I fixed this in b297ce2 but haven't actually tested it yet. 
It does basically the same thing, but now takes an initial pass over the names to keep only the most popular spelling. 
We'll know next time we update the nsi-collector data! 🤞

**Comment by tas50** [comment]
Thanks for taking a stab at it. I'll let you know if we see issues in the future.
