### ISSUE TITLE
amenity/pub Wetherspoons update logo

### ISSUE THREAD

**Issue by ThatRobson** [osmlab/name-suggestion-index#5928]
Can we change Wetherspoons logo to their App icon which has a square ratio as the company is not on social media?
![Wetherspoons app icon](https://user-images.githubusercontent.com/25868403/147272812-6e801ee1-0b6e-4d1d-b8e7-7e08dde80b3c.png)
 
![image](https://user-images.githubusercontent.com/25868403/147273039-bbc27bd8-9488-4298-ab15-075ab3a40865.png)

**Comment by UKChris-osm** [comment]
This logo would need to be added to their [Wikidata item](https://www.wikidata.org/wiki/Q6109362) but I did email them a while ago asking if it would be okay, but they never responded unfortunately.

**Comment by arch0345** [comment]
You could probably upload it to the English Wikipedia instead of the Commons - other copyrighted logos like [Taco Bell's](https://en.wikipedia.org/wiki/File:Taco_Bell_2016.svg) are allowed as "the use of low-resolution images on the English-language Wikipedia, hosted on servers in the United States by the non-profit Wikimedia Foundation, of logos for certain uses involving identification and critical commentary may qualify as fair use under the Copyright law of the United States"

**Comment by bhousel** [comment]
I did check on nsi.guide what logos we could extract from their [Wikidata page (Q6109362)](https://www.wikidata.org/wiki/Q6109362):
https://nsi.guide/index.html?t=brands&k=amenity&v=pub#wetherspoon-eaed91

It's weird that it has a commons logo but our script didn't generate a correct URL for it, so there might be a bug.

It also does have a Facebook profile, but the profile is restricted, so we don't pull a logo that way either.  (I've found this sort of profile restriction is common for places involving alcohol).

**Comment by UKChris-osm** [comment]
Could the logo have been skipped due to the dimensions of the image?

**Comment by bhousel** [comment]
> It's weird that it has a commons logo but our script didn't generate a correct URL for it, so there might be a bug.

I just looked into this and pushed a change to `build_wikidata.js` that should fix this logo 
(There may have been other .svg logos that were broken too, I'm not sure).

The P145 claim on [Q6109362](https://www.wikidata.org/wiki/Q6109362) contains `'wetherspoon logo.svg'` (lowercase)
but the actual url should be `'Wetherspoon logo.svg'` (uppercase)

Apparently this mismatch can happen sometimes because the filenames get normalized, but claims aren't updated to match the true filename. We can use Special:FilePath to redirect the user to the real file.
Thanks @jleedev for the solution!

https://osmus.slack.com/archives/CUP8V1Z61/p1641313622080700

**Comment by bhousel** [comment]
I should also add, this change doesn't actually set the logo to the one requested by the OP - that is something that would need to be done on the Wikidata side.  But it does fix it so that the existing logo will work.
