### ISSUE TITLE
Anchor Hanover retirement housing

### ISSUE THREAD

**Issue by codeinabox** [osmlab/name-suggestion-index#6006]
Anchor Hanover provides a lot of retirement housing across England. I've been mapping this as I find it and am wondering about two things: 1) if I am using the most appropriate tags and 2) should we add an operator preset?

An example I recently mapped is https://www.openstreetmap.org/way/934332362

**Comment by codeinabox** [comment]
@UKChris-osm any thoughts on this?

**Comment by UKChris-osm** [comment]
I think you've been tagging this correctly, and I would tag this as an **operator**, rather than a brand personally, but they seem to be trading as simply "_Anchor_" so I would probably go with that, with a "_matchName_" for "_Anchor Hanover_"

amenity=social_facility
operator=Anchor
operator:wikidata=Q65091469
operator:wikipedia=en:Anchor Hanover Group
social_facility=group_home
social_facility:for=senior
