### ISSUE TITLE
"Curio Collection by Hilton" preset gets overwritten by "Hilton" preset

### ISSUE THREAD

**Issue by mxxcon** [osmlab/name-suggestion-index#6018]
Way 265260930
When I open it in iD, I see that it has "Curio Collection by Hilton" preset applied. However, after a couple of seconds iD wants to replace it with just regular Hilton preset. Seems like a conflict?
![image](https://user-images.githubusercontent.com/847140/148470739-b8d888c9-72f8-4595-9550-2ba7c562e52b.png)

**Comment by UKChris-osm** [comment]
I think this is because the name on the object (the Hotel) is to long, and should just be "_Martinique_",  "_Hotel Martinique_", or  "_Martinique New York_", and what's happening is because the name tag includes "_Hilton_", this is why the matcher is suggesting it.

However, I think this might also be because [Curio Collection](https://nsi.guide/index.html?t=brands&k=tourism&v=hotel&tt=curio#curiocollection-779ccb) doesn't contain any real reference to "_Hilton_" and by adding this (maybe as a matchName "_by hilton_") we could remove this incorrect match?

**Comment by arch0345** [comment]
I've added `matchNames` to both this and Tapestry Collection, I'll see if this issue's fixed after the next release

**Comment by arch0345** [comment]
After taking a look at the hotel in question, it looks like iD was trying to match it to Hilton because it's tagged with `operator=Hilton`

**Comment by Adamant36** [comment]
Closing since it seems to be fixed.
