### ISSUE TITLE
UK Amazon Lockers and Amazon Hubs

### ISSUE THREAD

**Issue by jnicho02** [osmlab/name-suggestion-index#6161]
with the shift from `amenity=vending_machine + vending=parcel_pickup` to `amenity=parcel_locker` the UK Amazon Lockers aren't converting in iD as, I believe, amazonhublocker-f85b1f pushes the 'Amazon Hub' brand.

For reference, here in the UK, pickup points in supermarkets, garage forecourts, etc. are branded 'Amazon Lockers' and are generally pickup only with selected lockers accepting parcel returns. The 'Amazon Hub' brand is specifically used for lockers places in the foyer of apartment blocks, etc.

If I select that this isn't an Amazon Hub, then I end up with the brand being marked as `not:brand:wikidata=Q16974764`
<img width="387" alt="Screenshot 2022-02-04 at 09 22 59" src="https://user-images.githubusercontent.com/83251/152509661-e4728514-4fd7-49f3-87b6-efc00c5ab3f5.png">

**Comment by SK53** [comment]
Note that Amazon also use the Amazon Hub brand for third-party counter facilities with no visible branding, such as post offices.

**Comment by arch0345** [comment]
Relates to https://github.com/osmlab/name-suggestion-index/pull/5986#issuecomment-1004183948

**Comment by Lukas458** [comment]
In Germany we have a similar "problem". We have two types of Amazon parcel lockers, some labeled "Amazon locker" and others labeled "Amazon Hub".

I'm not exactly sure what the difference between the two is. But somehow there has to be one, otherwise the two different names wouldn't exist, would they?

What I also find slightly problematic: in the preset for amazonhublocker-f85b1f there is the tag `brand=Amazon Hub`. However, the name of the associated Wikidata item is not "Amazon Hub" but "**Amazon Locker**". 

We then combine both in the tag `name: Amazon Hub Locker`, which I don't find very successful either...
<br>
<br>
> The 'Amazon Hub' brand is specifically used for lockers places in the foyer of apartment blocks, etc.

I think that's the crucial difference in Germany, too. Could it be that we need two presets: one for the hub and one for the locker?
