### ISSUE TITLE
How should we tag acai bowl places

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#6187]
These are currently tagged inconsistently:

- [Everbowl](https://nsi.guide/?id=everbowl-243cad)
- [Oakberry Açaí bowls](https://nsi.guide/?id=oakberryacaibowls-df46eb)

**Comment by codeinabox** [comment]
Good question, if I had to pick a dominant cuisine option I'd go with salad or smoothie. However reading the [Wikipedia entry](https://en.wikipedia.org/wiki/A%C3%A7a%C3%AD_palm#As_a_food_product) the bowls aren't as healthy due to a high sugar content so maybe they warrant their own cuisine entry ie `cuisine=açaí`
