### ISSUE TITLE
Banco Patagonia tags

### ISSUE THREAD

**Issue by pablorodz** [osmlab/name-suggestion-index#6197]
Hi,
I would like to ask if anyone could update/review the brand and name for the bank and atm from Banco Patagonia. These tags are set to only "Patagonia" instead of "Banco Patagonia".

Brand wikidata is Q2882078.

Thanks
Pablo

**Comment by UKChris-osm** [comment]
Hi @pablorodz, thanks for your post.

Having looked at the Overpass query for this entry, they almost all appear green, with the name marked as simply "_Patagonia_", which is likely where the original data came from when the NSI scanned the planet data.

So just to confirm with you, does the Bank trade as "_Banco Patagonia_" locally? Could "_Patagonia_" be a shorter name that local people refer to the bank as - in the same way that people in the UK refer to "_Lloyds Bank_" simply as "_Lloyds_"?

Looking at some Google images and the web site I think you're correct, but because so much of the current data is marked as "_Patagonia_" I just wanted to double check with you?

**Comment by pablorodz** [comment]
Hi there,
As far as I know, it trade as Banco Patagonia. And, as you said, locally we
do call it just Patagonia depending on context, as we do with Lloyds :)

Let me send a message to the local community so someone else could also
confirm this.

**Comment by pablorodz** [comment]
Can confirm the change. The name tags should be "Banco Patagonia"

**Comment by UKChris-osm** [comment]
Thanks for checking @pablorodz - I have made the edit here, which will be live in iD in a week or so, but this won't automatically edit data in OpenStreetMap, so any Banks marked up as "_Pantagonia_" will remain so until edited by someone.

**Comment by pablorodz** [comment]
Thanks! Probably I could do the edits in osm myself.
