### ISSUE TITLE
Bus transit within Lagos

### ISSUE THREAD

**Issue by EOEboh** [osmlab/name-suggestion-index#6243]
The data about bus transit in Africa's largest city needs to be added, alongside every searchable information. Bus Rapid Transit System (BRT) and LagBus which runs from Berger bustop to CMS bustop.

**Comment by LaoshuBaby** [comment]
Hello friend, If you want to add a Bus network to NSI you can try to contribute in `/data/transit/route/bus.json`

Or, you need to tell us the English name of this network (or local language) with a wikidata (If don't exist you need to create one).

> which runs from Berger bustop to CMS bustop

Because I seaech “LagBus” and haven't got any result. And name-suggestion-index don't store specify route information, if you wanna add a route from Berger to CMS, you can create a new relation in osm.org

For more about this project you can see:
https://github.com/osmlab/name-suggestion-index/wiki

Best Regard

**Comment by LaoshuBaby** [comment]
> how to create a wiki data?

![图片](https://user-images.githubusercontent.com/42690037/156494365-37425046-0c2f-48db-bc8c-1cd3bb186564.png)

https://www.wikidata.org/wiki/Special:NewItem

-----
Or you can tell us the full name of this bus network

:)

**Comment by EOEboh** [comment]
Thank you so much.  Haha, i would love to learn something new lol

**Comment by bhousel** [comment]
I was able to find this:
https://en.wikipedia.org/wiki/Lagos_Bus_Rapid_Transit_System
https://www.wikidata.org/wiki/Q6472593

Is this the same one?
It does look like there is not much information there, but it might be it..

**Comment by EOEboh** [comment]
Yes that would serve for this issu
