### ISSUE TITLE
Add Brand - Bread Ahead

### ISSUE THREAD

**Issue by bazoch24** [osmlab/name-suggestion-index#6260]
Hi, 

Sorry if this is the wrong place to post this but i requested to add brand earlier and I received help with this issue (thank you). But I am not sure how to run build, as would this be the second step after requesting add brand?

**Comment by codeinabox** [comment]
AFAIK builds are run at regular intervals. I've raised lots of PRs though never needed to trigger the build

**Comment by LaoshuBaby** [comment]
Hey friend, if a brand in this repository but iD or other editor still give you a warning that contain old data, this is because latest version haven't been publish to [npm registry](https://www.npmjs.com/package/name-suggestion-index). Usually we do this per week.

![图片](https://user-images.githubusercontent.com/42690037/156785228-9a783243-9e52-48d0-9d50-2ccb5235e124.png)

This publish have [a lot of step](https://github.com/osmlab/name-suggestion-index/wiki/Release-Checklist) that only core maintainer can do, which is differ from usually `npm run build`.

Only after a new version published, editor can use new data.

**Comment by bazoch24** [comment]
Thank you so much for clearning that up for me

That all makes sense now 😄

________________________________
