### ISSUE TITLE
Add support for `man_made=pipeline` operators, specifically Southwest Gas (SWG)

### ISSUE THREAD

**Issue by BubbaJuice** [osmlab/name-suggestion-index#6276]
Gas pipeline have operators. Specifically, Southwest Gas should be added to the index under a pipeline.
Website: [https://www.swgas.com/](https://www.swgas.com/)
Twitter: [https://twitter.com/SWGas](https://twitter.com/SWGas)
Facebook: [https://www.facebook.com/southwestgas/](https://www.facebook.com/southwestgas/)
Wikipedia: [https://en.wikipedia.org/wiki/Southwest_Gas](https://en.wikipedia.org/wiki/Southwest_Gas)
Wikidata: [https://www.wikidata.org/wiki/Q7571280](https://www.wikidata.org/wiki/Q7571280)

Support for pipelines has been mentioned in #5499.

**Comment by Hiausirg** [comment]
Strong oppose. I've been mapping thousands of pipeline miles in the southeast (https://openinframap.org/#5.72/30.673/-83.465/L,O), tagged with a variety of operators, especially Florida Gas Transmission, Southern Natural Gas and Atlanta Gas & Light, to name a few. The last thing i need is get suggestions to add totally useless tags everywhere. Such operator names are unique "in the industry", and i'm sure that the normal operator tag is enough to prevent confusions.

**Comment by 1ec5** [comment]
What about gas pipeline operators whose trade names aren’t unique in the industry?

`operator:wikidata` isn’t just for disambiguation. Like `brand:wikidata`, it could help data consumers infer other information that’s only available on Wikidata, such as whether the operator is public or private, or where it’s based, or links to regulatory databases, just to name a few possibilities. It would be surprising to any data consumer if `operator:wikidata` were generally present but not for Florida pipeline operators, requiring a special lookup table for just that subset of values.

**Comment by Hiausirg** [comment]
I'm 99,9% sure that there aren't any pipeline operators with the same (or a very similar) name. Also, i don't think that there are any consumers which use or would use these operator:wiki.. tags ...on pipelines (and powerlines, too). Such tags make sense on chains like McDonalds/IKEA etc., but not on infrastructure. We also don't add "operator:wikidata=Q127743" or similar to roads. 

Isn't there some API on wikidata where you can insert a word and it returns you the code, e.g. a progam sends "Florida Gas Transmission" to WD and WD returns "Q5461387"? If a consumer would really need the wikidata of the operator, it could get it using this way.

"It would be surprising to any data consumer if operator:wikidata were generally present"
- well, they aren't generally present on pipelines, and consumers shouldn't assume this - assume it on stores, but nowhere else.

"An alternative would be to tag every pipeline that the operator operates with a wikidata tag specific to that individual pipeline"
- this can be done on route=pipeline relations, e.g. like https://www.openstreetmap.org/relation/13805393

**Comment by 1ec5** [comment]
> Isn't there some API on wikidata where you can insert a word and it returns you the code, e.g. a progam sends "Florida Gas Transmission" to WD and WD returns "Q5461387"?

Wikipedia has no one-to-one relationship between labels and items. You’re thinking of Special:ItemByTitle, which takes a Wikipedia article title as input. But you don’t seem to be in favor of tagging `operator:wikipedia` either…

**Comment by Hiausirg** [comment]
"Wikidata has no one-to-one relationship between labels and items. You’re thinking of Special:ItemByTitle, which takes a Wikipedia article title as input."
Then it's their task to create such a relationship. Or your task to use the NSI to link to wikidata instead of using the OSM database to link to wikidata.
"But you don’t seem to be in favor of tagging operator:wikipedia either…" 
No, definitely not. Normal wikipedia=* on pipe route relations is enough.

Also, i have no idea why you want to add the operator's wikidata tag to every pipeline, so that "consumers can rely on it". There are multiple thousands of different pipeline operators, so you would have to create thousands of presets AND apply these presets on OSM, until they can rely on any of those tags. It can't be that hard to fill out the operator field without typos...

**Comment by 1ec5** [comment]
It’s a good thing that many Wikidata items can have the same label. It makes little sense to propagate one of Wikipedia’s original shortcomings to projects that can do better.

If you’re really concerned about the scalability of manually creating a Wikidata and NSI entry for each pipeline operator, both projects are amenable to bulk edits. Ultimately, given adequate editor support, even `operator` could be redundant to `operator:wikidata`. For example, a simple SPARQL query can eliminate the need for explicit NSI entries in the first place: https://github.com/osmlab/name-suggestion-index/issues/4768#issuecomment-890462318.

In the meantime, it doesn’t sound like the original post was requesting a great many additional entries in NSI, or to tag every pipeline with its operator.

**Comment by bhousel** [comment]
> I'm 99,9% sure that there aren't any pipeline operators with the same (or a very similar) name.

@Hiausirg You are quite wrong about this.  Take a look at the `operator` values that we have collected from the OSM planet.  https://raw.githubusercontent.com/ideditor/nsi-collector/main/dist/osm/operators_all.json

It's a big file, but just search for "pipeline" and you'll see that the `operator` values for pipelines are just as inconsistent as any other category where people have just been freely typing stuff into the `operator` tag for years.

@1ec5 said:
> In the meantime, it doesn’t sound like the original post was requesting a great many additional entries in NSI, or to tag every pipeline with its operator.

To be clear - I'd be very happy if they were all in NSI, and all had complete information on Wikidata, and I'd love to see every pipeline tagged with its `operator` and `operator:wikidata`. 

> For example, a simple SPARQL query can eliminate the need for explicit NSI entries in the first place

I would like to use SPARQL to collect some categories from Wikidata where it makes sense (currently we only collect values from the OSM planet).  SPARQL doesn't eliminate the need for explicit NSI entries, because SPARQL will never be able to guess what tags OSM people want to use for their stuff.  But I do agree there is a lot of redundancy in the NSI, and if I were building it from scratch today I would do things differently. (#4765 has more on this).
