### ISSUE TITLE
An update on the readme on how the `data/transit/highway/bus_stop.json` should be contributed to

### ISSUE THREAD

**Issue by EOEboh** [osmlab/name-suggestion-index#6309]
There's an empty json file on this particular section, we need more hands on this part of the project. People needs to have a full navigational experience when using OSM.

The maintainers would need to clarify how to input the routes, how specific shoould we be? How should each bus  stop be recorded as there can be multiple bustops with the same name, even in the same city.

**Comment by bhousel** [comment]
We don't actually track specific bus routes or bus stops in this project.  A goal of this name-suggestion-index project is to track all of the transit _networks_ of the world,  including their location where they operate and the preferred OSM tags to use for things within that network. 

The output of this project is "presets" for OSM editors.  When you edit OSM to add a bus stop or a bus route, the editor can make sure that your bus routes and bus stops all have a consistent `network` and `network:wikidata` value set. 

So, to answer your question about the [bus_stop.json](https://github.com/osmlab/name-suggestion-index/blob/main/data/transit/highway/bus_stop.json) file:   There are not bus stop presets in this file because it contains a single template entry:

https://github.com/osmlab/name-suggestion-index/blob/07de9f42de1886c33630b9af274bfaadb9cbff17/data/transit/highway/bus_stop.json#L11-L15

This "template" item is just way of saying "take everything from `transit/route/bus.json` and create a preset that has `highway=bus_stop` tag instead of a `route` tag".

So if you want to ensure that bus routes (and stops) are captured in this index, you can review 
https://github.com/osmlab/name-suggestion-index/blob/main/data/transit/route/bus.json
Make sure the networks you know about are in this file, and that they have correct `network` and `network:wikidata` tags.   

Reviewing the .json files is kind of cumbersome, so we built 
https://nsi.guide/index.html?t=transit

**Comment by EOEboh** [comment]
Thanks for clarifying. Much appreciated

**Comment by EOEboh** [comment]
> There's an empty json file on this particular section, we need more hands on this part of the project. People needs to have a full navigational experience when using OSM.
> 
> The maintainers would need to clarify how to input the routes, how specific shoould we be? How should each bus stop be recorded as there can be multiple bustops with the same name, even in the same city.

Thanks for clarifying. Much appreciated

**Comment by LaoshuBaby** [comment]
This problem is not an isolated case in this project. By extension, `atm.json` and `post_box.json` also use templates, which are inherited from `bank.json` and two `post_office.json` respectively. So if you are surprised to find that there is no bank or post office that you are familiar with, you can find the file in the upper level and add it instead of adding it to the file where the template is applied.

（such as #5640  or #5641 isn't needed）

And thank you for your passion for this project! ♥
