### ISSUE TITLE
Add a USA brand 

### ISSUE THREAD

**Issue by ishovonahmed** [osmlab/name-suggestion-index#6325]
Brand name : ApexBuilt
"American car parts company"
website : https://www.shopapexbuilt.com/
Wikidata : Q111307099

**Comment by m-hue** [comment]
Hi @ishovonahmed,
Looking at the website it appears that they have one location only; the others appear to be independent dealers operating under own name/branding that just happen to sell their products. Do you have additional information that suggests otherwise? Adding an entry to the index for one single location feels a little excessive...

Thanks!

**Comment by ishovonahmed** [comment]
Kindly add this brand... ApexBuilt is a worldwide business company.. They
sell car parts worldwide..

Thanks you.  🌹

**Comment by m-hue** [comment]
When you say "worldwide business company", what specifically do you mean?
a) they sell to customers world wide through their ecommerce website?
b) they sell to customers world wide through a network of (authorized) independent dealers who are operating under own (non-Apexbuilt) branding?
c) they sell to customers world wide through a network of Apexbuilt-branded retail outlets?

only c) would really qualify for addition to the index. However, their website lists 7 locations, 6 of which appear to be independent dealers - that looks more like b)

Thanks,

**Comment by bhousel** [comment]
Hey @ishovonahmed , sorry but I have to close this request - this index is for brands that operate a lot of retail chain locations (things like fast food places like  McDonalds).  If ApexBuilt had something like 50 stores, we would include it, but I dont see evidence of that.

**Comment by m-hue** [comment]
@ishovonahmed  - adding on to what @bhousel said: If a brand is only tied to a product, not to a (network of) location(s), it is not something we're including here.
E.g. Heinz tomato ketchup, Colgate, Bud Light, Kleenex, ... are all popular US brands (of products), but since there's no locations/sites/retail outlets operating under that branding, we do not include them in the index. Even if Heinz, Colgate... decided to open a factory outlet or two under own branding, we still wouldn't include them. Once we start seeing a significant number of Heinz-branded ketchup bars (or specialty ketchup stores, ...) popping up, we'd add Heinz. 
As bhousel mentioned, 50 locations is a good ballpark number for something being considered significant enough (but 50 hasn't always been treated as a hard threshold).

**Comment by ishovonahmed** [comment]
Got it. Kindly add it..
