### ISSUE TITLE
Nothing Bundt Cakes => pastry?

### ISSUE THREAD

**Issue by michaelblyons** [osmlab/name-suggestion-index#6382]
NSI has "Nothing Bundt Cakes" as `shop=bakery`, but I'm vaguely suspicious that it belongs to `shop=pastry` instead, at least from a reading of the English wiki for the tags. Bakery apparently implies that at least some non-sweet breads are available.

It's a little frustrating that the `shop=confectionery` wiki has "cakes" in its first paragraph of inclusion, and then sends you to `shop=pastry` for cakes in the second paragraph.

**Comment by 1ec5** [comment]
The name in this case very clearly rules out `shop=bakery`, doesn’t it. 🙂 `shop=pastry` sounds like a good fit. I assume a confectioner would sell cakes in a broader sense or as part of a broader variety of sweets, but not just the kinds of cakes one associates with a baker.

**Comment by bhousel** [comment]
> It's a little frustrating that the shop=confectionery wiki has "cakes" in its first paragraph of inclusion, and then sends you to shop=pastry for cakes in the second paragraph.

Yes the over-specification of some shop types really is confusing for mappers! 😄 

NSI has a useful concept called `matchGroups` that allows the matcher to treat similar tags as the same. So if someone does create a "Nothing Bundt Cakes" as a `cafe` or `bakery` we can encourage them to use `shop=pastry` instead.

In [2756510](https://github.com/osmlab/name-suggestion-index/commit/27565100e63f2b43e4c731da0f0db363886e37c6) I moved all the "confectionery" types into more generic "food" matchGroup, since there really is a lot of overlap with these.

```js
    "food": [
      "amenity/bar",
      "amenity/cafe",
      "amenity/fast_food",
      "amenity/ice_cream",
      "amenity/pub",
      "amenity/restaurant",
      "shop/bakery",
      "shop/candy",
      "shop/chocolate",
      "shop/coffee"
      "shop/confectionary",    // we can match this common misspelling too!
      "shop/confectionery",
      "shop/food",
      "shop/ice_cream",
      "shop/pastry",
      "shop/tea"
   ]
```
