### ISSUE TITLE
Warning for duplicates in multiple trees when there isn't

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#6409]
This is the warning I got when running `npm run build`:
```
⚠️   Warning - matchIndex errors:
----------------------------------------------------------------------
  `key/value/name` occurs multiple times in the match index.
  To resolve these, make sure the key/value/name does not appear in multiple trees
    (e.g. `amenity/post_office/ups` should not be both a "brand" and an "operator"
----------------------------------------------------------------------
Duplicate cache key "amenity/post_box/中華郵政" in trees "operators" and "brands", check items: chunghwapost-bed6e8
Duplicate cache key "amenity/post_box/chunghwapost" in trees "operators" and "brands", check items: chunghwapost-bed6e8
Duplicate cache key "amenity/post_box/tionghoaiucheng" in trees "operators" and "brands", check items: chunghwapost-bed6e8
Duplicate cache key "amenity/post_box/中華郵政" in trees "operators" and "brands", check items: chunghwapost-bed6e8
```

**Comment by LaoshuBaby** [comment]
I haven't found Chuanghwa Post in brands' tree. I only found this in `data/operators/amenity/post_office/中華郵政`

https://github.com/osmlab/name-suggestion-index/blob/2af3fb48c72352581efb741c4bdddc7b3f96cf0d/data/operators/amenity/post_office.json#L1598-L1605

It's Strange.

**Comment by bhousel** [comment]
ok I figured out this issue.. It's caused by this line:
https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/parcel_locker.json#L197

After we made the `brands/amenity/parcel_locker` category, people have been adding `"matchTags": ["amenity/post_box"]` to all the items there.  

That's like saying "We might find this item in OSM mapped as an `amenity/post_box`, but we really want it to be mapped as an `amenity/parcel_locker`".

So in the case of "Chunghwa Post", this is complicated because they do actually operate post boxes, but they also operate parcel lockers that are branded as "i郵箱"..  

So I'm going to remove that `matchTags` so that the matcher code doesn't get confused.  If the matcher sees a post_box mapped with "Chunghwa Post", that's ok - it's not really a parcel locker.

(I know it's confusing!)
