### ISSUE TITLE
National Auto company suggested too generally

### ISSUE THREAD

**Issue by bgo-eiu** [osmlab/name-suggestion-index#6517]
I am not too familiar with the NSI system at the moment, so not sure if this issue is related to something here or iD.

I have noticed recently that any POI with "National" in the name will queue a prompt in iD about National Auto even if there is nothing auto related on the feature. (For edits in the United States.) For example, buildings with National Aquarium in the name will have this.

**Comment by bhousel** [comment]
I agree that sounds like a bug, I'll check it out..
National Aquarium:  https://www.openstreetmap.org/way/178328374

**Comment by cotesta** [comment]
Per request I have taken some time, sailed through cities around my area and attempted to find other mistakes that result in similar bugs as this one. It was much more difficult than I thought, as I was certain that scanning a large swath of Columbus would yield dozens of examples, but that was not true.

This first one is from Zanesville, Century National Bank is clearly not a theater (w566778703):
![566778703](https://user-images.githubusercontent.com/103306302/166208082-7584ac7e-79ac-4753-b0cb-b4edc5fd3c12.png)

Next one is from Cambridge, clearly the word "National" is triggering something in the tag detection (w766133385):
![766133385](https://user-images.githubusercontent.com/103306302/166208384-2831c24c-a868-43a8-b646-ea8eee0477d5.png)

### The last four are from Columbus Proper:

The one here is probably triggered by "Columbus", this library serves books, not coffee (w468054106):
![468054106](https://user-images.githubusercontent.com/103306302/166208661-7d7a0e0e-3c30-45fd-bd4b-6c34a8889b69.png)

Second is the EXPRESS theater, obviously not the clothes shop (w160180739):
![160180739](https://user-images.githubusercontent.com/103306302/166208814-5ca57d3a-2005-46b0-b34f-54db37b88f72.png)

Third might not be explicitly related to this problem, but it was something I wanted to note... The suggestion is for the **Car Wash** BP, instead of the convenience store "BP Shop" like it probably should be (w614141270):
![614141270](https://user-images.githubusercontent.com/103306302/166209206-9054ab71-cfc2-4e57-beb3-d721687e6200.png)

Lastly there's a COSI (Center of Science and Industry) building, which, despite the correct Wikidata already in place, is apparently supposed to be a... fast food chain? (w391604018):
![391604018](https://user-images.githubusercontent.com/103306302/166209877-a02c5463-6dbc-43f2-9848-f0841dd13e9b.png)

These examples should hopefully be sufficient to at least help with diagnosing whatever is causing this issue.

**Comment by bhousel** [comment]
I just published v6.0.20220503 and it looks fixed 👍. (see #6535 for the explanation)
I'm not offered the tag suggestion for the National Aquarium w178328374 anymore.

Let me know if the other tag suggestions are looking better now..

Also when reporting issues going forward, please include the OSM id of the feature if you can - it helps me debug the issue faster. 😄
