### ISSUE TITLE
`npm run build` will destroy correct data and add English name to Japanese name

### ISSUE THREAD

**Issue by LaoshuBaby** [osmlab/name-suggestion-index#6788]
After #6787 's merge I use `npm run build` command to auto format the data, but I noticed the Japanese name isn't I just merged.

I manually checked and ensure them, then I run `npm run build` in a clear and up-to-date environment, here is a video:

https://user-images.githubusercontent.com/42690037/179353635-0449b0b1-9d07-4490-8119-776dedb427d0.mp4

(Sorry, old video mistake cut key point, so this is the full screenrecord)

If video can't been play:

![图片](https://user-images.githubusercontent.com/42690037/179353498-0f8be1a3-6caf-4b7b-89d1-dc17dcac1d0f.png)

This may destroy any Japanese name in current data, but I don't know how to do with it. 

I run command on this commit: https://github.com/osmlab/name-suggestion-index/commit/b9a71323af8a3fa157a7b0fceb1d347a7b131f22

@bhousel

**Comment by bhousel** [comment]
Oh I see - yeah it does look like the build script is changing `name:ja` value to be equal to `name` value which contains the mixed ja and en strings (and same with `brand).

I remember I added this behavior a while ago because many validators (JOSM and KeepRight and maybe others) expect that is there is _any_ local tag like `name:XX` one of those local values _must_ match the value in `name`.  We apply this rule to tags like `brand:XX` and `brand` also.

#2245 has a lot more info about it and some screenshot of the warning.

Do you think it would be acceptable for Japanese mapping community if we remove the mixed string values in `name` and `brand` and just keep only the Japanese value?

**Comment by LaoshuBaby** [comment]
Emmm……In fact this is related to HK community. For this issue (Japanese brand in Hong Kong and call themselves only in `ja+en`, the `brand:ja` and `name:ja` is simply Japanese and don't need to obey Hong Kong's `T-Chinese + English` bilingual guideline), those 2 case is very strange.

https://github.com/osmlab/name-suggestion-index/blob/13120890f250f844035df64f13112a5c1b26eedf/data/brands/amenity/fast_food.json#L5845

---

> Do you think it would be acceptable for Japanese mapping community if we remove the mixed string values in `name` and `brand` and just keep only the Japanese value?

I think this suggestion may won't accepted because some place have different bilingual/multilingual rule, they are all documented in https://wiki.openstreetmap.org/wiki/Multilingual_names

For example, in Japan, they use Japanese only, so their `name` will be the same as `name:ja`, like in Mainland of China (only in no ethnic autonomous region), the `name` is equal to `name:zh`, but for HK/MO, for Brussels, for Ethiopia? the `name` tag is combined with some different language, different syntax.

So in this validator's behavior, I personally think it maybe a bit aggressive in multilingual region. Especially the `name` is a exception that not combine with documented language.

---

But I think that I mis-understand the of validator, because it is strange that the validator don't change other HK/MO brand, only in those 3 Japanese brand's HK branch. If so, could you give me a proper example 😂, thanks!

https://github.com/osmlab/name-suggestion-index/blob/13120890f250f844035df64f13112a5c1b26eedf/data/brands/amenity/fast_food.json#L9401-L9422

---

<s>BTW, when HK's friend first enter NSI community, the most thing he do is split HK's brand to `"name":"Chinese English"` type, will we have some fast syntax like `"name":["name:zh"," ","name:en"]`? But this looks hard to maintain, so just forget it.</s>

**Comment by bhousel** [comment]
> But I think that I mis-understand the of validator, because it is strange that the validator don't change other HK/MO brand, only in those 3 Japanese brand's HK branch. If so, could you give me a proper example 😂, thanks!

Yes the validator can be kind of fussy sometimes, and it's not a thing we control - Mostly I am trying to avoid a situation where people add features based on NSI, and then have a validator complain about how NSI tagged things.

The "麥當勞 McDonald's" example you gave is a good example of one that does raise the issue.  Here is a [KeepRight link](https://www.keepright.at/report_map.php?zoom=19&lat=22.30266&lon=114.17227&layers=B0T&ch=0%2C30%2C40%2C50%2C70%2C90%2C100%2C110%2C120%2C130%2C150%2C160%2C170%2C180%2C191%2C192%2C193%2C194%2C195%2C196%2C197%2C198%2C201%2C202%2C203%2C204%2C205%2C206%2C207%2C208%2C210%2C220%2C231%2C232%2C270%2C281%2C282%2C283%2C284%2C285%2C291%2C292%2C293%2C294%2C295%2C296%2C297%2C298%2C311%2C312%2C313%2C320%2C350%2C370%2C380%2C401%2C402%2C360&show_ign=1&show_tmpign=1) to a spot in Hong Kong that does show the issue is raised for a lot of features, including the McDonalds at the corner by Austin Road and Nathan Road.  But that same green "?" warning appears all over the map for a lot of other features too - probably every one mapped in the bilingual style..

<img width="699" alt="Screen Shot 2022-07-18 at 12 51 05 PM" src="https://user-images.githubusercontent.com/38784/179562466-0313a37b-f435-460b-bf65-27c7152aad7d.png">

**Comment by bhousel** [comment]
> What I'm confused is that why current `npm run build` only add `"Sukiya"` to `"name:ja":"すき家"`, but don't add `"McDonald"` to `"name:zh":"麥當勞"`

I think it is this code from the build script:
https://github.com/osmlab/name-suggestion-index/blob/6e93a1c62edb33aea1b378e466711c87f327b4ed/scripts/build_index.js#L501-L503

The intent was to try to set default values for the language and locationset, but I agree that this rule is being too aggressive and it shouldn't overwrite tags, so I'll change it..

**Comment by bhousel** [comment]
Ok I think code I added in 03b393459 should mean that `npm run build` should not overwrite the local tags anymore.. I'm definitely ok with using the bilingual main `name` and `brand` tags if this is what the local communities prefer. 👍
