### ISSUE TITLE
Two unrelated entries are creating a matchIndex error

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#7009]
```bash
⚠️   Warning - matchIndex errors:
----------------------------------------------------------------------
  `key/value/name` occurs multiple times in the match index.
  To resolve these, make sure the key/value/name does not appear in multiple trees
    (e.g. `amenity/post_office/ups` should not be both a "brand" and an "operator"
----------------------------------------------------------------------
Duplicate cache key "amenity/social_facility/roteskreuz" in trees "operators" and "brands", check items: deutschesroteskreuz-da0ff2,croixrougeluxembourgeoise-57c96b
total 1
```
Deutsches Rotes Kreuz and Croix Rouge Luxembourgeoise are creating a matchIndex error despite having different `brand`/`operator`/`:wikidata` values. The only thing they have in common is the matchName `rotes kreuz`

**Comment by bhousel** [comment]
this relates to #5675 and #5625

I ended up moving all the "red cross", "rotes kreuz", and "croix rouge" named items from the operators tree into the brands tree.

Because the tree will determine some other matching behaviors, we can't have these strings duplicated across trees, so because "rotes kreuz" sometimes can appear in the index with different `operator` values, it means that they all act like brands.
