### ISSUE TITLE
operator=AEP and other questions

### ISSUE THREAD

**Issue by Hiausirg** [osmlab/name-suggestion-index#7016]
"American Electric Power" is currently being replaced with "AEP", this is clearly wrong. The name of the company is "American Electric Power Company", not "AEP". Abbreviations can cause confusion and should therefore not be used. Furthermore, the longer version is used more often (and significantly more often before the id editor started replacing it).

And why are
"        
        "aep ohio",
        "aep texas",
        "american electric power",
        "apco",
        "**appalachian power**",
        "i&m",
        "**indiana michigan power**",
        "**indiana michigan power company**",
        "**kentucky power**",
        "pso",
        "**public service company of oklahoma**",
        "**southwestern electric power company**",
        "swepco"
"
also being replaced with AEP, especially the highlighted ones? Only because American Electric is the parent company? Alabama/Georgia/Mississippi Power Companies have the Southern Company as their parent, but no one would even think of generalize everything here and thus worse the accuracy of the data.

And also, where can I find the consensus for wikidata tags on power features, where were those mass changes/"meatbot" edits discussed?

I am absolutely against such tagging as it is a useless duplication of already existing information that just adds more maintenance to do. The point of such wikidata tags is to provide an unique code if the operator tag differs from each other, i.e. when a fast food company operates in multiple countries with different languages/writing systems, but the company is the same, and not to be spammed on every object possible. 
This example dosen't occur on power features, and if, it is extremely rare and dosen't justify the extra tagging/work.
Also, some kind of navigation apps or apps which display brand logos and think they can't use their own OSM-wikidata conversation tables don't display logos of power features anyway, because they're irrelevant there. 

Dont get me wrong, I support unifying operator tags. But don't make it so complicated, just unify the operator tag. Wikidata is not necessary here.

**Comment by 1ec5** [comment]
> "American Electric Power" is currently being replaced with "AEP", this is clearly wrong. The name of the company is "American Electric Power Company", not "AEP". Abbreviations can cause confusion and should therefore not be used. 

Yes, `operator=AEP` is incorrect. By convention, `operator` is either an organization’s trade name or its legal name, which in this case would be either “American Electric Power” or “American Electric Power Company, Incorporated”, respectively. However, “AEP” is incorrect not because it’s an abbreviation but rather because it isn’t one of the names that the company primarily goes by. `operator:short=AEP` would be more appropriate in this case.

As it happens, we already have `operator=American Electric Power` `operator:short=AEP` on `route=power` and `power=generator`:

https://github.com/osmlab/name-suggestion-index/blob/da6ff2c86d4de018565093686647c467f648e4eb/data/operators/route/power.json#L45-L47 https://github.com/osmlab/name-suggestion-index/blob/b4dadd0d1c86e4f6bacd603dad29221859c1eb6d/data/operators/power/generator.json#L308-L310

The incorrect and inconsistent tagging on `power=line` and `power=substation` was most likely an oversight:

https://github.com/osmlab/name-suggestion-index/blob/4459d72f6cd0c42400a508dedfa414811271cae3/data/operators/power/line.json#L60-L61 https://github.com/osmlab/name-suggestion-index/blob/4459d72f6cd0c42400a508dedfa414811271cae3/data/operators/power/substation.json#L90-L91

Note that some companies do use acronyms as their trade names, for example FPL (short for “Florida Power & Light”) and Conrail (Consolidated Rail). In fact, some of AEP’s subsidiaries have initialisms in their legal names, such as AEP Ohio (formally “AEP Ohio Transmission Company, Inc.”, but not “American Electric Power Ohio”).

> And why are
> …
> also being replaced with AEP, especially the highlighted ones? Only because American Electric is the parent company?

That seems to be the case. The index used to have a separate entry for AEP Ohio, but a24bb2449930dadd4a6f25c9ed1e0522f4913f14 for #5224 folded it into an umbrella AEP entry. This was a couple months before @brierjon created a Wikidata item about seemingly every power utility in the country, including AEP’s subsidiaries:

* [AEP Ohio](https://www.wikidata.org/wiki/Q109015295)
* [AEP Texas](https://www.wikidata.org/wiki/Q109015560)
* [Appalachian Power Company](https://www.wikidata.org/wiki/Q109013941)
* [Indiana Michigan Power](https://www.wikidata.org/wiki/Q109016008)
* [Kentucky Power](https://www.wikidata.org/wiki/Q109016012)
* [Public Service Company of Oklahoma](https://www.wikidata.org/wiki/Q109016015)
* [Southwestern Electric Power Company](https://www.wikidata.org/wiki/Q109016018)

These items are all the more reason to avoid overconsolidation. We should restore the AEP Ohio entry and create new entries for the other subsidiaries. If a data analyst wants to find all the AEP-operated infrastructure in the country, they would need to either query for each of these subsidiaries explicitly or perform a federated query that crawls the corporate hierarchy via Wikidata.

Previously, we reached a different conclusion about corporate parents in #2816, but that was about the corporate “operator” of a brand of a feature, which is too tangential to the geographic data we’re supposed to be mapping. That was also before we added a separate `operator` tree to the index.

> And also, where can I find the consensus for wikidata tags on power features, where were those mass changes/"meatbot" edits discussed?

There was never an explicit consensus for `operator` on power features, because `operator` was approved for features in general. In the same vein, no proposal for the `operator:wikidata` key or `*:wikidata` key suffix ever limited it to one group of features. The NSI project’s practice is to couple certain freeform keys with well-established `*:wikidata` tags whenever an accurate QID is available. For non-freeform keys such as `network` on road route relations, I’ve argued that `network:wikidata` should be omitted: #4768.

If you’re interested in arguing against `*:wikidata` tags in general, you’re welcome to start that discussion in a broader venue. We’re overdue for that annual debate. 🤷‍♂️

> The point of such wikidata tags is to provide an unique code if the operator tag differs from each other, i.e. when a fast food company operates in multiple countries with different languages/writing systems, but the company is the same, and not to be spammed on every object possible.

I disagree. `*:wikidata` subkeys have always been envisioned as a supplement to certain freeform keys, including `operator`, without regard for feature types or individual name collisions. The potential for localized `operator` values helps to justify this mechanism, but it’s a general mechanism as opposed to one that’s only used in exceptional cases. I gave another justification above: in Wikidata, each power utility’s item is linked to its corporate parent and so on. Querying for all of AEP’s infrastructure should ideally be as simple as this SPARQL query:

```sparql
SELECT * WHERE {
  # Query OSM for operators of features.
  ?osm osmt:operator:wikidata ?operator.
  # Query Wikidata for
  SERVICE <https://query.wikidata.org/sparql> {
    # The operator as long as it is a subsidiary of AEP.
    ?operator wdt:P749 wd:Q464092.
  }
}
```

We shouldn’t force everyone using Overpass or Sophox to hard-code a company’s org chart inside a query just to get similar results.

Another use case is to obtain contact information for an operator. Tagging `contact:phone` or `operator:website` on each individual stretch of pipeline would introduce needless maintenance overhead compared to a reference to a stable QID.

By the way: “Meatbot” is a derogatory term for an unthinking person. Perhaps you didn’t mean to apply this term to NSI’s end users, who map features individually by hand without the help of automated bulk import tools.

**Comment by Hiausirg** [comment]
"The [guideline on abbreviations](https://wiki.openstreetmap.org/wiki/Names#Abbreviation_%28don't_do_it%29) is clear that we shouldn’t artificially expand an abbreviation beyond common usage, visual or verbal, just to satisfy the guideline."
The long versions, American Electric Power and Florida Power & Light are both common usage.

"There was never an explicit consensus for "operator" on power features, because operator was approved for features in general." I'm not asking about operator, I'm asking about "operator:wikidata". 
"In the same vein, no proposal for the operator:wikidata key or *:wikidata key suffix ever limited it to one group of features."
But there wasn't any discussion to mass-add it everywhere (or on power features).
What the NSI does is adding such tags - hundreds of thousands. Yes, I can choose to ignore the suggestion, but it's only a matter of time before the next one comes along and accepts it. And to my knowledge, such mass edits need to be discussed first.

"We should restore the AEP Ohio entry and create new entries for the other subsidiaries." - Good idea, but until then, it's okay if the data is made worse? Dosen't matter, as long as there is some Wikidata link? These replacements should be removed - with or without Wikidata.

"We’re overdue for that annual debate." - Maybe the debate should have been started before those replacements started?

"Querying for all of AEP’s infrastructure should ideally be as simple as this SPARQL query:"
Why can't they just use the normal operator tags? Or why don't they use the normal operator tags, and match them with QIDs using the NSI data? I'm not a programmer, but wouldn't that be SO MUCH easier & more reliable than having to maintain the more or less same information on potentially millions of objects all the time?

"“Meatbot” is a derogatory term for an unthinking person." I have not meant it derogatory. I used it because the NSI's wikidata additions are done somewhat like a bot - except the executing entity is the contributor who sees a "Here's something wrong, click to fix it" button and presses it - and it takes way longer.

**Comment by arch0345** [comment]
> "American Electric Power" is currently being replaced with "AEP", this is clearly wrong. The name of the company is "American Electric Power Company", not "AEP". Abbreviations can cause confusion and should therefore not be used. Furthermore, the longer version is used more often (and significantly more often before the id editor started replacing it).
> 
> And why are
> "
> "aep ohio",
> "aep texas",
> "american electric power",
> "apco",
> "appalachian power",
> "i&m",
> "indiana michigan power",
> "indiana michigan power company",
> "kentucky power",
> "pso",
> "public service company of oklahoma",
> "southwestern electric power company",
> "swepco"
> "
> also being replaced with AEP, especially the highlighted ones? Only because American Electric is the parent company? Alabama/Georgia/Mississippi Power Companies have the Southern Company as their parent, but no one would even think of generalize everything here and thus worse the accuracy of the data.

Sorry, this was a mistake on my part. In hindsight I should've created separate entries pointing to the same Wikidata item. I'll change the AEP entry to its unabbreviated name and create entries for the subsidiaries linked to their respective Wikidata item once I have some more time. I'll also create a MapRoulette of features that might have been erroneously 'upgraded' as a result of this.

**Comment by Hiausirg** [comment]
Thanks!
I just noticed that "Texas New Mexico Power" is being replaced with "PNM". "PNM" is "Public Service Company of New Mexico" (we should also use the full version here). Both are seperate companies too, "PNM Resources" is the parent.
