### ISSUE TITLE
Please Add a Drive-Through Checkbox to Starbucks

### ISSUE THREAD

**Issue by Zol87** [osmlab/name-suggestion-index#7030]
Please add a drive-through Checkbox to Starbucks for Open Streetmaps because many locations feature a drive through.

**Comment by UKChris-osm** [comment]
Hi @Zol87 - unfortunately adding a checkbox for the drive-thru option isn’t something the NSI can do, that’s more for the [ID Tagging Scheme](https://github.com/openstreetmap/id-tagging-schema/tree/main/data) repository I believe.

**Comment by bhousel** [comment]
Yes, adding that field to the amenity/cafe.json and amenity/fast_food.json files would do it.

https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/cafe.json
https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/fast_food.json

I'm going to close here because it's really an issue for that other project.
