### ISSUE TITLE
Wrong suggestion for bus stop operator

### ISSUE THREAD

**Issue by Dimitar5555** [osmlab/name-suggestion-index#7054]
When I add `network=Софийски градски транспорт` to any bus stop in Sofia (https://www.openstreetmap.org/node/2618710946) iD suggest to add the following tags:
```
+ network:wikidata=Q7257712
+ operator=Столичен автотранспорт ЕАД
+ operator:wikidata=Q112957887
```
The `network:wikidata` tag is fine but the `operator` tags reference the company which is running the bus lines in the city. They do operate some stops but not all of them. Some of the stops are operated by private companies like JCDecaux, others are operated by the city's transport ticketing company (a.k.a. Sofa Urban Mobility Center). The rest are operated by the municipality itself. Is there any way to reflect that in NSI?

**Comment by Lukas458** [comment]
> The network:wikidata tag is fine but the operator tags reference the company which is running the bus lines in the city.

Oh yes, and that's exactly the problem here.
The NSI collects the network and the operator data from the bus lines which are tagged on the roads, when I interpret https://github.com/osmlab/name-suggestion-index/blob/main/data/transit/highway/bus_stop.json correctly.

And then, if NSI finds any fitting operator- oder network-tag on the bus _stops_, it offers to add all the same tags which are on the bus lines, not differentating anything, whether the operator is really the same and so on.
A solution would be to tag all the wrongly catched bus stops with "not:operator:wikidata==Q112957887", but I don't think that's the most sensible and comfortable solution, actually it's not any (only editor/NSI satisfaction?)

**Comment by bhousel** [comment]
Thanks, yes if the network is operated by different operators, it sounds like we should just remove the `operator` tag from this item..

**Comment by Dimitar5555** [comment]
> Thanks, yes if the network is operated by different operators, it sounds like we should just remove the `operator` tag from this item..

That's not a good solution since the bus routes are still operated by that company.

**Comment by Lukas458** [comment]
> That's not a good solution since the bus routes are still operated by that company.

It seems to me that at the moment in the NSI for the bus lines we only have the operator if then together with network, i.e. if then only the combination of network + operator is currently possible, and as we have seen here only if that is also the case for which highway=bus_stop fits. 

Putting the operator separately for bus routes in the NSI is a new step, I think.

**Comment by bhousel** [comment]
Oh ok, I understand now - I did it a different way in 65483cc
The `operator` tag can stay on the bus routes but be removed for this brand only on the bus stops.

We have a similar example with post offices and post boxes where people wanted some special override rules.  #6919
