### ISSUE TITLE
Duplicated Item

### ISSUE THREAD

**Issue by DiogoBaptista98** [osmlab/name-suggestion-index#7077]
Why have you changed the Shell Wikidata item number? Looks like someone have duplicated the item in a wrong way.

This is the original one
Shell (Q154950)
https://www.wikidata.org/wiki/Q154950

This is the duplicated one.
Shell (Q110716465)
https://www.wikidata.org/wiki/Q110716465

Please replace the item with the correct and original number.

**Comment by bhousel** [comment]
This got changed in d91684d by @1ec5 , I assume for a good reason. 

It's become kind of common for fuel brands to live on as their own thing and get transferred to another company even after their original companies get dissolved - or to operate under a different "shell" companies in different parts of the world.  So , I dont know the specifics of how Shell is working around the world, but I would assume that Wikidata has it represented accurately and the QIDs are correct.

I guess relates to: #3154, #4109, #5620, #6292

**Comment by 1ec5** [comment]
Like OSM features, Wikidata items sometimes go through iterations of additional detail. (Micro-dataing?) In this case, Shell’s corporate restructuring [in 2005](https://www.wikidata.org/wiki/Q110716465#P127) made it necessary to distinguish the brand from the corporate parent. Because Wikidata is now making this distinction, Q154950 is only correct as an `operator` and `owner` on Shell’s relatively few owned-and-operated stores, while Q110716465 is the correct `brand` for any Shell-branded location.

Ideally, Wikidata would aim to maintain separate items for brands and their corporate owners, just as ideally it would maintain separate items for administrative areas, populated places, and their governmental authorities, but in practice these concepts get conflated until someone gets around to deconflating them. I don’t think there’s an active push to create all these separate items en masse, so the churn should be limited to Shell for now.
