### ISSUE TITLE
Add Yunnan Rural Credit Cooperatives

### ISSUE THREAD

**Issue by kcx36** [osmlab/name-suggestion-index#7105]
A very common local bank.

labels:

amenity=bank
name=云南省农村信用社
official_name=云南省农村信用社联合社
name:en=Yunnan Rural Credit Cooperatives
name:zh=云南省农村信用社
website=http://www.ynrcc.com/
wikidata=Q114321959

**Comment by LaoshuBaby** [comment]
关于农村信用社的问题之前中国社区曾经讨论过，只有成规模且地区性统一的农村信用社才加入NSI，县级和地级的太零散就不会加入。
请确认一下，云南省全省的农村信用社在招牌上都使用“云南省农村信用社”的名字，而不是随着具体的县市地市改变。（如果符合那就收录）

---
machine translation:

The issue of rural credit cooperatives has been discussed in the Chinese community before. Only rural credit cooperatives that are large-scale and regionally unified will join the NSI, and those that are too scattered at the county and prefecture levels will not join.
Please make sure that all rural credit cooperatives in Yunnan Province use the name "Yunnan Rural Credit Cooperatives" on their signboards, rather than changing with specific counties, cities, prefectures and cities. (if applicable, record it)

**Comment by kcx36** [comment]
> 

满足“成规模且地区性统一”。高德地图随机搜索一个云南县名+“云南省农村信用社”，均有多个结果。且每个办事处都是写有“云南省农村信用社”的统一式样招牌。
