### ISSUE TITLE
Add TSB Wikidata Name/Description Official Website Social Links

### ISSUE THREAD

**Issue by OumKaZa** [osmlab/name-suggestion-index#7328]
Wikidata Name/Description

Thai Smile Bus
[Q115052890](https://www.wikidata.org/wiki/Q115052890)

Official Website - https://www.thaismilebus.com/

Social Links - Facebook: https://www.facebook.com/Thaismilebusofficial

**Comment by UKChris-osm** [comment]
According to the [Wikidata](https://www.wikidata.org/wiki/Q115052890) this entry already existed in the index at some point? Or did you add that @OumKaZa??

**Comment by OumKaZa** [comment]
> According to the [Wikidata](https://www.wikidata.org/wiki/Q115052890) this entry already existed in the index at some point? Or did you add that @OumKaZa??

mean add on Name Suggestion Index page - bus route.

**Comment by OumKaZa** [comment]
> 

Wikidata Name/Description, Official Website, Social Links column on NSI page.

**Comment by LaoshuBaby** [comment]
> mean add on Name Suggestion Index page - bus route.

I received your reply in #7321 but can't see it on GitHub

![图片](https://user-images.githubusercontent.com/42690037/200153050-8a3e1636-f506-4731-a402-f55bc8def58b.png)

If you means add those 2 tag in NSI preset and automatically add them when edit a OSM element, you can read our [judge case](https://github.com/osmlab/name-suggestion-index/wiki/Judge-Case), and those detailed information isn't common enough, those may have differ in different branch shop so that need a on ground survey.

**Comment by UKChris-osm** [comment]
[TSB](https://nsi.guide/index.html?t=transit&k=route&v=bus&tt=tsb#tsb-43cc75) appears completed now.
