### ISSUE TITLE
Add Cofidis 

### ISSUE THREAD

**Issue by DiogoBaptista98** [osmlab/name-suggestion-index#7413]
Please add Cofidis to France Belgium, Spain, Portugal, Italy, Czech Republic, Greece and Hungary. https://www.wikidata.org/wiki/Q1106920

**Comment by LaoshuBaby** [comment]
Hello, I looked at en-wikipedia and found "Cofidis specialized in the [consumer credit](https://en.wikipedia.org/wiki/Consumer_credit) business of the [3 Suisses Group](https://en.wikipedia.org/wiki/3_Suisses). It has expanded since then."

Currently only 7 elements in OSM named after this, some are "office=insurance" while another "office=financial".

I want to know which tag will you choose.
