### ISSUE TITLE
Start moving telecom companies from `shop/mobile_phone` to `shop/telecommunication`

### ISSUE THREAD

**Issue by Dimitar5555** [osmlab/name-suggestion-index#7505]
Currently ~85-90 of the 111 brands in `shop/mobile_phone` are telecom companies. IMHO it would be good to move them to `shop/telecommunication` in order to not have two entries for the same object (which is the case for some of them) and to have a clear separation between the two tags.

**Comment by bhousel** [comment]
This seems like kind of a big change.. Has it been discussed anywhere else?
In the past we have used:
- `shop/mobile_phone` (most stores) where mobile phone service is their main offering (like Verizon or T-Mobile)
- `shop/telecommunication` (kind of rare) where wired internet is their main offering (like CenturyLink or Xfinity)

**Comment by Dimitar5555** [comment]
> This seems like kind of a big change.. Has it been discussed anywhere else?

I don't think that it has been discussed.

> In the past we have used:
> 
>     * `shop/mobile_phone` (most stores) where mobile phone service is their main offering (like Verizon or T-Mobile)

`shop=mobile_phone` is for shops that primarily sell mobile phones and accessories but not mobile services (they don't have the physical and financial capacity to do it). Some telecoms do sell phones and accessories but that's not their main business.

>     * `shop/telecommunication` (kind of rare) where wired internet is their main offering (like CenturyLink or Xfinity)

Telecommunication includes a lot more communications like wired and wireless internet, cable TV, IPTV, satellite TV, stationary phone links.

**Comment by Adamant36** [comment]
> shop=mobile_phone is for shops that primarily sell mobile phones and accessories but not mobile services (they don't have the physical and financial capacity to do it).

I can't speak for anywhere outside of the United States, but as far as I know most mobile phone stores sell mobile services these days, including internet. Except for maybe the small, single employee kiosks you around sometimes that sell phone accessories, but they are really rare, the exception to the rule, and shouldn't be tagged as shop=mobile_phone IMO anyway. Maybe shop=electronics since they usually sell other things (Now that I think about it, I think some of them actually are tagged that way), but that's besides the point. The point is, most or all mobile phone stores out there sell services along with the phone. Especially in Africa BTW since they do everything with texting and prepaid cards. It's pretty easy to find kiosks selling pre-paid phones and/or recharge cards there.

**Comment by Dimitar5555** [comment]
> as far as I know most mobile phone stores sell mobile services these days, including internet

Is that service operated by the store retailer or by an actual telecom?

> or all mobile phone stores out there sell services along with the phone

Are you sure that it's not the opposite? When you get a new service, telecoms try to sign you up on a new phone. Usually it's not possible to buy a phone from a telecom without a service. In the rare cases where it is possible, it will cost you double or more. On the other hand, if you go to an electronics shop, you can buy any phone you like and nobody will offer you a service (except if there is a telecom sales representative in the shop which is very rare). Then you are free to go to any telecom to get a service.

**Comment by Adamant36** [comment]
> Is that service operated by the store retailer or by an actual telecom?

The operator of the cell towers doesn't really matter here. That's not what we are tagging. Like [Cricket Wireless](https://www.cricketwireless.com/) is owned and operated by AT@T, but we still tag them as shop=mobile_phone + name=Cricket_Wireless, without indicating the connection to AT@T. Partly because it's pointless, also it's impossible to dig through, but also at the end of the day no one cares. At least not that I'm aware of. So no the service isn't operated by the store retailer, but that doesn't matter in the slightest. Nor is it something we could tag anyway. Really, 99% of the time they are just wholesalers and the operator is 15 shell companies down the chain. That's true even in cases where it's a supposedly a branded store ran by the actual telecommunications company. 

> When you get a new service, telecoms try to sign you up on a new phone. Usually it's not possible to buy a phone from a telecom without a service.

I mean, I guess that would be true if you go down to your local CenturyLink or Xfinity office since cell phone is not their main product, but so what? They are already not being tagged as mobile phone stores. So I don't see why it matters. My local family ran post office sells mobile phones to. At the end of the day I don't think a business selling mobile phones or mobile services automatically makes them a mobile phone or telecommunications shop. It's obviously more nuanced than that. 


> if you go to an electronics shop, you can buy any phone you like and nobody will offer you a service (except if there is a telecom sales representative in the shop which is very rare). Then you are free to go to any telecom to get a service.

I assume your talking about un-locked phones. They aren't really sold in the United States except on Ebay and at least when I've bought one I've had to order it from China. Most mobile phones are locked to a specific provider. At least that's been my experience. Like I can't go into T-Mobile and buy a phone off of them that will work out of the box with MetroPCS even though it's essentially the same company at this point.

**Comment by Dimitar5555** [comment]
> > Is that service operated by the store retailer or by an actual telecom?
> 
> The operator of the cell towers doesn't really matter here. That's not what we are tagging. Like [Cricket Wireless](https://www.cricketwireless.com/) is owned and operated by AT@T, but we still tag them as shop=mobile_phone + name=Cricket_Wireless, without indicating the connection to AT@T. Partly because it's pointless, also it's impossible to dig through, but also at the end of the day no one cares. At least not that I'm aware of. So no the service isn't operated by the store retailer, but that doesn't matter in the slightest. Nor is it something we could tag anyway. Really, 99% of the time they are just wholesalers and the operator is 15 shell companies down the chain. That's true even in cases where it's a supposedly a branded store ran by the actual telecommunications company.

The connection to AT@T is not relevant. Cricket Wireless provides mobile services using cell towers (be it their own or other company's cell towers) which makes their main business telecommunication, not phones.

> > When you get a new service, telecoms try to sign you up on a new phone. Usually it's not possible to buy a phone from a telecom without a service.
> 
> I mean, I guess that would be true if you go down to your local CenturyLink or Xfinity office since cell phone is not their main product, but so what? They are already not being tagged as mobile phone stores. So I don't see why it matters.

That's the case of CenturyLink and Xfinity, but not for [Cosmote](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#cosmote-d5175a), [O2](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#o2-8befd0), [Telstra](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#telstra-bae8bc), [Turk Telekom](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#turktelekom-0b23a0), [Turkcell](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#turkcell-0bab4d), [Vodafone](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#vodafone-d7631b), [Билайн](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#beeline-3f097a), [MTS](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#mts-3162ba) and at least 3-4 dozen more.

> My local family ran post office sells mobile phones to. At the end of the day I don't think a business selling mobile phones or mobile services automatically makes them a mobile phone or telecommunications shop. It's obviously more nuanced than that.

The difference is that post offices don't own or operate cell towers. The post office company probably had an agreement with some telecom to sell their SIM cards but that doesn't mean that they are telecoms.

> > if you go to an electronics shop, you can buy any phone you like and nobody will offer you a service (except if there is a telecom sales representative in the shop which is very rare). Then you are free to go to any telecom to get a service.
> 
> I assume your talking about un-locked phones. They aren't really sold in the United States except on Ebay and at least when I've bought one I've had to order it from China. Most mobile phones are locked to a specific provider. At least that's been my experience. Like I can't go into T-Mobile and buy a phone off of them that will work out of the box with MetroPCS even though it's essentially the same company at this point.

Locked phones are not very common in Europe if they are even legal. By electronics shop I mean a shop that sells electronics only (washing machines, fridges, dryers, TV sets, computers, phones etc.) and accessories/repair kits for them.

**Comment by Adamant36** [comment]
> The connection to AT@T is not relevant. Cricket Wireless provides mobile services using cell towers (be it their own or other company's cell towers) which makes their main business telecommunication, not phones.

I agree as far as mapping goes. The reason the connection to AT@T is relevant this conversation though is because you asked me who the operators of the service are, the retailer or an actual telecom. So I brought up how Cricket Wireless is owned by AT@T to illustrate that there is no "operator" in that case. At least to any degree that matters. Otherwise, since you brought it up who do you think the operator there is. Cricket Wireless, AT@T, or whoever maintains the cell towers? Also what relevance does it have to this? 

> That's the case of CenturyLink and Xfinity, but not for [Cosmote](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#cosmote-d5175a), [O2](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#o2-8befd0), [Telstra](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#telstra-bae8bc), [Turk Telekom](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#turktelekom-0b23a0), [Turkcell](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#turkcell-0bab4d), [Vodafone](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#vodafone-d7631b), [Билайн](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#beeline-3f097a), [MTS](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#mts-3162ba) and at least 3-4 dozen more.

I haven't looked into it that much, but as far as I know at least with Vodafone they have stores that mainly sell mobile phones and others that just sell "services." Maybe you could argue we should create a separate shop=telecommunication entry in that case, but it's not an either or thing. Let alone one where we simply re-tag 90 of the 111 brands currently tagged as shop=mobile_phone just because they are broadly speaking telecommunications companies or part of the telecommunications industry. The general format of their stores and what they actually selling IRL also matters. 

Like look at this way, most people go to T-Mobile stores to buy mobile phones and mobile phone services. They sell mobile phones in most or all of their stores. That's what people mainly or only go there for. The fact that they might try to upsell a person on getting Wi-Fi service when they buy a phone doesn't mean the particular store is magically a "telecommunications shop." Maybe you could argue that's the case with some European brands, but your saying 99% of the companies shop/mobile_phone should be re-categorized. A better way to go would be to open individual issues for the ones you think are actually telecommunication shops. Then the specifics could be hashed out by locals or whatever. I don't think anyone would have an issue with that. I'm sure some, like Vodafone, could use clarification. But as things stand this isn't something that can be done in bulk through a single issue just because mobile phone companies happen to be in the telecommunications industry. That's not how this or tagging more generally works. Sorry.

**Comment by Dimitar5555** [comment]
> I agree as far as mapping goes. The reason the connection to AT@T is relevant this conversation though is because you asked me who the operators of the service are, the retailer or an actual telecom. So I brought up how Cricket Wireless is owned by AT@T to illustrate that there is no "operator" in that case. At least to any degree that matters. Otherwise, since you brought it up who do you think the operator there is. Cricket Wireless, AT@T, or whoever maintains the cell towers?

The operator doesn't matter. What matters is that AT&T has gotten license to operate on specific frequency band. Then AT&T has decided to sublicense it so that Cricket Wireless can use it as well. Both companies offer celuar services therefore both are telecoms.

> > That's the case of CenturyLink and Xfinity, but not for [Cosmote](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#cosmote-d5175a), [O2](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#o2-8befd0), [Telstra](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#telstra-bae8bc), [Turk Telekom](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#turktelekom-0b23a0), [Turkcell](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#turkcell-0bab4d), [Vodafone](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#vodafone-d7631b), [Билайн](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#beeline-3f097a), [MTS](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#mts-3162ba) and at least 3-4 dozen more.
> 
> I haven't looked into it that much, but as far as I know at least with Vodafone they have stores that mainly sell mobile phones and others that just sell "services." Maybe you could argue we should create a separate shop=telecommunication entry in that case, but it's not an either or thing. 

How many mappers would know or even care to see what's the difference between "Company A Telecommunication shop" and "Company A mobile phone shop"? 

> Let alone one where we simply re-tag 90 of the 111 brands currently tagged as shop=mobile_phone just because they are broadly speaking telecommunications companies or part of the telecommunications industry. The general format of their stores and what they actually selling IRL also matters.

There is no such thing as "broadly speaking telecommunications companies or part of the telecommunications industry". Telecommunications are quite regulated in most countries and require at least one license to operate any of them.

> Like look at this way, most people go to T-Mobile stores to buy mobile phones and mobile phone services. They sell mobile phones in most or all of their stores. That's what people mainly or only go there for. The fact that they might try to upsell a person on getting Wi-Fi service when they buy a phone doesn't mean the particular store is magically a "telecommunications shop."

It seems like this may be valid mainly in the USA. Most people in Europe go to a telecom store to get a new contract and then they may get offered an phone. That doesn't magically make the store `shop=mobile_phone`. Sure, they are some phones on display, but that does not mean that it is `shop=mobile_phone`, since most money come from services.

> Maybe you could argue that's the case with some European brands, but your saying 99% of the companies shop/mobile_phone should be re-categorized.

It's 81% in the worst case.

> A better way to go would be to open individual issues for the ones you think are actually telecommunication shops. Then the specifics could be hashed out by locals or whatever. 

I'm sure that there would be someone who will go through all of these issues and comment on each one.

> I don't think anyone would have an issue with that. I'm sure some, like Vodafone, could use clarification. But as things stand this isn't something that can be done in bulk through a single issue just because mobile phone companies happen to be in the telecommunications industry. That's not how this or tagging more generally works. Sorry.

Most of them have never been a mobile phone company in the first place. A mobile phone company is Huawei, Apple, Samsung etc. I'm talking about telecom companies which have been added in `shop=mobile_phone` due to the lack of better tag for them at that time.

**Comment by Adamant36** [comment]
> The operator doesn't matter.

Then why did you ask me who the operators are then? 🙄 

> Both companies offer cellular services therefore both are telecoms.

I disagree. Otherwise there'd essentially be no such thing as mobile phone store. That said, we aren't what tagging/mapping what the company is, we are tagging/mapping what type of shop it is. I'm sure you get the difference. Like to float an analogy, there's super markets that also sell gasoline and/or have pharmacies. Walmart being one example. How those are currently tagged/mapped is that the gasoline locations are mapped as amenity=fuel, amenity=pharmacy, and so on and so forth. Obviously Walmart gas stations and pharmacies aren't mapped/tagged as shop=supermarket because Walmart is in the grocery industry. 

Like I said, it's more nuanced then just re-tagging everything with the word Vodafone into it to shop=telecommunication "because telecommunications" or whatever. Especially if you think we should do it in mass and without considering the facts on the ground. But be my guest and open an issue for Vodafone or any other company that you think is tagged wrong or needs more discussions. I'm sure some of them could be tagged better or differently 👍 

> How many mappers would know or even care to see what's the difference between "Company A Telecommunication shop" and "Company A mobile phone shop"?

Probably a lot. There's at least five people this conversation so far that do. Conversely, how many people in the world would be able to find their local mobile phone store on the map or in the database if it was re-tagged to shop=telecommunication? I know at least for the United States no one would, because we don't call mobile phone stores telecommunication shops. Regardless of it's a shop owned by a telecommunications company or not. Maybe people in a random Eastern European do, but it's clearly not the norm. In the meantime your saying 90% of them should be re-tagged. Not just ones in your niche area where people call them telecommunications shops. I don't have a problem with those being re-tagged, but again, it should be done on an individual basis after some discussion about it takes place. You can start with Vodafone or keep beating this clearly dead horse. It's your call. 

> Sure, they are some phones on display, but that does not mean that it is shop=mobile_phone, since most money come from services.

What makes something a mobile shop then and how exactly would you know where most money the shop makes comes from anyway? If I were to guess most the money those places make is in selling cheap discount/pre-paid phones and cheap accessories. Sure maybe people will pay the initial cost of setup in the store, but then their paying the monthly bill online or over the phone and in the meantime the store has sold 20 USB cables or MicroSD cards before the costumer has even gotten to their car. Even if you were take the average costumer, most of what they spend is on the upsold physical items they toss in as "bonuses" to new costumers.  

> I'm sure that there would be someone who will go through all of these issues and comment on each one.

Sure the process is slow and sometimes people don't comment on certain issues, but that's just how the consensus process works. This is clearly dead on arrival and IMO that's your next best avenue to have the businesses re-tagged. Take it or leave it. I don't really care, but I think you have a better shot doing that then just trying to continue milking something out of this issue. People are always more willing to do something if done it's small, digestible bites though and you don't really need people to comment on every single one anyway. Just the majority, if even. Then the other ones will probably get re-tagged over time on their own once the precedent is set. 

> Most of them have never been a mobile phone company in the first place. A mobile phone company is Huawei, Apple, Samsung etc. I'm talking about telecom companies

[Key:shop](https://wiki.openstreetmap.org/wiki/Key:shop) "Use shop=* to mark the location of a [shop](https://wiki.openstreetmap.org/wiki/Shops) and **the products that it sells**." Not to be rude, but what part of **the products that it sells** has to do with what industry the company that runs the shop is in?

**Comment by Dimitar5555** [comment]
> Then why did you ask me who the operators are then? 🙄

In order to determine what kind of shop it is.

> I disagree. Otherwise there'd essentially be no such thing as mobile phone store. That said, we aren't what tagging/mapping what the company is, we are tagging/mapping what type of shop it is. I'm sure you get the difference. 

There would be at least one dozen of mobile phone shops. See [Germanos](https://www.germanos.gr), iStore, iShop, Huawei, Phone House, Алло, Евросеть, Honor for a few examples of proper `shop=mobile_phone`.

> Like to float an analogy, there's super markets that also sell gasoline and/or have pharmacies. Walmart being one example. How those are currently tagged/mapped is that the gasoline locations are mapped as amenity=fuel, amenity=pharmacy, and so on and so forth. Obviously Walmart gas stations and pharmacies aren't mapped/tagged as shop=supermarket because Walmart is in the grocery industry.

So why do you insist on `shop=mobile_phone` for telecom retail stores??

> Like I said, it's more nuanced then just re-tagging everything with the word Vodafone into it to shop=telecommunication "because telecommunications" or whatever. Especially if you think we should do it in mass and without considering the facts on the ground. But be my guest and open an issue for Vodafone or any other company that you think is tagged wrong or needs more discussions. I'm sure some of them could be tagged better or differently 👍

Looking only from your own belfry, you won't know when it started to rust.

> Probably a lot. There's at least five people this conversation so far that do.

5 out of a few thousand active mappers. 

> Conversely, how many people in the world would be able to find their local mobile phone store on the map or in the database if it was re-tagged to shop=telecommunication? I know at least for the United States no one would, because we don't call mobile phone stores telecommunication shops. Regardless of it's a shop owned by a telecommunications company or not. 

All of them. People search using either the company name or by shop categories. Also en-US exists for a reason...

> Maybe people in a random Eastern European do, but it's clearly not the norm. In the meantime your saying 90% of them should be re-tagged. Not just ones in your niche area where people call them telecommunications shops. I don't have a problem with those being re-tagged, but again, it should be done on an individual basis after some discussion about it takes place. You can start with Vodafone or keep beating this clearly dead horse. It's your call.

Once again, I said 80% in the worst case. Don't change my words. I see that you have some problem with it.

> Not just ones in your niche area where people call them telecommunications shops. I don't have a problem with those being re-tagged, 

It's not nieceh :)

> What makes something a mobile shop then and how exactly would you know where most money the shop makes comes from anyway?

It's clearly defined in the wiki."A shop that primarily sells mobile phones and accessories.". See Germanos for a good example.
![image](https://user-images.githubusercontent.com/19364673/206968704-c9e63dc3-e24c-42cd-95e0-35d0f7b878e1.png)

> If I were to guess most the money those places make is in selling cheap discount/pre-paid phones and cheap accessories. Sure maybe people will pay the initial cost of setup in the store, but then their paying the monthly bill online or over the phone and in the meantime the store has sold 20 USB cables or MicroSD cards before the costumer has even gotten to their car. Even if you were take the average costumer, most of what they spend is on the upsold physical items they toss in as "bonuses" to new costumers.

You didn't guess right. Phones give them very little money. They can get 800 buck over two years for one phone, but they will also get 1200 bucks on the mobile plan alone in that same two years. If the customer gets a cheaper plan, he will pay 800 bucks for the plan and at least 1400 for the same phone. I doubt that many people prefer toe second option.

> Sure the process is slow and sometimes people don't comment on certain issues, but that's just how the consensus process works. This is clearly dead on arrival and IMO that's your next best avenue to have the businesses re-tagged. Take it or leave it. I don't really care, but I think you have a better shot doing that then just trying to continue milking something out of this issue.

I don't have that much free time. 

> People are always more willing to do something if done it's small, digestible bites though and you don't really need people to comment on every single one anyway. Just the majority, if even. Then the other ones will probably get re-tagged over time on their own once the precedent is set.

Then what's the point of even creating separate issues if "Just the majority (need to comment), if even"??

> [Key:shop](https://wiki.openstreetmap.org/wiki/Key:shop) "Use [shop](https://wiki.openstreetmap.org/wiki/Shops)=* to mark the location of a shop and the products that it sells." Not to be rude, but what part of "the products that it sells" has to do with what industry the company that runs the shop is in? At the end of the day f a shop sells mobile phones, then it should be tagged as shop=mobile_phone, if it doesn't then it should be mapped another way. That's it. This isn't super complicated.

See the definitions in the table that's on the same page.

shop=telecommunication - Shop selling internet, television or similar services, and related hardware. 
shop=mobile_phone - Shop focused on selling mobile phones and accessories 

By definition, a telecom company provides cellular services, TV, wired internet, wired telephony or all/most of these services (assuming it has the required licenses). Therefore you can't tag a telecom store as `shop=mobile_phone` since such kind of shop is "focused on mobile phones and accessories". 

> Not to be rude, but **what part of "the products that it sells" has to do with what industry the company that runs the shop is in**? At the end of the day f a shop sells mobile phones, then it should be tagged as shop=mobile_phone, if it doesn't then it should be mapped another way. That's it. This isn't super complicated.

> Obviously Walmart gas stations and pharmacies aren't mapped/tagged as shop=supermarket because Walmart is in the grocery industry.

I think that you answered your questions, which confirms my point that telecom stores should be tagged with `shop=telecommunications` and not `shop=mobile_phone`.

**Comment by Adamant36** [comment]
> So why do you insist on shop=mobile_phone for telecom retail stores??

Where have I at all been insist on shop=mobile_phone for telecom retail stores? All I've said is that we can't determine which ones should or shouldn't be re-tagged in bulk like your requesting and that we should open issues for particular ones you think are wrong instead. I've even said multiple times that I think [Vodafone](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone#vodafone-d7631b) could probably have a shop=telecom preset along with shop=mobile_phone. So In no way is am I insisting telecoms be tagged as shop=mobile_phone. If anything I probably agree with your assessment in general, I just disagree with this specific way of it doing it. I'm sure you get the difference between me  saying this should be done differently then how you requested versus me saying it shouldn't be done at all 🙄 

> 5 out of a few thousand active mappers.

The last time I checked your only mapper and the only one making the request. In the meantime no ones backed you here, let alone thousands of active mappers. So I don't think that's the great point you apparently think it is. Personally it's between 6 people clearly rejecting something versus 1 person failing to get the point because their unwilling to do what I've suggested I'm always going to go with the 6 people 🤷‍♂️ 

> Once again, I said 80% in the worst case. Don't change my words.

In your original comment you said ~85-90. Then you walked it back to 80% after it was clear that number was untenable. It's not if it's like 80%, 70%, or 60% in the worst case that it magically changes this or how to have them re-tagged though. But sure, you originally said ~85-90. Now you've changed it to 80% and it's still not a workable idea. Great. So what? 

> I don't have that much free time.

🤷‍♂️ This was opened six days ago. You've made 5 comments since then. That could have been like 12 issues, or 10% of the companies you want re-tagged. I'm sure you could find the time if you really wanted to. 

> They can get 800 buck over two years for one phone, but they will also get 1200 bucks on the mobile plan alone in that same two years.

Sure, but the parent company is the one that's being paid in that case. Not the individual shops. Most people don't go into the shop to pay their monthly bills. Again, it's what the **shop primarily sells.** Not what some telecom companies corporate headquarters say they make the most profit off in any given year. Which I agree is probably from selling services, but that's not what your average Joe Blow mom and pop franchise store is primarily selling, let alone making most of their money from.

**Comment by m-hue** [comment]
Interesting discussion. My $0.02:  
1. As far as the shop/mobile_phone vs shop/telecommunications question is concerned, I'm pretty much with @Dimitar5555 - IMO, semantically, a T-Mobile (or any other brand) retail outlet is _not_ primarily a store that sells phones. It's a store that sells cell phone service (or, more broadly, telecoms services, if we wanna call it that). Sure, phones are part of that. 
Looking at T-Mobile US' latest annual report as an example, they made  only ~25% of their revenue with equipment. Also, devices are often sold at super slim margins to get people locked into an agreement that produces steady, projectable cash flows for months and years to come. Another way of thinking of it: a carrier essentially has to(!) sell the equipment at low margins to justify the "you're stuck with me for the next x years" aspect of the transaction. Selling a carrier-locked phone without a discount on the the retail price of an unlocked one isn't really gonna scale well.

In the end however, I don't see sales volume (or even profit) as the main argument here. (We don't tag gas stations as liquor stores either, even though they may make more money off of booze vs. gas). What is the most convincing to me is this: I can go to a tmobile/verizon/... store to buy service, and I may or may not buy a phone. Buying just a phone, but no service may be technically possible (not sure), but it sounds...unusual, at the very least.

Also, the argument of carrrier-unlocked devices not being a thing in the US is not entirely accurate either. Sure, discounted carrier-locked devices are more popular here than they are in Europe, but that doesn't mean that unlocked phones don't exist in the US. Think Best Buy, or any electronics store really. Or even Samsung, Apple, Google etc. directly. It's a thing, and it has been for many years. 
In my opinion, the cleanest way would be to tag stores that primarily sell phones and accessories (not service!) as shop=mobile_phone, and stores that primarily sell service (typically one network only, may also sell equipment) as shop=telecommunications. The tmobile's,  verizon's and metro's of the world would mostly fall into the latter category. This would appear to be consistent with the definitions in the wiki (but it is not how the overwhelming majority of these places are mapped in reality).

2. Process wise, I'm more with @Adamant36 - historically, these types of businesses have mostly been tagged as mobile_phone; honestly, I haven't seen any tagged as telecoms around the area I'm typically mapping in. I don't believe that the NSI is the right place to make this big of a change - this is more of a "we may want to reconsider how this is being mapped" question than it is a "we want these places to be mapped consistently" question. Introducing this type of (bulk) change through the NSI sounds like it would create a lot of conflict that keeps everyone busy and upset, but adds little value if there isn't prior consensus on it being mapped that way. If someone truly has strong feelings towards changing how we map these stores, a [proposal](https://wiki.openstreetmap.org/wiki/Proposal_process) or at least a discussion on the shop/mobile_phone or shop/telecommunications talk pages of the wiki may be the better starting point - to get a more representative picture than this discussion and to ensure that there actually is consensus first.

3. Finally, and this is somewhat meta, everyone _please_ be civil. Condescending language is neither supporting anyone's point, nor does it help the project overall.

@bhousel is pull request #3130 really the one you intended to reference? Sounds kind of unrelated to me, or am I missing something?

**Comment by Adamant36** [comment]
> Looking at T-Mobile US' latest annual report as an example, they made only ~25% of their revenue with equipment.'

Yeah sure, I've been pretty clear that I think T-Mobile corporate office in Bellevue, Washington probably makes most of their money from services. We aren't mapping T-Mobile's corporate office though. In the meantime I can guarantee the specific mobile phone store franchises we are actually mapping don't make most of their profits from monthly plans. It's ridiculous to act like they do. Even if they did, no one seriously thinks we should be making tagging decisions based on annual financial reports 🙄 

> Also, devices are often sold at super slim margins to get people locked into an agreement that produces steady, projectable cash flows for months and years to come.

Usually it's like 10% to 15%, which is about average for consumer electronics. Like with computers it can be anywhere from 8% to 15% depending on the computer and brand. So it's not particularly super slim for the industry. If anything it's pretty high margins compared to other business sectors. Like with supermarkets they make an average of 1% to 3% percent. So you can say they don't make money off devices, but it's actually quite a lot of money regardless. That said, you'd have to compare it to how much the individual stores make in commissions from selling the phone plans. Like I said, most people don't pay their bills in the store anymore and I can guarantee my local T-Mobile store doesn't get paid residual commissions on payments that aren't being made to them directly. 

So say a person only pays their bill in the original store that they signed up at twice a year and the store is only making a 5% commission on it to begin with, they aren't making jack from that steady stream of income because it's going to straight to corporate the other 10 months of the year when the costumer pays through their phone or whatever. So at the end of the day it either balances out, or the store makes less from services then they do phones and accessories. That's why they have to keep upselling and close down pretty frequently. It's not like they can just sell a years worth of costumers phone service and then sit on their loreals the rest of the time because of agreements. If anything, the stores don't get jack after they make the initial sale.

> that doesn't mean that unlocked phones don't exist in the US. Think Best Buy, or any electronics store really. Or even Samsung, Apple, Google etc. directly. It's a thing, and it has been for many years.

I never said unlocked phones don't exist in the US. You can get them at electronics stores sometimes, but mostly the phones have to be for the main three companies that you mentioned. I can't just go into T-Mobile and have them sell me an unlocked iPhone though, let alone an off brand, and that's what we are talking about here. Not what type of phones we can buy from some rando at a flee market or whatever, obviously. At the end of the day carrier branded mobile phone shops are only going to sell phones that are locked into that brands services. 

> the cleanest way would be to tag stores that primarily sell phones and accessories (not service!) as shop=mobile_phone, and stores that primarily sell service (typically one network only, may also sell equipment) as shop=telecommunications.

OK. Say I agree with you. Then what about stores that just sell cable/internet without the phones or phone accessories? How are we supposed to tag those differently then places that primarily sell phones and accessories if both are being tagged as shop=telecommunication? Or does it not really matter?

**Comment by bhousel** [comment]
> @bhousel is pull request #3130 really the one you intended to reference? Sounds kind of unrelated to me, or am I missing something?

sorry, I meant #3120

I am not going to read this entire thread.  I'm getting seriously pissed off at how things are trending on this project, and OSM more generally.  Maybe in 2015 or 2017 this was fun, but it's 2022 now and I don't have the patience anymore for long philosophical tagging discussions and it isn't fun anymore.

If you're here to build a useful open map of the world, then welcome. 
 
If you're here to argue about what words mean, please leave.  Take it to a mailing list, wikipedia talk page, diary post, hold a vote, whatever.  Let me know what you decide and I'll support it if it makes sense and works technically.

I'll be making changes soon to the NSI project if things continue this way.

**Comment by m-hue** [comment]
@Adamant36 
I'd invite you to obtain a financial statement from one of the telcos. They actually report the revenue from selling devices (Tmobile calls this "Equipment revenues", Verizon calls it "Wireless equipment revenues") as well as the cost of the devices they sell ( "Cost of equipment sales" and "cost of wireless equipment" respectively). You'll be shocked, more often than not equipment sales result in a negative _gross_ profit (=they sell it at a loss). The GP obviously doesn't even take into account the operating expenses (wages, rent, ...) yet. You'd deduct these from the GP to get to net income. If you account for that, the losses would be even steeper.
The ~3% profit you typically see in the grocery industry is _net_ profit (=after operating expenses). Most grocers' GP is significantly higher (e.g. Walmart, Kroger and Publix all reported GP margins between 20% and 25% for Q3/2020, which is not untypical at all). The numbers you're referencing (8-15% profit on phones, the conclusion that  that's a "pretty high margin compared to other business sectors", mixing gross and net (?) etc.) make me wonder whether you're basing these statements on personal assumptions rather than verifiable facts. 

Oh, and
>I never said unlocked phones don't exist in the US. 
"[...]They aren't really sold in the United States except on Ebay[...]" kind of came across like you were trying to imply exactly that.

Anyway - you appear to have made up your mind. That's fine, agree to disagree.

The main point I was trying to make is that this is a great place to _document_ tagging best practices, but not so much to _redefine_ tagging. I think consensus on how things should be tagged needs to be reached elsewhere; especially in situations like these, where the documentation (wiki) is not at all consistent with how things are actually being tagged. I believe we're on the same page as far as that's concerned.

**Comment by ilias52730** [comment]
See https://community.openstreetmap.org/t/rfc-feature-proposal-shop-telecommunication/135231
