### ISSUE TITLE
A question about multinational brand in different locationSet

### ISSUE THREAD

**Issue by iigmir** [osmlab/name-suggestion-index#7581]
There's a thing that deeply confused me when seeing the project: For multinational brands, some brands were put in the same brand in different regions/locations, while others separate them. I don't, exactly understand when to separate them or put them together.

Take `data/brands/amenity/restaurant.json` for example: I once believed that the NSI should deal with such cases like the "大戸屋" (`"id": "ootoya-d30421"`) one. But then I see "寿司郎"(`sushiro-22b83d`) only includes `cn`, "壽司郎"(`sushiro-aafd63`) only includes `tw`, and "壽司郎 Sushiro"(`"id": "sushiro-8b6c9a"`) only includes `hk`. I don't understand the difference between these items.

Things get more confusing when seeing the Ichibanya one: `cn` is included in both CoCo Ichibanya(`"id": "cocoichibanya-365649"`) and CoCo壹番屋咖喱 (`"id": "cocoichibanya-2b8b0b"`).

Tried to search if there are issues with it, but don't see a satisfactory one.

If I have to separate countries that share the same multinational brands, what's the guide to separating?

**Comment by 1ec5** [comment]
A brand can have multiple entries because its details (like the correct `name` to use) differs from one country to another. In reality, many brands have different branding practices from country to country, based on the local language or other factors. Additionally, some local communities in OSM have their own expectations about how things are tagged, even multinational brands.

**Comment by iigmir** [comment]
Well, I understand the reason why. It looks like I need to consult local communities for practice details. Thank you.
