### ISSUE TITLE
Fix requests

### ISSUE THREAD

**Issue by RicTimeMuseum** [osmlab/name-suggestion-index#7997]
Some fix requests below: 
1. Please add "cn" on Line 10080 at https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/fast_food.json . There're also serveal Cafe de Coral restaurants in Mainland China. 
2. Please remove the default values of "operator" parameters in below

书亦烧仙草 (on Line 4379 at https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/cafe.json)
中油碧辟 (on Line 6690 at https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/fuel.json)
樊登书店 (on Line 1513 at https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/shop/books.json)

because instead of the current default values, this parameter should be filled with the actural operators of the branches 

(e.g., 

"惠州市惠城区回南天餐饮店" for 书亦烧仙草 on node 10657852528
"中油碧辟石油有限公司惠州大湖溪加油站" for 中油碧辟 in way 1152612859
"惠州市知了文化传播有限公司" for 樊登书店 on node 10670028440).

**Comment by LaoshuBaby** [comment]
> "惠州市惠城区回南天餐饮店" for 书亦烧仙草 on node 10657852528
> "中油碧辟石油有限公司惠州大湖溪加油站" for 中油碧辟 in way 1152612859
> "惠州市知了文化传播有限公司" for 樊登书店 on node 10670028440).

1.2. 对于个体户餐饮店的情况，不建议将其认为operator，OSM不是用来查户口的。既然是连锁品牌，至少应是地区性的经营公司，不过如果全国范围内各省各地负责落地运营的实体不统一，确实不适合规定operator。

3. 查询后发现樊登读书会应是一个brand，确实不应作为具体书店的operator。

1.2. For the case of self-employed/small-business restaurants, it is not recommended to be regarded as an operator, and I think such detailed data don't recommend to be collected in OSM. Since it is a chain brand, operator should at least be a regional operating company. However, if the entities responsible for landing operations in various provinces and regions across the country are not unified, it is really not suitable to specify the operator.

3. After research, it was found that 樊登读书会 should be a brand, and it should not be the operator of a specific bookstore.

感谢您的建议， 已经做出修正

Thank you for your advice. has been corrected
