### ISSUE TITLE
Correct logo for PTT gas station

### ISSUE THREAD

**Issue by TagaSanPedroAko** [osmlab/name-suggestion-index#8042]
The logos for PTT gas station are still incorrect for years (it should be one with a dark blue droplet with red circle and resembling a blue flame).

**Comment by 1ec5** [comment]
The logo comes from the [PTTNews](https://www.facebook.com/PTTNews) Facebook account, which is linked from [this Wikidata item](https://www.wikidata.org/wiki/Special:PermanentLink/1871682962#P2013), which is linked from this NSI entry:

https://github.com/osmlab/name-suggestion-index/blob/fc157a5ca5208536f92423f9b22b0995379d0fb8/data/brands/amenity/fuel.json#L3905

This Facebook account claims to belong to the oil company; is that not the case? If it does belong to the same company but they’ve chosen an unintuitive profile picture on Facebook, there’s currently no mechanism to exclude that profile picture from consideration when converting the entry into a preset, even if Wikimedia Commons were able to provide a logo image for this brand. (It apparently can’t due to copyright.)

Some background reading: #2798 #2641 #6664 openstreetmap/iD#6361.

**Comment by TagaSanPedroAko** [comment]
Well, that's actually what it is. Closing.

**Comment by bhousel** [comment]
> there’s currently no mechanism to exclude that profile picture from consideration when converting the entry into a preset, even if Wikimedia Commons were able to provide a logo image for this brand.

FWIW we actually do have a few hardcoded brands where we prefer the Wikimedia Commons logo over the social media profile pic.  Fortunately this is rare.

https://github.com/osmlab/name-suggestion-index/blob/80f0d9bfbd8464e92fbb610001ad55db09d09b6d/scripts/dist_files.js#L287-L294

**Comment by 1ec5** [comment]
Ah, there it is. I thought we did something like that after KFC started showing off but couldn’t find it. 👍
