### ISSUE TITLE
Sort semicolon separated values alphabetically

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#8397]
Is it possible to automatically sort semicolon separated values in an alphabetical order?
Especially for e.g. `cuisine=*` or `clothes=*` the collected values appear pretty random, see [taginfo.json](https://github.com/osmlab/name-suggestion-index/blob/0cf46e39294259d0362d849474bd4722fe51f680/dist/taginfo.json#L220C2-L256) for reference.

**Comment by bhousel** [comment]
They are supposed to be sorted by order of importance, not alphabetical.

**Comment by kjonosm** [comment]
Hmm, I find it hard to interpret an order by importance when many used values are orthogonal/complimentary as in `cuisine=country/dish` or `clothes=style/target group`

**Comment by 1ec5** [comment]
> many used values are orthogonal/complimentary as in `cuisine=country/dish` or `clothes=style/target group`

As you’ve noted, the convention is often to put national cuisines before dishes or food types and styles before demographics – more general types of values before more specific types of values. However, there are exceptions. In OSM overall, `cuisine=italian;pizza` and `cuisine=pizza;italian` are both common: an Italian restaurant is not guaranteed to serve pizza, so appending `pizza` emphasizes that offering. Conversely, a pizza parlor is not necessarily particularly Italian (hello California Pizza Kitchen), so one that carries other Italian fare needs to indicate that somehow. `american;burger` and `burger;american` are neck and neck, maybe for the same reason.

If NSI is ordering the values inconsistently among entries that otherwise belong in the same category, we should fix that, but merely alphabetizing the values wouldn’t add any information.

**Comment by 1ec5** [comment]
I started a discussion [on the wiki](https://wiki.openstreetmap.org/wiki/Talk:Key:cuisine#Significance_of_value_order) because it seems like everyone thinks there’s a consensus but differ on what that consensus is.

**Comment by bhousel** [comment]
I think the tl;dr is that many data consumers aren't going to bother with semicolon-delimited values, and they just take the first one in the list, so that first one should be the most important.

**Comment by kjonosm** [comment]
According to [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:cuisine) the order of values is not important:

> Values can be combined using the [semi-colon value separator](https://wiki.openstreetmap.org/wiki/Semi-colon_value_separator). For example, cuisine=[donut;coffee_shop](https://wiki.openstreetmap.org/w/index.php?title=Tag:cuisine%3Ddonut;coffee_shop&action=edit&redlink=1) denotes a place that specializes in both donuts and coffee, or cuisine=[italian;pizza](https://wiki.openstreetmap.org/w/index.php?title=Tag:cuisine%3Ditalian;pizza&action=edit&redlink=1) denotes an Italian restaurant that specializes in pizza. **The order is not important.**

**Comment by bhousel** [comment]
> According to [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:cuisine) the order of values is not important:

Yep, that guidance changed in this diff with no discussion and the comment "remove outdated information"
https://wiki.openstreetmap.org/w/index.php?title=Key:cuisine&diff=prev&oldid=2428982

Someone should change it back to what it said before 😆

**Comment by 1ec5** [comment]
Without speaking for the author of that change, I suspect the reason for the back-and-forth is that the order doesn’t matter as much when there are multiple values of the same kind – does it serve burritos and tacos or tacos and burritos? – but probably matters more when there are values of different kinds. This is why we don’t glom orthogonal information into the same key. 🤷‍♂️

Anyhow, NSI definitely isn’t an outlier when it comes to keeping `cuisine` values in non-alphabetical order, so I think this issue would only be actionable if there are entries where the `cuisine` order is flat-out incorrect according to any of these sort orders.

**Comment by bhousel** [comment]
Closing here, please change the OSM wiki back to what it said before.
