### ISSUE TITLE
"Boss (boss-ceeccb)" -> missing tag? -> "vending"

### ISSUE THREAD

**Issue by AntiCompositeNumber** [osmlab/name-suggestion-index#8928]
[boss-ceeccb](https://nsi.guide/index.html?t=brands&k=amenity&v=vending_machine&tt=boss#boss-ceeccb) appears to be https://ja.wikipedia.org/wiki/%E3%83%9C%E3%82%B9_(%E3%82%B3%E3%83%BC%E3%83%92%E3%83%BC) https://www.wikidata.org/wiki/Q4947502. It appears there is also a matchNames for [suntory-bf11a2](https://nsi.guide/index.html?t=brands&k=amenity&v=vending_machine&tt=boss#suntory-bf11a2) (the parent company). 

There are [a large number](https://overpass-turbo.eu/s/1Dfm) of vending machines with `brand=Boss` in Japan, which signals to me that it might actually be a distinct brand. 

This is what I had before I noticed the matchNames:
```
    {
      "displayName": "Boss",
      "id": "boss-bf11a2",
      "locationSet": {"include": ["jp"]},
      "tags": {
        "amenity": "vending_machine",
        "brand": "Boss",
        "brand:en": "Boss",
        "brand:ja": "ボス",
        "brand:wikidata": "Q4947502",
        "drink:coffee": "bottled",
        "name": "Boss",
        "name:en": "Boss",
        "name:ja": "ボス",
        "vending": "coffee"
      }
    },
```

**Comment by AntiCompositeNumber** [comment]
Looks like the matchNames was added by @ffff-23 in #8254 about 5 months ago. So it might just be that the existing vending machines haven't been re-tagged yet.

**Comment by ffff-23** [comment]
Hi, @AntiCompositeNumber I thought BOSS is a part of Suntory and added it to matchNames in Suntory.

![IMG_2353](https://github.com/osmlab/name-suggestion-index/assets/72978935/ae628d01-4ba9-406f-aa5a-7fd17316dd4d)


This may be similar to the relationship between [Asahi Soft Drinks](https://nsi.guide/index.html?t=brands&k=amenity&v=vending_machine#asahisoftdrinks-bf11a2) and [Calpis](https://nsi.guide/index.html?t=brands&k=amenity&v=vending_machine#calpis-bf11a2).

![IMG_2336](https://github.com/osmlab/name-suggestion-index/assets/72978935/3f3ffcc3-4bfe-4f7c-9e8e-672e4748729d)
![IMG_2339](https://github.com/osmlab/name-suggestion-index/assets/72978935/6bc4f2af-4f60-4148-bdfd-eda5cce914f5)


Is it better to add a new item as BOSS instead of matchNames?
