### ISSUE TITLE
Add Continente Bom Dia to supermarket in Portugal

### ISSUE THREAD

**Issue by DiogoBaptista98** [osmlab/name-suggestion-index#8978]
Add Continente Bom Dia to supermarket in Portugal
https://www.wikidata.org/wiki/Q123570507

brand=Continente Bom Dia
brand:wikidata=Q123570507
building=yes
name=Continente Bom Dia
shop=supermarket

**Comment by DiogoBaptista98** [comment]
2 weeks for this?

**Comment by LaoshuBaby** [comment]
Sorry for the delay on this ticket, I found 2 similar supermarket already added to NSI

https://github.com/osmlab/name-suggestion-index/blob/996ea9260b4e31dbd1fd0c221a2b599d3b466bad/data/brands/shop/supermarket.json#L1520-L1541

Please confirm whether there is a duplicate entity with the "Continente Bom Dia" you described, or is it 3 different brand(Continente, Continente Modelo, Continente Bom Dia) operator by same company?

Because I saw that their Wikidata items are the same on P856 (Official Website) http://www.continente.pt/

---

Additional, you can see that there are currently hundreds of issues that need to be dealt with, and many of them require manual addition of brand content. If you have certain computer skills (such as understanding json format), you can try to raise a PR directly. That's faster

**Comment by DiogoBaptista98** [comment]
> Sorry for the delay on this ticket, I found 2 similar supermarket already added to NSI
> 
> https://github.com/osmlab/name-suggestion-index/blob/996ea9260b4e31dbd1fd0c221a2b599d3b466bad/data/brands/shop/supermarket.json#L1520-L1541
> 
> Please confirm whether there is a duplicate entity with the "Continente Bom Dia" you described, or is it 3 different brand(Continente, Continente Modelo, Continente Bom Dia) operator by same company?
> 
> Because I saw that their Wikidata items are the same on P856 (Official Website) http://www.continente.pt/
> 
> Additional, you can see that there are currently hundreds of issues that need to be dealt with, and many of them require manual addition of brand content. If you have certain computer skills (such as understanding json format), you can try to raise a PR directly. That's faster

You’re right, this are 3 different supermarket brands by the same company.
