### ISSUE TITLE
Ukrtelecom

### ISSUE THREAD

**Issue by MortalEngineXXII** [osmlab/name-suggestion-index#9003]
The description of this company is inaccurate. "shop=telecommunication" is specified, but "office=telecommunication" is better because this company provides telephone, Internet access and television services

Link https://nsi.guide/?t=brands&k=shop&v=telecommunication#ukrtelecom-19c022

Article in Wikipedia https://en.wikipedia.org/wiki/Ukrtelecom

**Comment by bhousel** [comment]
We really haven't used `office=telecommunication` since around #3120 and the `shop=telecommunication` tag became more accepted: https://wiki.openstreetmap.org/wiki/Tag:shop%3Dtelecommunication

In general:
- `shop` is used for retail locations where the public can walk in without appointment and buy things
- `office` is used for corporate locations where you are expected to have an appointment to go there and meet with an employee

**Comment by MortalEngineXXII** [comment]
Ok, thanks!

**Comment by Dimitar5555** [comment]
I don't see anything that needs doing here. I assume that we can close the issue?

**Comment by MortalEngineXXII** [comment]
Yes, thanks!
