### ISSUE TITLE
Dynamically generate contact information as part of the NSI Hints from Wikidata

### ISSUE THREAD

**Issue by balporig** [osmlab/name-suggestion-index#9156]
The current hints in iD and other supported editors are great but a when creating new POIs a tedious step is adding contact information like websites, phones and socials over and over again. Besides phones, websites and social usually are static between chain/operator branches. Also, just as before with the `cannonical` names, this can bring some more consistency and remove the contributor burden to maintain one more thing.

Given that most NSI entries have `brand:wikidata` or `operator:wikidata` and the contact information is already fetched from Wikidata when generating `dist/wikidata.json` in the `identities` and `officialWebsites` keys, why not use them to add to the existing entry tags (merge) for each one of those:

```json
"tags":  {
  "website": "",
  "contact:facebook": "",
  "contact:instagram": "",
  ....
}
```
For e.g. let's pick this operator from `operators/amenity/drinking_water.json`

```json
    {
      "displayName": "City of Denton",
      "id": "cityofdenton-6aaee1",
      "locationSet": {
        "include": ["us-tx.geojson"]
      },
      "tags": {
        "amenity": "drinking_water",
        "operator": "City of Denton",
        "operator:type": "government",
        "operator:wikidata": "Q128306"
      }
    },
```

this is what we have fetched in `wikidata.json` for `Q128306`

```json
    "Q128306": {
      "description": "city in Denton County, Texas, United States",
      "identities": {"website": "https://www.cityofdenton.com/"},
      "label": "Denton",
      "officialWebsites": ["https://www.cityofdenton.com/"]
    },
```

so we end up with

```json
    {
      "displayName": "City of Denton",
      "id": "cityofdenton-6aaee1",
      "locationSet": {
        "include": ["us-tx.geojson"]
      },
      "tags": {
        "amenity": "drinking_water",
        "operator": "City of Denton",
        "operator:type": "government",
        "operator:wikidata": "Q128306",
        "website": "https://www.cityofdenton.com/"
      }
    },
```

This is offline only transformation with the data we already have and probably will require minimal to no changes in the editors.
The transformation can be added to run on each release so that the information is up-to-date.

**Comment by 1ec5** [comment]
Contact information is rarely consistent across a large brand. In particular, a franchisor often has one website and one set of social media accounts, while each franchisee might have a different set. And even though the franchisee can be tagged as the `operator`, it might have different contact information depending on the brand or from store location to store location. In the U.S., this is the case with almost every car dealership that’s part of a dealer group. Similarly, many restaurants that are part of the same chain have their own Facebook pages in order to advertise local promotions.

If what you want to tag is how to contact the operator or the brand, rather than the individual POI itself, that would be e.g., `operator:website` and `brand:facebook`. But these things aren’t usually tagged because they’re too tangential to OSM; a data consumer might as well look it up on Wikidata.
