### ISSUE TITLE
Add name suggestions for common trees

### ISSUE THREAD

**Issue by tordans** [osmlab/name-suggestion-index#94]
I have two issues which could be solved with this idea:

a. For each tree I add, I have to do a lot of clicks to specify `leaf_type` and `leaf_cycle`. That is very tedious, especially since in my region both have a relation in nearly all cases (as in "nearly all trees which are broadleaved are also deciduous, nearly all trees which are needleleaved are also evergreen").

b. I nearly never tag the type/genus, because I need to look up the correct spelling to not mess up the database. Even though in quite some cases I could at least specify the broader genus (as in, I know that a tree is a `genus:de=Eiche` (EN: Oak), but I would not know that it is a `species:de=Stieleiche`).

This would also solve different spelling like "oak" (taginfo:43), "Oak" (taginfo:15), "en:Oak" (taginfo:2)

### My suggestion:

Add name suggestion for some commonly used trees.

Commonly could be defined as "all that have been tagged > 1000"
- https://taginfo.openstreetmap.org/keys/genus#values ~60
- https://taginfo.openstreetmap.org/keys/genus:de#values ~20 with GER names

### Example

Suggestion name EN: `Tree: Oak tree`
Suggestion name DE: `Baum: Eiche`
Tags:
```
leaf_type=broadleaved
leaf_cycle=deciduous
genus=Oak
genus:de=Eiche
```

Suggestion name EN: `Tree: Picea tree`
Suggestion name DE: `Baum: Fichte`
Tags:
```
leaf_type=needleleaved
leaf_cycle=evergreen
genus=Picea
species:de=Fichte
```

Wiki pages about trees:
- EN https://wiki.openstreetmap.org/wiki/Tag:natural%3Dtree
- DE https://wiki.openstreetmap.org/wiki/DE:Tag:natural%3Dtree

Would this name-suggestion-index be the right place for this idea?

**Comment by bhousel** [comment]
I think iD is probably a better place for this, since it would be a curated list of the most common tree presets - `name_suggestion_index` is really for things with names.

I've put my thoughts on tree presets here: https://github.com/openstreetmap/iD/issues/4240  and I'm reluctant to take this up right now.  (please add your comments to that issue instead of opening a new one).  

If it's really true that we could make the tree presets usable for untrained users, then I would be ok with it.
