### ISSUE TITLE
Country filter does not filter only countries

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#9540]
https://nsi.guide/index.html?t=brands&k=amenity&v=atm&cc=pl

I would expect it to show global entries and ones in Poland.

![screen07](https://github.com/osmlab/name-suggestion-index/assets/899988/00d35517-de78-4d63-a761-ca4dad6d0bb3)
![screen06](https://github.com/osmlab/name-suggestion-index/assets/899988/6ebd9940-1296-4af0-a8e1-5d3de3591a0b)

Instead it includes also other entries like

https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/bank.json#L9510

```
    {
      "displayName": "People's United Bank",
      "id": "peoplesunitedbank-28419b",
      "locationSet": {
        "include": [
          "peoples_united_bank_ct.geojson"
        ]
      },
      "tags": {
        "amenity": "bank",
        "brand": "People's United Bank",
        "brand:wikidata": "Q7165802",
        "name": "People's United Bank"
      }
    },
```
not within Poland.

(maybe these get in due to geojson-specified area, obnoxious to filter by country code? But then maybe it can show up with note, not with random `pl` being highlighted?)

**Comment by mnalis** [comment]
I'd guess the quick fix for this particular problem would be that website does not match country as `pl` but as `"pl` instead - `"pl"` (with the trailing quote) would produce less false positives, but would also prevent matching things like `"gb-sct"`).

---

However, it seems that https://nsi.guide/ website only does the **simplest matching** for that country in entered, i.e. if you entered specific country code, it won't match:

1. things that are present it whole world - e.g. searching for [amenity=parcel_locker](https://nsi.guide/index.html?t=brands&k=amenity&v=parcel_locker) in `pl` will not find `GLS`, even if it has `[{"include":["001"]}]` (i.e. whole world)
2. any other [UNM_49](https://en.wikipedia.org/wiki/UN_M49) numeric codes (like e.g. `"039"` for Southern Europe)
3. manually defined polygons as in that example, wikidata QIDs, and other [more complex cases](https://github.com/osmlab/name-suggestion-index/wiki/Item-Property-Reference#locationset) like e.g. that specific one [peoples_united_bank_ct.geojson](https://raw.githubusercontent.com/osmlab/name-suggestion-index/d71ffd472556269fd8cbb5f7c4be663f344edb32/features/us/peoples_united_bank_ct.geojson)

While the first (whole world) could be added relatively easily manually, second is noticeably harder, and third near impossible. 

I'm not sure if implement just `1.` would make it less confusing, although it would cover many popular cases. [Wiki](https://github.com/osmlab/name-suggestion-index/wiki/Item-Property-Reference#locationset-tips) lists  [@ideditor/location-conflation](https://github.com/ideditor/location-conflation/blob/main/README.md) which perhaps could be used for more complete country-matching support. 

How much work that would be implementing that (including detecting country polygon crossing manually specified polygon to get full support), I don't know... Perhaps UI should then be changed so that instead of typing a country code, you pick a single point on the map, and it finds all polygons that this point is inside...

---

What is more confusing to me is why it is showing you _"People's United Bank"_ which is marked as _dissolved_,  and you have not checked "Dissolved" checkbox.

**Comment by peternewman** [comment]
I think this is just a duplicate of #4077 isn't it?

**Comment by matkoniecz** [comment]
Yep, duplicate of #4077
