### ISSUE TITLE
Exclude Sagawa,Yamato from post_box

### ISSUE THREAD

**Issue by ffff-23** [osmlab/name-suggestion-index#9771]
In Japan, only 'Japan Post(日本郵便)' uses amenity=post_box

Is it possible to exclude Sagawa Express(sagawaexpress-f7cda2) and Yamato Transport(yamatotransport-f7cda2) from [post_box](https://nsi.guide/index.html?t=operators&k=amenity&v=post_box&cc=jp)?

**Comment by LaoshuBaby** [comment]
Very thank you for open this issue because I found same situation in China, some commercial express parcel service, called "快递" (like Yamato in Japan, such kind of "たくはいびん"), are all listed here in [post_box](https://nsi.guide/index.html?t=operators&k=amenity&v=post_box&cc=cn), I think this truly a confusing problem 

However this may need change inherit of "post_office -> post_box" and even change build script, so I guess this need some core developer's help.

Anyway, thank you for your interest in this project and for finding this issue!

**Comment by AntiCompositeNumber** [comment]
@LaoshuBaby You can use the `templateExclude` property to exclude ids from the template, see https://github.com/osmlab/name-suggestion-index/wiki/Item-Property-Reference#templateexclude. 

We can leave this open until the next release to confirm that the entries were removed.

**Comment by ffff-23** [comment]
Thank you @AntiCompositeNumber I confirm that the entries has been removed from the list.
