### ISSUE TITLE
add indonesian ferry companies

### ISSUE THREAD

**Issue by koenvanhollebeke** [osmlab/name-suggestion-index#9963]
Please add the following indonesian ferry companies:

- PT. Pelni (Q1393397)
  network = Pelni
  network:wikidata = Q1393397
  route = ferry
- PT. ASDP Indonesian Ferry (Q97671497)
  network = ASDP
  network:wikidata = Q97671497
  route = ferry

**Comment by koenvanhollebeke** [comment]
Thanks for adding the ferry companies. Maybe a stupid question: when do they appear on the https://nsi.guide/index.html?t=transit&k=route&v=ferry site?

**Comment by Snowysauce** [comment]
> Thanks for adding the ferry companies.

You're welcome!

> Maybe a stupid question: when do they appear on the https://nsi.guide/index.html?t=transit&k=route&v=ferry site?

Your question is one I'd imagine a lot of contributors have, so I don't think it's a bad question at all. The online NSI guide gets updated whenever a new version of the NSI is [packaged for distribution](https://github.com/osmlab/name-suggestion-index/wiki/Info-for-Maintainers#releasing) to downstream consumers like OSM's iD editor or JOSM. This process typically takes place every couple of weeks or so, and was most recently completed on September 9.

**Comment by koenvanhollebeke** [comment]
OK, thanks a lot.

**Comment by koenvanhollebeke** [comment]
Hi,

OSM now automatically finds the network (ASDP, Pelni). 

One question/remark: the automatical tagging applies on nodes, ways and relations in OSM. 
Practically it is annoying that a **way** for route=ferry is automatically suggested for tagging. Compared with a bus route, this would be like wanting to tag with the network all streets for that bus company. No idea if the tagging for ferry route (ASDP/Pelni) can exclude way and only be applicable on nodes & relations?

Kind regards,
Koen

**Comment by Snowysauce** [comment]
> No idea if the tagging for ferry route (ASDP/Pelni) can exclude way and only be applicable on nodes & relations?

Unfortunately, no. The matcher code only looks for `route=ferry` and `network=ASDP` (or Pelni), and will suggest the tags for anything matching that criteria regardless of object type.

> Practically it is annoying that a **way** for route=ferry is automatically suggested for tagging. Compared with a bus route, this would be like wanting to tag with the network all streets for that bus company.

I understand the comparison, but there's a key difference. The lines operated by bus networks are routed along tangible, physically distinct roads which have specific owners and maintainers, while ferry routes are arbitrary paths across open water (which of course has no owners or maintainers). I'd imagine that this difference is why the primary tag of road segments is `highway=*` instead of other tags (like `route=bus`) while ferry segments and route networks alike use `route=ferry`.
